### PR TITLE
ffi.C triggers undefined symbol error in turbo

### PR DESCRIPTION
**Pull request by Hzj-jie**
My fault in last patch, ffi.C.signal or ffi.C.sysv_signal won't work in ffi.C.

### CODE REVIEW

**Comment by houqp** [comment]
Feel free to  merge this yourself after rebased on the latest master

**Comment by chrox** [comment]
Yes, dogfooding will prevent it from happening.

B.t.w, your git flow seems rather wrong, how did to make this `Merge remote-tracking branch 'upstream/master'` commit, it's not good-looking and has no meaning at all (there is not a single line of code change).

Good git flow is like this:
```
git checkout -b your_branch upstream/master
# do something
git add your_file
git commit -m "your message"
# in case the upstream master branch has new commits
git rebase upstream/master
git push origin your_branch
# in case you need to modify your commit
git add your_another_file
git commit --amend --no-edit
git push origin your_branch -f
```
And send a pull request on GitHub site.

In this way you don't need to manually merge upstream branch at all and you should not do that manually since the merge action is supposed to be done in the GitHub web page after someone has reviewed your code.

**Comment by chrox** [comment]
How about rebuilding your pull request like this?
```
git remote add upstream https://github.com/koreader/koreader-base.git
git checkout -b fix_turbo upstream/master
git cherry-pick ab66edf
git push origin fix_turbo
```

**Comment by chrox** [comment]
Nice.

**Pull request merged**
