### PR TITLE
fix fribidi includes

### PR DESCRIPTION
**Pull request by benoit-pierre**
```bash
▸ pkg-config --cflags fribidi
-I/usr/include/fribidi
```

Otherwise, using `fribidi/fribidi.h` may result in the wrong (system) include being picked up when building the emulator.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1616)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
This depends on https://github.com/koreader/crengine/pull/519.

**Comment by poire-z** [comment]
Fine with me, but not as familiar with build stuff as @NiLuJe and @Frenzie .
Btw, how is it that picking system include does not happen for other stuff ? Is it just because I added this single occurence of an include with a subdir ?

**Comment by benoit-pierre** [comment]
It does not happen right now, but if you're messing with the build system, it's easy to get the wrong include because of it.

**Review by NiLuJe — APPROVED** [review]

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
No longer needs to be "Draft" ?

**Comment by benoit-pierre** [comment]
Yeah, I was waiting for the macOS check.

**Review by Frenzie — APPROVED** [review]

**Pull request merged**
