### PR TITLE
MuPDF document loading from memory, Noto Sans support

### PR DESCRIPTION
**Pull request by TnS-hun**
MuPDF related changes:
* support loading HTML from a string
* layout HTML for a given resolution
* use Noto Sans font when requested

Needed for https://github.com/koreader/koreader/issues/1776

### CODE REVIEW

**Comment by poire-z** [comment]
Looks OK to me.

May be you could drop a few (all?) of the empty lines in mupdf.lua 's `mupdf.openDocumentFromText` , for a consistent style with the other functions ?
(If you do, could you also remove the line `M.fz_keep_image(context(), image)` in `mupdf.renderImage()` ? It's a line from 2014, and I think it may introduce some memory leaks, making the following `M.fz_drop_image` actually not releasing it, and everything seem to work fine without it.)

**Comment by Frenzie** [comment]
At a quick skim it seems fine to me too. Also pinging @houqp @chrox @NiLuJe

**Comment by TnS-hun** [comment]
> May be you could drop a few (all?) of the empty lines in mupdf.lua 's mupdf.openDocumentFromText , for a consistent style with the other functions ?

I removed two empty lines, if I remove more then the formatting will be out of sync with openDocument. :)

> (If you do, could you also remove the line M.fz_keep_image(context(), image) in mupdf.renderImage() ? 

No problem.

**Comment by poire-z** [comment]
Merging, as it's mostly new code that's not yet used by current code.

**Pull request merged**
