### PR TITLE
Bump a few thurd-party libs

### PR DESCRIPTION
**Pull request by NiLuJe**
* OpenSSL 1.0.2q
* HarfBuzz 2.1.3

### CODE REVIEW

**Comment by Frenzie** [comment]
Is our beloved gcc 4.8 causing trouble again? >_>

**Comment by NiLuJe** [comment]
Yup' ;).

**Comment by Frenzie** [comment]
The official line is to stick to older HB, btw. 
```
https://github.com/pocketbook-free/SDK_481/issues/3#issuecomment-442148725
```

**Comment by Frenzie** [comment]
Over in `https://github.com/buggins/coolreader/pull/59` it's said that newer HB is much faster. ;_;

**Comment by NiLuJe** [comment]
I thought so too, which was why I was chasing the bump... ;p.

Next version *might* possibly build again (it breaks on old VS compilers, too).

**Comment by Frenzie** [comment]
Yeah, but twice as fast? Whoa! So time to try 2.2? :-P

**Comment by NiLuJe** [comment]
2.2 still won't build, AFAICT. Next one might?

**Pull request merged**
