### PR TITLE
Bump libjpeg-turbo to 2.0.0

### PR DESCRIPTION
**Pull request by NiLuJe**
It unfortunately caught the CMake bug, so this may become fun^Whellish
pretty fast...

### CODE REVIEW

**Comment by NiLuJe** [comment]
... Waiting for the full set of red crosses. :D.

**Comment by NiLuJe** [comment]
For ref, a sane output w/ my CMakeCross thingy:

```
-- The C compiler identification is GNU 7.3.1
-- Check for working C compiler: /home/niluje/x-tools/arm-kobo-linux-gnueabihf/bin/arm-kobo-linux-gnueabihf-gcc
-- Check for working C compiler: /home/niluje/x-tools/arm-kobo-linux-gnueabihf/bin/arm-kobo-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 2.0.0, BUILD = 20180802
-- 32-bit build (arm)
-- CMAKE_INSTALL_PREFIX = /home/niluje/Kindle/CrossTool/Build_KOBO
-- CMAKE_INSTALL_BINDIR = bin (/home/niluje/Kindle/CrossTool/Build_KOBO/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/home/niluje/Kindle/CrossTool/Build_KOBO/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/home/niluje/Kindle/CrossTool/Build_KOBO/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/home/niluje/Kindle/CrossTool/Build_KOBO/include)
-- CMAKE_INSTALL_LIBDIR = lib (/home/niluje/Kindle/CrossTool/Build_KOBO/lib)
-- CMAKE_INSTALL_MANDIR = share/man (/home/niluje/Kindle/CrossTool/Build_KOBO/share/man)
-- Shared libraries disabled (ENABLE_SHARED = 0)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- In-memory source/destination managers enabled (WITH_MEM_SRCDST = 1)
-- Emulating libjpeg API/ABI v6.2 (WITH_JPEG7 = 0, WITH_JPEG8 = 0)
-- libjpeg API shared library version = 62.3.0
-- Compiler flags = -O3 -ffast-math -ftree-vectorize -funroll-loops -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard -mthumb -D_GLIBCXX_USE_CXX11_ABI=0 -pipe -fomit-frame-pointer -frename-registers -fweb -flto=9 -fuse-linker-plugin -O3 -DNDEBUG
-- Linker flags = -L/home/niluje/Kindle/CrossTool/Build_KOBO/lib -Wl,-O1 -Wl,--as-needed 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Check size of unsigned char
-- Check size of unsigned char - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Performing Test INCOMPLETE_TYPES
-- Performing Test INCOMPLETE_TYPES - Success
-- Compiler supports pointers to undefined structures.
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_VERSION_SCRIPT
-- Performing Test HAVE_VERSION_SCRIPT - Success
-- Linker supports GNU-style version scripts
-- CMAKE_EXECUTABLE_SUFFIX = 
-- The ASM compiler identification is GNU
-- Found assembler: /home/niluje/x-tools/arm-kobo-linux-gnueabihf/bin/arm-kobo-linux-gnueabihf-gcc
-- CMAKE_ASM_FLAGS = -O3 -ffast-math -ftree-vectorize -funroll-loops -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard -mthumb -D_GLIBCXX_USE_CXX11_ABI=0 -pipe -fomit-frame-pointer -frename-registers -fweb -flto=9 -fuse-linker-plugin  -O3 -DNDEBUG
-- GAS is working properly
-- SIMD extensions: arm (WITH_SIMD = 1)
-- FLOATTEST = 32bit
-- RPM architecture = arm, DEB architecture = armel
-- Configuring done
-- Generating done
-- Build files have been written to: /home/niluje/Patchland/libjpeg-turbo-2.0.0/build
```

**Comment by NiLuJe** [comment]
Protip: `$` matters.

`DEFINED VAR` != `DEFINED $VAR` -_-".

**Comment by Frenzie** [comment]
Woo CMake! :-p

**Comment by NiLuJe** [comment]
Yaaaaaay! Did I win a prize? ;D

**Pull request merged**
