### PR TITLE
move round % to utils

### PR DESCRIPTION
**Pull request by mwoz123**
required for https://github.com/koreader/koreader/pull/6048

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1081)

### CODE REVIEW

**Comment by mwoz123** [comment]
this is common part - I can duplicate it in my Change but prefered to extract common part to util.lua

**Comment by Frenzie** [comment]
But why *base* utils?

**Comment by mwoz123** [comment]
Rounding seems to be one of the basic operations that might be used at different layers of application. 
Or am I not enought familiar with the architecture of Koreader?

**Comment by Frenzie** [comment]
It seems to me like something for the Math module or front util.

https://github.com/koreader/koreader/blob/ba4e175ee63d69086723e3366492eb1c79f505e5/frontend/optmath.lua#L11-L21

https://github.com/koreader/koreader/blob/ba4e175ee63d69086723e3366492eb1c79f505e5/frontend/util.lua#L717-L725

**Comment by mwoz123** [comment]
ok

**Pull request closed without merging**
