### PR TITLE
bump crengine: text formatting: fix leading spaces issues

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- text formatting: fix leading spaces issues https://github.com/koreader/crengine/pull/204
- new English US & GB hyph patterns https://github.com/koreader/crengine/pull/206

(small bump to have nightly builds with individual changes in case we need to bissect some side effects with the recent and coming rendering fixes)

### CODE REVIEW

**Comment by poire-z** [comment]
https://github.com/koreader/koreader-base/blob/340e809afdfd1354dec1a9577efe33e1ec6d7d94/thirdparty/lua-Spore/CMakeLists.txt#L32-L37
It looks like https://github.com/fperrad/lua-Spore has disappeared :|
What's to be done in such cases?

**Comment by Frenzie** [comment]
I suspect the dev may have moved it over somewhere else due to the Microsoft takeover? If nothing turns up when looking around (sorry, no time today or tomorrow) then any one of us can (presumably) easily push a copy to a repo either here on GH or on GL but hopefully that won't be necessary.

Btw there are forks on GH though I don't know if they're up to date atm, e.g., https://github.com/LuaDist/lua-spore

**Comment by Frenzie** [comment]
Actually that one's forked from https://github.com/vladfedin/lua-Spore

But yeah, weird.

**Comment by poire-z** [comment]
Looks like it was moved to https://framagit.org/fperrad/lua-Spore (a french instance of gitlab it looks like).
(The other ones you linked haven't been updated for years, so better stick to that one).

**Comment by Frenzie** [comment]
A little "we've moved" left behind would have been nice. :-)

That Framasoft place offers a pretty interesting bunch of free software services btw.

**Pull request merged**
