### PR TITLE
Kobo sunxi support (ion buffers/disp2 display driver)

### PR DESCRIPTION
**Pull request by NiLuJe**
It shouldn't sell your firstborn to the devil, but I haven't done much testing yet, and it's arguably unfinished.

But, it boots, and it mostly works.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1386)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Missing (non exhaustive, because I'm exhausted ;p):

* Actually updating FBInk for real
* Updating KoboUSBMS (so, don't try USBMS, it won't work ^^).

**Comment by NiLuJe** [comment]
@roshavagarga: I'm afraid that, nope, turns out this won't really make the Bookeen port easier to integrate, because it looks like a fairly different beast altogether ;).

**Comment by roshavagarga** [comment]
@NiLuJe Thanks for trying either way, I was expecting it to be improbable without you having a Bookeen :)

**Review by poire-z — APPROVED** [review]
PR really really too out of my league :)
(Looked at framebuffer_mxcfb.lua, which seems fine - I assume you tested that Mk6 and Mk7 didn't break :)

**Comment by NiLuJe** [comment]
> PR really really too out of my league :)
> (Looked at framebuffer_mxcfb.lua, which seems fine - I assume you tested that Mk6 and Mk7 didn't break :)

Ahah, good point, I checked on Mk. 5, I'll give it a go on the Forma  ;p.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 14 of 19 files at r1, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Pull request merged**
