### PR TITLE
cre.findText(): fix inconsistencies in results

### PR DESCRIPTION
**Pull request by poire-z**
See details in https://github.com/koreader/koreader/pull/3656 and https://github.com/koreader/crengine/pull/94.

Don't use `rc.height()` for the height to search in, as it may be small for some pages when there is a page-break (it would then be the height of the rendered text only) - and we would only search in this area of the other page, missing occurences in the visible but not searched other area.
Better to use the view height.

Don't use `+1` or `-1` with `rc.bottom` or `rc.top`, as there may be no node at this +/-1 location, and search would abort. So, use them directly.

Still, even when using them directly, we may miss some words at edges of page, and even some words not at edge of pages, but included in a node/tag that is itself at edge of page or spanning previous or
next page.
The surest way to not miss any such edge cases is to not do what it does currently:
 - forward: find next page's top `y`, search in `y ⇒ y + pageHeight`
 - reverse: find prev page's bottom, seach in `y - pageHeight ⇒ y`

but to include current page and search in 3*pageHeight:
 - forward: search from current page's top : search in `y ⇒ y + 3*pageHeight`
 - reverse: search from current page's bottom: search in `y ⇒ y - 3*pageHeight`

These `3 x pageHeight` areas are:
  1) the current page that may have part of the occurence, or a node spanning next/previous page,
  2) the next/previous page where we may find our interesting occurences
  3) the page after/before that one, where some node shown on 2) may start in

This will return more results, including those on current page, but we can filter them in `readersearch.lua` (which we would have to do anyway even with current algorithm, as edge cases could give results on current page and get us blocked on this page, unable to search backwards).

It may be a little bit more expensive, but that's negligeable:
- if occurence in next page, instead of parsing 1 page, we'll parse 3.
- if occurence in page 20 after current, instead of parsing 20 page, we'll parse 22.

### CODE REVIEW

**Comment by poire-z** [comment]
There was one unit test that failed in one build (gcc no debug) but not the others (gcc debug, clang):
```
KOPTContext module should convert koptcontext to/from table
./spec/base/unit/koptcontext_spec.lua:180: Expected objects to be the same.
Passed in:
(string) ''
Expected:
(string) 'eng'
```
Strange (this PR code should have no impact). (Unless I poke into other libraries' data - which I think I don't - but just curious: do these unit tests each run in a single luajit process, or are there multiple launched for each test?)

**Comment by Frenzie** [comment]
Just a single one.

**Comment by poire-z** [comment]
Any comment on this?
I'd like to trigger a rebuild (would push a comment change commit) just to have unit tests run again, but I guess it will fail like this morning nightlys as http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/ is unavailable.

**Comment by Frenzie** [comment]
Since you have write access you should be able to restart the job directly from Travis. I triggered a rebuild yesterday but apparently it had a Travis illegal instruction fluke instead.

**Pull request merged**
