### PR TITLE
bump crengine: rendering, CSS and hyphenation tweaks

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- Fix sizing of float/inline-block image containers https://github.com/koreader/crengine/pull/467
- Fix body background drawing and other clipping issues
- Drawing: don't use `setHidePartialGlyphs()`
- CSS: ignore the `<body>` parent of `<DocFragment>`
- CSS colors: parse `rgb()/rgba()` and 4/8 digits hex values
- LVString: update/fix char props and `lStr_findWordBounds()` https://github.com/koreader/crengine/pull/468
- `UserHyphDict::getHyphenation()`: trim word with `lStr_findWordBounds()` https://github.com/koreader/crengine/pull/469

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1462)

### CODE REVIEW

**Comment by Frenzie** [comment]
I can't right now, but I guess someone should put in a PR over here.
https://github.com/Olivine-Labs/busted/blob/75b2c8930ed22d99dc5f6e41547ec333feee6197/busted-scm-2.rockspec#L4

For the moment can you check if it just works if you comment out this line?
https://github.com/koreader/koreader-base/blob/c9620454db9d88e44faa8f26d18df7d96797a240/.ci/emulator_install.sh#L11

**Comment by poire-z** [comment]
It fails later, with the same ubuntu errors I had in crengine:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-9/gcc-9-multilib_9.3.0-17ubuntu1~20.04_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by zwim** [comment]
Very good work :100:

**Comment by Frenzie** [comment]
@poire-z Why are we installing a custom gcc-9 here? Where's that coming from? If something's missing from the images, the images should be updated. (This is different from the GHA images because these are *our* images.)

**Comment by poire-z** [comment]
I have no idea, I've never put my nose in the CI/images stuff, and hardly ever followed when you guys were playing with this :/

**Comment by Frenzie** [comment]
I don't see that in the logs for your commit above. Where did it come from?

**Comment by poire-z** [comment]
I think I picked it from the Kobo build (from the CI for commit "comment out busted install":
https://github.com/koreader/koreader-base/runs/5575538728?check_suite_focus=true

**Pull request merged**
