### PR TITLE
minor: start SDL2 window at the center of screen

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by Frenzie** [comment]
Can't check atm, but what's the previous behavior?

**Comment by chrox** [comment]
Previously on GNOME 3 the SDL window will be placed at the last position where the window was closed. I don't know if centering the window on the screen each time koreader is launched is a good idea.

**Comment by Frenzie** [comment]
Opening at last location sounds better to me.

**Comment by houqp** [comment]
Ha, I see. My KDE4 has different behaviour, which it always start at the same location and covers the log in my terminal. It a little bit annoying that I have to manually move it away every time. I will close this PR for now.

**Pull request closed without merging**
