### PR TITLE
More djvulibre CMake tweaks...

### PR DESCRIPTION
**Pull request by NiLuJe**
Re #1409 

Let's see if this still builds...

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1410)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Probably more robust.

**Comment by NiLuJe** [comment]
And it makes for slightly less confusing output in case one of 'em implodes ;).

**Comment by Frenzie** [comment]
Definitely, yes.

**Comment by poire-z** [comment]
Random PR hijack.
Dunno if we're in any way impacted by this, so, just mentionning it:
https://news.slashdot.org/story/21/09/15/2034224/travis-ci-flaw-exposed-secrets-of-thousands-of-open-source-projects

**Comment by Frenzie** [comment]
We haven't had any Travis builds for weeks if not months, so definitely not that particular one. Besides that, I think I already deleted any remaining push tokens for Travis a few years ago.

**Pull request merged**
