### PR TITLE
[CI] Fix GitHub Action

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes https://github.com/koreader/koreader-base/pull/1462#issuecomment-1070807378.

Alternative to #1465. Maintenance-wise something has to give though.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1466)

### CODE REVIEW

**Comment by Frenzie** [comment]
This one's suffering from:

```
busted scm-2 depends on mediator_lua >= 1.1.1 (not installed)
Installing https://luarocks.org/mediator_lua-1.1.2-0.rockspec
mediator_lua 1.1.2-0 is now installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

Cloning into 'busted'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Error: Failed cloning git repository.
Error: Process completed with exit code 1.
```

I mentioned it upstream at `https://github.com/Olivine-Labs/busted/issues/668#issuecomment-1073215957` but working around it in the meantime might be prudent.

**Comment by Frenzie** [comment]
I have no idea why the same thing is still happening. It fixed the problem locally. >_>

**Comment by NiLuJe** [comment]
Could we point to a fork w/ the PR merged instead?

**Comment by Frenzie** [comment]
@NiLuJe Not sure what you mean? That's exactly what I did?

**Comment by Frenzie** [comment]
Like I said, doing exactly that fixes the problem… locally.

**Comment by NiLuJe** [comment]
I was slightly confused by the fact that the raw pointed to upstream directly ^^.

**Pull request closed without merging**
