### PR TITLE
Minor third-party bumps

### PR DESCRIPTION
**Pull request by NiLuJe**
* libjpeg-turbo 2.0.4
* LodePNG 20200120

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1032)

### CODE REVIEW

**Comment by Frenzie** [comment]
@NiLuJe I can't rerun you workflow (bit annoying, that) so let's see if closing and reopening does it…

**Comment by NiLuJe** [comment]
Once more, with feeling ;).

**Comment by NiLuJe** [comment]
Whee! \o/

(What's left is the usual Clang/MD5 mystery, and https://github.com/koreader/virdevenv/pull/46#issuecomment-570902518 ;)).

**Comment by Frenzie** [comment]
Like I wrote in https://github.com/koreader/virdevenv/issues/25#issuecomment-570903643 I don't think it looks very different from our regular base image, except that it has a bit less cruft in it. It'd be nice to know for sure though.

**Pull request merged**
