### PR TITLE
Bump HB to v6.0.0

### PR DESCRIPTION
**Pull request by NiLuJe**
HB [6.0.0](https://github.com/harfbuzz/harfbuzz/releases/tag/6.0.0)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1567)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Frenzie** [comment]
> A test variable font with ~7160 Hangul syllables derived from the NotoSerifKR-VF font has been built, with existing OpenType technology, as
well as with the new Variable Composites (VarComposites) technology. The VarComposites font is over 90% smaller than the OpenType version of the font!

**Comment by NiLuJe** [comment]
Yeah, the CJK stuff might be interesting ;).

Alas, Android toolchain strikes again ;).

**Comment by NiLuJe** [comment]
Archived in https://github.com/NiLuJe/koreader-base/tree/hb-6.0.0 for now.

**Comment by Frenzie** [comment]
A closed PR is also archived. ;-)

**Comment by NiLuJe** [comment]
That was mostly to stash it in a branch, because that was my master branch ;).

**Comment by NiLuJe** [comment]
And apparently we can't re-open a PR? o_O.

**Comment by NiLuJe** [comment]
Oh, that one wasn't from a branch, that's why ;o).

**Pull request closed without merging**
