### PR TITLE
Minor dropbear build tweaks

### PR DESCRIPTION
**Pull request by NiLuJe**
Hopefully without breaking anything ;).

(Ground-work for minor changes to the plugin to make it easier to test without risking clobbered system files).

### CODE REVIEW

**Comment by poire-z** [comment]
Dunno if it's related to this PR.
The clang build for my crengine bump failed this morning because ... 
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated
```
https://api.travis-ci.org/v3/job/407002046/log.txt
It needed only 50 more lines of log to reach a success :) 

This dropbear build succeeded thus, but its log is near 4MB too: https://api.travis-ci.org/v3/job/406649732/log.txt 

But in this dropbear build (and my bump's) log, there is like 20% of the log that are warnings related to the dropbear build:
```
clang-5.0: warning: argument unused during compilation: '-I .' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/zlib/build/x86_64-unknown-linux-gnu/zlib-prefix/src/zlib' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/zlib/build/x86_64-unknown-linux-gnu/zlib-prefix/src/zlib' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear/libtomcrypt/src/headers/' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I ./' [-Wunused-command-line-argument]
   * /usr/bin/ccache clang bn_mp_n_root_ex.o
clang-5.0: warning: argument unused during compilation: '-I src/headers/' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear/libtomcrypt/src/headers/' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I ../' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear/libtomcrypt/../' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I ../libtommath/' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear/libtomcrypt/../libtommath/' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/koreader/koreader-base/thirdparty/dropbear/build/x86_64-unknown-linux-gnu/dropbear-prefix/src/dropbear/libtomcrypt/src/headers/' [-Wunused-command-line-argument]
```

**Comment by NiLuJe** [comment]
Gah, there's another Travis limit beyond the "I'll stop showing you stuff on the web UI" one?

Grmbl.

I'll take care of it (ans fix those -I calls, because WTH? :D)

**Comment by NiLuJe** [comment]
Should be taken care of in #711 ;).

**Comment by Frenzie** [comment]
> Gah, there's another Travis limit beyond the "I'll stop showing you stuff on the web UI" one?

There's also "don't take more than the x minute timeout". What happened here exactly?

**Comment by NiLuJe** [comment]
Dropbear did not honor CFLAGS, (upstream issue, fixed, but not in any
release), and clang was being very very very very verbose with the default
warning set, because the lack of custom CFLAGS meant it didn't honor our
attempts at taming those ;).

**Comment by NiLuJe** [comment]
Which is how we learned that 4MB of logs meant an abort ;p.

**Comment by Frenzie** [comment]
Huh, I'd have expected something more like at least 10 ('cause it's a rounder number). Oh well. :-P

**Pull request merged**
