### PR TITLE
Add a kobov5 target

### PR DESCRIPTION
**Pull request by NiLuJe**
Now that the TCs are ready ;).

Also, minor third-party bumps.

(Rebase me)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1943)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Not really the place but potentially worth noting that there's a new https://github.com/fribidi/fribidi/releases/tag/v1.0.16 and https://github.com/harfbuzz/harfbuzz/releases/tag/10.0.1

(I'm too tired atm anyway)

**Comment by benoit-pierre** [comment]
Yep, I have PRs for those.

**Review by pazos — APPROVED** [review]
@NiLuJe: please merge when ready. If you bump base in front please also bump android-luajit-launcher

Thanks!

**Comment by NiLuJe** [comment]
That'll probably be tomorrow evening ;).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1943)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Pull request merged**
