### PR TITLE
thirdparty/luasec 0.9

### PR DESCRIPTION
**Pull request by Frenzie**
https://github.com/brunoos/luasec/compare/luasec-0.8.2...v0.9

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1005)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Any idea what went kablooey here?

**Comment by Frenzie** [comment]
Not really, it seemed to work locally but I haven't looked into it besides not merging due to the failure.

**Comment by NiLuJe** [comment]
Could it be related to the luarocks tweaks? (That vaguely seems to match, timing-wise).

**Comment by Frenzie** [comment]
You mean #1003? I don't think so but it's something to consider once I/someone looks into it. :+1:

**Comment by NiLuJe** [comment]
Yep. Is the CI happy after a rebase and a rebuild, for instance?

**Comment by Frenzie** [comment]
Only takes seconds to try, so let's give it a go.

**Comment by Frenzie** [comment]
Meh, I guess I'll have to run the build in a local Docker container to see what goes wrong. But once again, if I make the change locally (plus emptying out base/build) it works just fine if I run `kodev test base common_spec.lua`.

**Comment by Frenzie** [comment]
Alright, I finally had some time to look into this and I think it's most likely https://github.com/brunoos/luasec/commit/8ef33e33cfa92aa671afbd5517a4c1aee6631d4e (and possibly a couple of related commits). Fingers crossed.

**Comment by Frenzie** [comment]
Hm, guess I did something wrong there.

```
[----------] Running tests from ./spec/base/unit/common_spec.lua
common/ssl.lua:8: error loading module 'ssl.core' from file 'common/ssl.so':
	libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by NiLuJe** [comment]
Hmm, we *are* using openssl 1.1.1, not 1.1.0?

**Comment by Frenzie** [comment]
You're quite right of course.

So then wtf is going wrong here, lol

**Comment by Frenzie** [comment]
Okay, let's see… this is the 0.9 if I'm not mistaken:

```
$ readelf -d ssl.so

Dynamic section at offset 0xfe00 contains 26 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libssl.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x6000
 0x000000000000000d (FINI)               0xce14
 0x0000000000000019 (INIT_ARRAY)         0x10df0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x10df8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x260
 0x0000000000000005 (STRTAB)             0x1fa0
 0x0000000000000006 (SYMTAB)             0x530
 0x000000000000000a (STRSZ)              4489 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x11000
 0x0000000000000002 (PLTRELSZ)           6000 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x45b0
 0x0000000000000007 (RELA)               0x33e0
 0x0000000000000008 (RELASZ)             4560 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x3360
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x312a
 0x000000006ffffff9 (RELACOUNT)          185
 0x0000000000000000 (NULL)               0x0
```

**Comment by Frenzie** [comment]
Yeah, no real difference with the 0.8.2 version…

```
$ readelf -d ssl.so

Dynamic section at offset 0xfdf0 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libssl.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../libs]
 0x000000000000000c (INIT)               0x6000
 0x000000000000000d (FINI)               0xcca0
 0x0000000000000019 (INIT_ARRAY)         0x10de0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x10de8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x260
 0x0000000000000005 (STRTAB)             0x1f88
 0x0000000000000006 (SYMTAB)             0x530
 0x000000000000000a (STRSZ)              4488 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x11000
 0x0000000000000002 (PLTRELSZ)           5976 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x4478
 0x0000000000000007 (RELA)               0x33c8
 0x0000000000000008 (RELASZ)             4272 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x3348
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x3110
 0x000000006ffffff9 (RELACOUNT)          173
 0x0000000000000000 (NULL)               0x0
```

**Comment by Frenzie** [comment]
Except that `0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../libs]` seems to be missing… hmm, what's that.

**Comment by NiLuJe** [comment]
Oh, right, that makes sense ;).

And that LD override was... weird, yeah.

You'll *probably* still need the ORIGIN_CMAKE_TO_AUTOCFG crap, though? (c.f., PNG_LIB for instance).

You'll also need the matching ovzerride in the make call in our CMakeLists ;).

**Comment by Frenzie** [comment]
Anyway, it's caused by https://github.com/brunoos/luasec/commit/57f2f1363fd98112af056353860c2202acc61f33 so that change from LD to CCLD is sufficient to make it work just as it always has.

**Pull request merged**
