### PR TITLE
rework parallelisation handling

### PR DESCRIPTION
**Pull request by benoit-pierre**
- use both -j and -l to control/limit it
- honor those parameters in recursive calls to make & ninja

Note: with make '>=4.4' you can change the defaults with `make -j… -l…`, and use `make PARALLEL_JOBS=… PARALLEL_LOAD=…` on older versions.

Additionally, CMake based external projects will use `ninja` too (when enabled).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1762)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Any `MAKEFLAGS` in your environment?

**Comment by benoit-pierre** [comment]
A `-w` I expect.

**Comment by benoit-pierre** [comment]
Actually fixed in #1750, I think, but not attributed to the right commit which is why I missed, my bad. Try with this patch:
```diff
--- i/Makefile.defs
+++ w/Makefile.defs
@@ -92,7 +92,7 @@ ifneq ($(USE_NINJA),)
   CMAKE_MAKE_PROGRAM_FLAGS ?= $(NINJAFLAGS)
 else
   CMAKE_MAKE_PROGRAM := $(MAKE)
-  CMAKE_MAKE_PROGRAM_FLAGS ?= $(MAKEFLAGS)
+  CMAKE_MAKE_PROGRAM_FLAGS ?=
 endif
 
 CMAKE_FLAGS += -DMAKE=$(MAKE) -DNINJA=$(NINJA)
```

**Comment by poire-z** [comment]
> Any MAKEFLAGS in your environment?
> A -w I expect.

Nope, none of that that I could see.

> Try with this patch:

Yep, this makes it pass that!
But who knows what may happen in the next 40 minutes :)
I guess I need to wait for you to fix this before bumping base into frontend?

3 minutes later:
```
[ 12%] Performing build step for 'zlib'
make[5]: Entering directory '/space/kobo/koreader/base/thirdparty/zlib/build/x86_64-linux-gnu-debug/zlib-prefix/src/zlib'
/usr/bin/ld: error while loading shared libraries: libz.so.1: invalid ELF header
collect2: error: ld returned 127 exit status
make[5]: *** [Makefile:288: minigzip] Error 1
```
I'm gonna clean this build dir, unless you think it's unexpected and something that needs worrying ?

**Comment by poire-z** [comment]
It moves on after I just retried a build (without any cleaning).
Could it be that the parallelisation was building with one process, while the other process was trying to use stuff not yet build?
(In case it matters, my tiny-appartment-tuned fanless linux PC has 2 CPU core Intel(R) Celeron(R) CPU 847 @ 1.10GHz)

Oups, happened again:
```
[ 12%] Performing build step for 'zstd'
make[5]: Entering directory '/space/kobo/koreader/base/thirdparty/zstd/build/x86_64-linux-gnu-debug/zstd-prefix/src/zstd'
make[6]: Entering directory '/space/kobo/koreader/base/thirdparty/zstd/build/x86_64-linux-gnu-debug/zstd-prefix/src/zstd/lib'
CC obj/conf_d23dba049d58938689ab281864b97a66/static/debug.o
CC obj/conf_4b679653d87f80eceea6e21c84766c97/dynamic/error_private.o
CC obj/conf_d23dba049d58938689ab281864b97a66/static/pool.o
compiling multi-threaded dynamic library 1.5.5
CC obj/conf_d23dba049d58938689ab281864b97a66/static/zstd_common.o
/usr/lib/gcc/x86_64-linux-gnu/12/cc1: error while loading shared libraries: libzstd.so.1: file too short
as: error while loading shared libraries: libzstd.so.1: file too short
make[7]: *** [Makefile:211: obj/conf_d23dba049d58938689ab281864b97a66/static/zstd_common.o] Error 1
make[6]: *** [Makefile:107: libzstd.a] Error 2
make[6]: *** Waiting for unfinished jobs....
creating versioned links
```
Again, it moved on after a re-run.

**Comment by benoit-pierre** [comment]
Which version of make? There's a `.NOTPARALLEL` at the top of `Makefile.defs`, which should be supported since 3.79 (released Apr 2000). This normally prevent the build system from compiling multiple projects in parallel.

**Comment by benoit-pierre** [comment]
But I don't see how that would explain those errors: an issue with `libz.so.1` when compiling zlib, or with `libzstd.so.1` when compiling zstd… You not running out of disk space, are you?

**Comment by benoit-pierre** [comment]
I would `make clean` and retry. And install ccache and ninja. No sense in building with more handicaps. :P

**Comment by poire-z** [comment]
```
[ 25%] Performing install step for 'libzmq'
make[5]: Entering directory '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build'
Making install in src
make[6]: Entering directory '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/src'
make[7]: Entering directory '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/src'
 /usr/bin/mkdir -p '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/include'
 /usr/bin/mkdir -p '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/lib/pkgconfig'
 /usr/bin/install -c -m 644 ../include/zmq.h ../include/zmq_utils.h '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/include'
 /usr/bin/install -c -m 644 libzmq.pc '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/lib/pkgconfig'
/usr/bin/install: '../include/zmq.h' and '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/include/zmq.h' are the same file
/usr/bin/install: '../include/zmq_utils.h' and '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/include/zmq_utils.h' are the same file
make[7]: *** [Makefile:1425: install-includeHEADERS] Error 1
make[7]: *** Waiting for unfinished jobs....
make[7]: Leaving directory '/space/kobo/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu-debug/libzmq-prefix/src/libzmq-build/src'
make[6]: *** [Makefile:1545: install-am] Error 2
```
Moved on after I `rm base/thirdparty/libzmq/build/x86_64-linux-gnu-debug`.

Btw, my re-run keeps going through (quickly, but this usually disappear after I rm the build dir an re-run - this already happened in the past):
```
# Avoid precision loss on 32-bit arches (LFS is always built w/ LARGEFILE support, but lua_Integer is always a ptrdiff_t, which is not wide enough).
patch -d luafilesystem -t -N --no-backup-if-mismatch -r - -p1 < patches/lfs-pushnumber-for-wide-types.patch
patching file src/lfs.c
gcc -L/space/kobo/koreader/base/build/x86_64-linux-gnu-debug/libs -Og -g -pipe -fno-omit-frame-pointer   -march=native -fPIC -I/space/kobo/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-
debug/luajit-prefix/src/luajit/src -shared -Wl,-O1 -Wl,--as-needed -Wl,@/space/kobo/koreader/base/origin.ldflags  -o build/x86_64-linux-gnu-debug/libs/libkoreader-lfs.so luafilesystem/src/lfs.c
patch -d luafilesystem -t -R --no-backup-if-mismatch -r - -p1 < patches/lfs-pushnumber-for-wide-types.patch
patching file src/lfs.c
install -d thirdparty/openssl/build/x86_64-linux-gnu-debug
rm -f /space/kobo/koreader/base/thirdparty/openssl/build/x86_64-linux-gnu-debug/openssl-prefix/src/openssl/../openssl-stamp/openssl-build
cd thirdparty/openssl/build/x86_64-linux-gnu-debug && \
```

Same for:
```
 /usr/bin/install -c -m 644 libczmq.pc '/space/kobo/koreader/base/thirdparty/czmq/build/x86_64-linux-gnu-debug/czmq-prefix/src/czmq-build/lib/pkgconfig'
/usr/bin/install: '../include/czmq.h' and '/space/kobo/koreader/base/thirdparty/czmq/build/x86_64-linux-gnu-debug/czmq-prefix/src/czmq-build/include/czmq.h' are the same file
/usr/bin/install: '../include/czmq_prelude.h' and '/space/kobo/koreader/base/thirdparty/czmq/build/x86_64-linux-gnu-debug/czmq-prefix/src/czmq-build/include/czmq_prelude.h' are the same file
make[7]: *** [Makefile:879: install-includeHEADERS] Error 1
make[7]: *** Waiting for unfinished jobs....
make[7]: Leaving directory '/space/kobo/koreader/base/thirdparty/czmq/build/x86_64-linux-gnu-debug/czmq-prefix/src/czmq-build/src'
```

> Which version of make? 

From debian make 4.3-4.1
$ make -v
GNU Make 4.3
Built for x86_64-pc-linux-gnu

> You not running out of disk space, are you?

No, neither in my /space/ or /tmp/

> No sense in building with more handicaps. :P

I'm happy to masquerade as a third-world user and ensure that people with old hardware can build koreader. None of your CI fancy cloud services will ensure that ! :)

**Comment by benoit-pierre** [comment]
What version of cmake do you have?

**Comment by benoit-pierre** [comment]
> I'm happy to masquerade as a third-world user and ensure that people with old hardware can build koreader. None of your CI fancy cloud services will ensure that ! :)

Hey, I'm using a 10+ years old desktop, a number of build system changes are all about reducing / better utilizing resources.

**Comment by Frenzie** [comment]
@poire-z Toss the zmq and czmq build/x86_etc dirs.

@benoit-pierre I'm using a 10-year old PC too but they still sell brand new computers that are a lot worse. ;-P

**Comment by benoit-pierre** [comment]
Oh, damn, I edited you comment…

**Comment by benoit-pierre** [comment]
And I just made it worse. ;(

**Comment by benoit-pierre** [comment]
> @benoit-pierre I'm using a 10-year old PC too but they still sell brand new computers that are a lot worse. ;-P

True.

**Comment by Frenzie** [comment]
Live and learn. ;-)

**Comment by benoit-pierre** [comment]
Anyway, @poire-z, I'm wondering if you're maybe hitting [CMP0114](https://cmake.org/cmake/help/latest/policy/CMP0114.html#cmp0114).

**Comment by poire-z** [comment]
cmake from Debian 12 (but unpacked outside /usr/, from Nov 2022, not updated by debian since):
```
/space/kobo $ cmake --version
cmake version 3.25.1
```

**Comment by benoit-pierre** [comment]
So it's not that.

**Comment by poire-z** [comment]
> I guess I need to wait for you to fix this (the `CMAKE_MAKE_PROGRAM_FLAGS ?= $(MAKEFLAGS)` issue) before bumping base into frontend?

Should I wait or should I go ? :)

**Comment by benoit-pierre** [comment]
Building with cmake 3.15.0 and `make43 USE_NINJA=` works fine locally…

I'll PR the `CMAKE_MAKE_PROGRAM_FLAGS` fix.

**Pull request merged**
