### PR TITLE
RTC: Implement HCToSys

### PR DESCRIPTION
**Pull request by NiLuJe**
Needed for Kobo shenanigans on devices whose system clock goes wonky during suspend.

(Re #https://github.com/koreader/koreader/issues/7092)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1322)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Matches busybox's behavior, weird TZ & DST shenanigans included.

**Comment by NiLuJe** [comment]
And that's nickel, FWIW:

```
9070  20:13:51.079792 [2fb46b34] open("/dev/rtc0", O_RDONLY|O_NONBLOCK) = 27</dev/rtc0> <0.000095>
9070  20:13:51.080269 [2fda14ec] ioctl(27</dev/rtc0>, RTC_RD_TIME, {tm_sec=52, tm_min=13, tm_hour=19, tm_mday=7, tm_mon=2, tm_year=121, tm_wday=0, tm_yday=0, tm_isdst=0}) = 0 <0.002177>
9070  20:13:51.082939 [2fd6446c] settimeofday({tv_sec=1615144432, tv_usec=0}, {tz_minuteswest=0, tz_dsttime=0}) = 0 <0.000056>
```

**Review by Frenzie — APPROVED** [review]
I still think it's really weird, but oh well.

PS I only glanced and nothing looks off, let me know if you want me to actually look at it in detail.

**Comment by NiLuJe** [comment]
@Frenzie: Eh, nothing blew up, should be good ^^.

**Comment by NiLuJe** [comment]
If anything, maybe that I didn't mangle the error handling in `set_kernel_tz` ;).

**Pull request merged**
