### PR TITLE
Cache/MµPDF shenanigans, the base edition

### PR DESCRIPTION
**Pull request by NiLuJe**
Bits and bobs needed by https://github.com/koreader/koreader/pull/7624 related to https://github.com/koreader/koreader/issues/7627

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1365)

### CODE REVIEW

**Review by Frenzie — COMMENTED** [review]
The commit title me think you randomly included a fix for https://github.com/koreader/koreader/issues/7631

**Comment by NiLuJe** [comment]
Not that I know of, unless the tow are relate,d which I doubt, but koreader/koreader#7627, yeah ;).

**Comment by Frenzie** [comment]
Yeah, no, the commit titled `KOPTContext: Minor API tweak to getWordBoxes & co` isn't related at all but it just sounds like it. :-D

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Pull request merged**
