### PR TITLE
Utf8Proc: add a dumb lowercase method

### PR DESCRIPTION
**Pull request by zwim**
Do the lower casing of a string like crengine does.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1458)

### CODE REVIEW

**Comment by poire-z** [comment]
Feels a bit.. dumb to have to use/see in frontend `Utf8Proc.lowercase_dumb`.
May be you could wrap it here as a single function, which may do NFKC_Casefold by default (if that's what the frontend code needs most), and you would use in the rare places where you need the dumb variant:
`Utf8Proc.lowercase(word, false)`
(or `Utf8Proc.lowercase(word, true)`, but it sounds better to say `better=false` than `dumber=true` :)

```lua
function Utf8Proc.lowercase(str, normalize)
    if normalize == nil then normalize = true end
```

**Comment by poire-z** [comment]
You need this merged, with the crengine bumps, for your user hyph frontend PR ?

**Comment by zwim** [comment]
Yes, please.

**Comment by zwim** [comment]
Thank you.

**Pull request merged**
