### PR TITLE
sdl: use versioned library, cleanup `ffi/util` helpers

### PR DESCRIPTION
**Pull request by benoit-pierre**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1929)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(nit: typo in the commit msg if this is to be a rebase, ffi/input is gone, not ffi/util ;)).

**Review by NiLuJe — COMMENTED** [review]
A few questions, but good to go on principle ;).

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1929#-:-O7L_hBdBjLnraS_rIj_:b-qlkgtf)* status: all files reviewed, 2 unresolved discussions (waiting on @benoit-pierre)

___
*[`ffi/util.lua` line 685 at r1](https://reviewable.io/reviews/koreader/koreader-base/1929#-O7LZo8-A2wWnUNYY8TE:-O7LZo8-A2wWnUNYY8TF:b2q64qi) ([raw file](https://github.com/koreader/koreader-base/blob/62e0cecf589ae3fae11558c56fcaa8a13d84e0c7/ffi/util.lua#L685)):*
> ```Lua
>         libSDL2, err = util.ffiLoadCandidates(candidates)
>         if not libSDL2 then
>             print("SDL2 not loaded:", libSDL2)
> ```

Shouldn't this still be printing `err`? `libSDL2` is always `false` in this branch.
___
*[`ffi/util.lua` line 688 at r1](https://reviewable.io/reviews/koreader/koreader-base/1929#-O7L_2r6BpFlOMfv0Nyh:-O7L_2r6BpFlOMfv0Nyi:b-owmfvk) ([raw file](https://github.com/koreader/koreader-base/blob/62e0cecf589ae3fae11558c56fcaa8a13d84e0c7/ffi/util.lua#L688)):*
> ```Lua
>         end
>     end
>     return libSDL2 or nil
> ```

Would returning a `false` `libSDL2` (as opposed to `nil`) here be an issue for `ffi/SDL2_0.lua`?

Or, perhaps a better question would be: should `ffi/SDL2_0.lua` handle failure to load SDL2 in a specific way?

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1929)* status: all files reviewed, 1 unresolved discussion (waiting on @benoit-pierre)

**Comment by benoit-pierre** [comment]
> _[`ffi/util.lua` line 685 at r1](https://reviewable.io/reviews/koreader/koreader-base/1929#-O7LZo8-A2wWnUNYY8TE:-O7LZo8-A2wWnUNYY8TF:b2q64qi) ([raw file](https://github.com/koreader/koreader-base/blob/62e0cecf589ae3fae11558c56fcaa8a13d84e0c7/ffi/util.lua#L685)):_
> 
> > ```lua
> >         libSDL2, err = util.ffiLoadCandidates(candidates)
> >         if not libSDL2 then
> >             print("SDL2 not loaded:", libSDL2)
> > ```
> 
> Shouldn't this still be printing `err`? `libSDL2` is always `false` in this branch.

Yep.

> _[`ffi/util.lua` line 688 at r1](https://reviewable.io/reviews/koreader/koreader-base/1929#-O7L_2r6BpFlOMfv0Nyh:-O7L_2r6BpFlOMfv0Nyi:b-owmfvk) ([raw file](https://github.com/koreader/koreader-base/blob/62e0cecf589ae3fae11558c56fcaa8a13d84e0c7/ffi/util.lua#L688)):_
> 
> > ```lua
> >         end
> >     end
> >     return libSDL2 or nil
> > ```
> 
> Would returning a `false` `libSDL2` (as opposed to `nil`) here be an issue for `ffi/SDL2_0.lua`?
> 
> Or, perhaps a better question would be: should `ffi/SDL2_0.lua` handle failure to load SDL2 in a specific way?

No (it will fail in `frontend/device.lua` before that), but it's cleaner / more logical, no?

**Review by NiLuJe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1929)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @benoit-pierre)

**Pull request merged**
