### PR TITLE
framebuffer: Make sure scaleBySize honors a DPI override

### PR DESCRIPTION
**Pull request by NiLuJe**
Even if said override happens to match the native DPI, because the scaleBySize heuristic is weird and results would differ.

c.f., https://github.com/koreader/koreader/pull/6977#issuecomment-743276911

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1258)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
Ref https://github.com/koreader/koreader/pull/6977#issuecomment-743300572

So, we continue getting a different result whether auto 300 dpi vs. user-set 300 dpi ?
You're less puzzled than yesterday ? Or just don't want to introduce a change ?

**Comment by NiLuJe** [comment]
Getting consistent results would involve just *always* going the scale_size + scale_dpi way (with scale_dpi actually being scaleByDpi), which would change a lot of things, yeah.

At least this way it does what it probably intended to do without the weird corner-case of "except when override matches native".

**Comment by NiLuJe** [comment]
And this way, we can actually *see* what would happen if we went that way, by setting an override that matches our device's native DPI ;).

**Comment by NiLuJe** [comment]
It's definitely not a bad idea, and would probably not change much on legacy devices, because scale_size is 1 there, and scaleByDpi would be almost exactly 1, too (167 / 160).

**Comment by poire-z** [comment]
OK, so _not_ less puzzled :)

**Pull request merged**
