### PR TITLE
bump crengine: supports DocM, minor CSS fixes

### PR DESCRIPTION
**Pull request by poire-z**
Includes https://github.com/koreader/crengine/pull/523 : 
- DocX: add support for similar DocM format
- LVStyleSheet: fix LVCssDeclaration::getHash()
- CSS parsing: accept Unicode values for ID and classnames
- update for Harfbuzz 8, fix some compiler warning

(
For some reason I can't get, my git diff is showing:
```diff
+++ b/thirdparty/kpvcrlib/crengine
@@ -1 +1 @@
-Subproject commit db3bc426b6e8e3b88ca917287a9335617eb2ac6e
+Subproject commit 3b6f7f4bb03744b5a1f0855c582b44d2068bb9fb
```
The start commit https://github.com/koreader/crengine/commit/db3bc426b6e8e3b88ca917287a9335617eb2ac6e is not part of this crengine commit history.
It should have been https://github.com/koreader/crengine/commit/15ea43c4dd9a46fa9d705e3c75deee8626f0fde2.
I have no idea why it appeared.
Hopefully, this won't cause any issue, github seems to look happy with it...
)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1641)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
Still that ghost commit hash after merge... But things looks ok in spite of that.

**Comment by poire-z** [comment]
Stuff looks still odd in other ways:

image
When you click on the "6 changed files", you reach a page that says they are "8 changed files":
image

**Comment by benoit-pierre** [comment]
db3bc426 is my crengine PR, while master is db3bc426, so even locally your merge looks weird (last line):
```diff
commit a938d082ba3f39a9d5cc39492637ce8711b9dd3f
Author: poire-z <poire-z@users.noreply.github.com>
Date:   Sun Jul 16 10:46:09 2023 +0200

    bump crengine: supports DocM, minor CSS fixes (#1641)
    
    Includes:
    - DocX: add support for similar DocM format
    - LVStyleSheet: fix LVCssDeclaration::getHash()
    - CSS parsing: accept Unicode values for ID and classnames
    - update for Harfbuzz 8, fix some compiler warning
---
 thirdparty/kpvcrlib/crengine | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

Submodule thirdparty/kpvcrlib/crengine db3bc426...3b6f7f4b:
  > update for Harfbuzz 8, fix some compiler warning
  > CSS parsing: accept Unicode values for ID and classnames
  > LVStyleSheet: fix LVCssDeclaration::getHash()
  > DocX: add support for similar DocM format
  > lvstring: fix clang release build (#522)
  < lvstring: fix clang release build
```

**Comment by poire-z** [comment]
Do you foresee possible future problems with that ?
Or can I just go with it and forget about it ? :)
(The alternative is to reset on the master branch... and try to do it again properly.)

**Comment by benoit-pierre** [comment]
I don't know, but how did it happen? The crengine submodule was not up-to-date?

**Comment by poire-z** [comment]
Not sure. I did as I usually do (extract of my bash history):
```
git checkout master
git branch -D bump_lunasvg
git fetch --prune
git fetch upstream ; git merge upstream/master
git push origin master
git log
git branch
git checkout -b bump_crengine
git status
git submodule update thirdparty/kpvcrlib/crengine
git status
   here, it told me that nothing was new
grep update ../NOTES.txt
git submodule update --remote thirdparty/kpvcrlib/crengine
   and there, I saw the hash diff
git status
```

**Comment by NiLuJe** [comment]
I'd probably force-push it into shape, just for peace of mind ;).

**Comment by poire-z** [comment]
Might be a bit too late, all users or tools that had pulled it would stumble to resync with it.
But I guess that just the "new" hash matters to git/things that apply commits in order, so let's not bother.

**Pull request merged**
