### PR TITLE
A round of 3rd-party updates

### PR DESCRIPTION
**Pull request by NiLuJe**
A whole bunch of them, but nothing groundbreaking...

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1580)

### CODE REVIEW

**Comment by Frenzie** [comment]
Pssht https://github.com/koreader/koreader-base/blob/a5e198ec5ac6f7b0cee11b82909394064bb7fcad/thirdparty/freetype2/CMakeLists.txt#L32

https://gitlab.freedesktop.org/freetype/freetype/-/tags/VER-2-13-0

**Comment by NiLuJe** [comment]
Huh, hasn't hit portage yet ;).

**Comment by Frenzie** [comment]
Btw, were we avoiding Harfbuzz 6 and now 7?

https://github.com/harfbuzz/harfbuzz/releases/tag/7.0.0

**Comment by NiLuJe** [comment]
6 didn't build on Android (https://github.com/koreader/koreader-base/pull/1567)

**Comment by Frenzie** [comment]
Oh right, I forgot.

**Pull request merged**
