### PR TITLE
blitbuffer: Always enable JIT workaround

### PR DESCRIPTION
**Pull request by ezdiy**
This is necessary even with CBB on, for Lua fallbacks.

(maybe) fixes https://github.com/koreader/koreader/issues/6736

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1205)

### CODE REVIEW

**Comment by ezdiy** [comment]
(to be merged if @zwim confirms)

**Comment by zwim** [comment]
LGTM.
Screenshot takes 3 seconds now and the whole KOReader UI is snappier.

**Comment by ezdiy** [comment]
Welp, let's see what else catches fire from this.

**Comment by poire-z** [comment]
@ezdiy : you still have to work on your merging skills :) (same glitch as last time ? or you used the wrong merge button, the one other than squash or rebase ?)
```
Merge: fc79465 a7437c6
Author: ezdiy <ezdiy@outlook.com>
Date:   Sun Oct 4 11:31:55 2020 +0200
    blitbuffer: Always enable JIT workaround (#1205)
    This is necessary even with CBB on, for Lua fallbacks.
    fixes https://github.com/koreader/koreader/issues/6736

commit a7437c689f2a15bca8950aaf81674afa510e7a37
Author: Ez Diy <ezdiy@outlook.com>
Date:   Sun Oct 4 00:55:15 2020 +0200
    blitbuffer: Always nable JIT workaround
    This is necessary even with BB on, for Lua fallbacks.
```

**Comment by ezdiy** [comment]
@poire-z seems like wrong button this time

**Pull request merged**
