### PR TITLE
More PB fb shenanigans!

### PR DESCRIPTION
**Pull request by NiLuJe**
Mandatory status dump for everyone, so we get useful crash.logs straight away ;).

Plus a tentative fix for https://github.com/koreader/koreader/issues/4447
But I'd *really* like to get logs, because depending on those, I might be able to simply do away with the whole ugly side of the branch ;).

### CODE REVIEW

**Comment by NiLuJe** [comment]
Just wanted to confirm that we don't have a prettier way than io.write to handle logging this early?

**Comment by Frenzie** [comment]
Nothing other than calling the same thing in different ways (e.g., `io.stdout:write()`) and `print()`.

Also keep in mind io.write doesn't flush.

**Comment by NiLuJe** [comment]
Eh, good enough for me, thanks!

**Comment by Frenzie** [comment]
Close? No no, it just forces the buffered output to be written. Bad for performance, good for actually catching it in a log file in case of a crash. ;-)

**Comment by NiLuJe** [comment]
I'll remember that for the next round of PB fun times ;).

**Pull request merged**
