### PR TITLE
Move natural sorting algorithm to ffi/util

### PR DESCRIPTION
**Pull request by NiLuJe**
And implemented the hardened variant by Egor Skriptunoff

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1572)

### CODE REVIEW

**Comment by NiLuJe** [comment]
RFC: This implementation fixes minor inconsistencies (quoting Kulchenko's example):

> when a number in one string is in a position where a number is absent in some other string. For example: when sorting `{"dir\\file.lua", "dir2\\file.lua", "dir3\\file.lua", "dir3\\file2.lua"}` using the algorithm above, you'd get `{"dir2\\file.lua", "dir3\\file.lua", "dir3\\file2.lua", "dir\\file.lua"}`, which is probably not what you'd expect.

> If you sort the same table using this function, you'll get the sorted table you'd likely expect: `{"dir\\file.lua", "dir2\\file.lua", "dir3\\file.lua", "dir3\\file2.lua"}`.

The drawback being that it is roughly twice as expensive. Now, I don't actually use this myself in the FM, but when trying it on a H2O, the delay is noticeable.
Should we care?
Should we keep both imps and use the faster one in the FM?

**Comment by poire-z** [comment]
Any reason for this to be in ffi/util.lua if it relies on nothing C/ffi ? Could be in frontend/util.lua, no ? Or is it used in base/ ?

**Comment by NiLuJe** [comment]
I waffled a bit on that one; the `strcoll` stuff is in base, but it makes sense, because it's actually C (... sometimes ;p).

So, absolutely no objection about moving this to front if you guys prefer it that way ;).

**Comment by poire-z** [comment]
> the strcoll stuff is in base

What uses that strcoll stuff? And shouldn't that "what" then use this new natsort stuff?

**Comment by NiLuJe** [comment]
> What uses that strcoll stuff? And shouldn't that "what" then use this new natsort stuff?

The FM (via FileChooser, which is where the sorting method selection is implemented).

And ReaderDictionary, for... something :D

**Comment by poire-z** [comment]
> And ReaderDictionary, for... something :D

I guess for the initial sorting of dictionary names (a metadata string in the .ifo).

No idea how strcol does different from your natural sorting, so I too can't answer what you didn't answer :):

> And shouldn't that "what" then use this new natsort stuff?

**Comment by NiLuJe** [comment]
> And shouldn't that "what" then use this new natsort stuff?

Well, it already does?

**Comment by poire-z** [comment]
> Well, it already does?

Uh, but it doesn't if it uses strcol ? :)

But strcol is different than natural sorting (which just deal with numbers), as it's about the locale:
https://www.man7.org/linux/man-pages/man3/strcoll.3.html
```
       The comparison is based on strings interpreted
       as appropriate for the program's current locale for category
       LC_COLLATE.  
```

So, probably not replaceable by your naturalsort stuff.

**Comment by poire-z** [comment]
> The reasoning was that it miiiight be used in base, theoretically, but, yeaaaah ;p.
So, absolutely no objection about moving this to front if you guys prefer it that way ;).

But yes, if it does not need any C/ffi, and is somehow unrelated in purpose to strcol, and we may only need natural-sorting stuff for UI display, better in frontend/util.lua.

**Comment by NiLuJe** [comment]
Everything's now in front @ https://github.com/koreader/koreader/pull/10023 ;).

**Pull request closed without merging**
