### PR TITLE
luajit: add android luajit-launcher patch

### PR DESCRIPTION
**Pull request by benoit-pierre**
Cf. https://github.com/koreader/koreader/pull/12285.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1899)

### CODE REVIEW

**Comment by Frenzie** [comment]
I'm not entirely sure if that patch is still relevant btw. It could be it was mainly a 2.3 problem. But it's hard to test; I couldn't reproduce it myself even on 2.3.

**Comment by Frenzie** [comment]
Also see this somewhat related discussion: https://github.com/koreader/koreader/issues/4137#issuecomment-410677398

**Comment by NiLuJe** [comment]
Oh, it very much still relevant, the virtual address space mapping layout hasn't changed on Android AFAIK ;).

**Comment by NiLuJe** [comment]
Speaking of, this doesn't include the debug patch, which is really helpful in double-checking that it's behaving as expected ;).

**Review by NiLuJe — APPROVED** [review]

**Pull request merged**
