### PR TITLE
Bump LuaJIT

### PR DESCRIPTION
**Pull request by NiLuJe**
Fixes a nasty issue, possibly related to the recent CI weirdness.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1216)

### CODE REVIEW

**Comment by NiLuJe** [comment]
re: https://github.com/koreader/koreader/issues/6787

**Comment by pazos** [comment]
same on android?

**Review by Frenzie — APPROVED** [review]
Could you link to the specific commit too for phone ease? ;-)

**Comment by NiLuJe** [comment]
@Frenzie: https://github.com/LuaJIT/LuaJIT/compare/e9af1abec542e6f9851ff2368e7f196b6382a44c...1d8b747c161db457e032a023ebbff511f5de5ec2

@pazos: I'm not sure we're quite in sync on Android, but, yeah, probably ought to sync to the same commit ;).

**Pull request merged**
