### PR TITLE
sdl & sdcv: use CMake's external project support

### PR DESCRIPTION
**Pull request by benoit-pierre**
Prefer `ExternalProject` over `DownloadProject`.

Rational:
- using `DownloadProject` only work if a project dependencies are available at CMake's configure stage
- it also prevents parallelizing some steps (download, patch, configure)
- and finally, I want to PR a fix for the regression introduced in #1690 (only compile gettext & libiconv on Android and macOS), and this PR will reduce the amount of conflicts I have to deal with

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1753)

### CODE REVIEW

**Comment by Frenzie** [comment]
It's not relevant anymore, but DownloadProject was integrated in CMake as FetchContent since… I think it was 3.11.

Regarding gettext and libiconv whatever you prefer.

**Comment by Frenzie** [comment]
I don't see anything in here that looks suspicious, but after this was merged these errors started showing up:

```
./sdcv: /lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./sdcv)
```

Perhaps you have an idea as to what might've been overlooked?

**Comment by Frenzie** [comment]
It's all platforms, not just Android. Which is to say the problem is presumably located in the CMake daisy-chaining, only nothing springs out to me as suspicious.

As to your question, http://build.koreader.rocks/download/nightly/ or https://gitlab.com/koreader/nightly-builds/-/jobs

**Comment by Frenzie** [comment]
My bad, the OP there (the details of which I had forgotten over the past few days :blush:) might be unrelated to the discussion following https://github.com/koreader/koreader/issues/11604#issuecomment-2029613677

In fact Android 14 should be decidedly unaffected for obvious reasons.

**Comment by poire-z** [comment]
Just bumped base (to its current master) and try a rebuild, and failed on sdcv:
```
[ 87%] Building CXX object CMakeFiles/sdcv.dir/src/distance.cpp.o
[100%] Linking CXX executable sdcv
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-gconvert.o): in function `try_conversion':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/gconvert.c:175: undefined reference to `libiconv_open'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-gconvert.o): in function `g_iconv':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/gconvert.c:285: undefined reference to `libiconv'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-gconvert.o): in function `g_iconv_close':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/gconvert.c:308: undefined reference to `libiconv_close'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-ggettext.o): in function `ensure_gettext_initialized':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/ggettext.c:107: undefined reference to `libintl_bindtextdomain'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/ggettext.c:110: undefined reference to `libintl_bind_textdomain_codeset'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-ggettext.o): in function `_g_dgettext_should_translate':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/ggettext.c:315: undefined reference to `libintl_textdomain'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/ggettext.c:316: undefined reference to `libintl_gettext'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-ggettext.o): in function `g_dgettext':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/ggettext.c:402: undefined reference to `libintl_dgettext'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-ggettext.o): in function `g_dcgettext':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/ggettext.c:429: undefined reference to `libintl_dcgettext'
/usr/bin/ld: base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/lib/libglib-2.0.a(libglib_2_0_la-ggettext.o): in function `g_dngettext':
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/ggettext.c:460: undefined reference to `libintl_dngettext'
collect2: error: ld returned 1 exit status
make[7]: *** [CMakeFiles/sdcv.dir/build.make:195: sdcv] Error 1
make[7]: Leaving directory 'base/thirdparty/sdcv/build/x86_64-linux-gnu-debug/sdcv-prefix/src/sdcv-build'
make[6]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sdcv.dir/all] Error 2
```

Trashing thirdparty/glib/build/ to rebuild it too fails with:
```
  CC       libglib_2_0_la-gdataset.lo
base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/gconvert.c:59:2: error: #error GNU libiconv not in use but included iconv.h is from libiconv
   59 | #error GNU libiconv not in use but included iconv.h is from libiconv
      |  ^~~~~
```

Any hint about what I can do (some toolchain bits to update?) to move on?

**Comment by benoit-pierre** [comment]
Did you rebuild from scratch?

**Comment by poire-z** [comment]
No, I usually don't need to, or when stuff fails, I can just rm the build/ subdirs and the libs in libs/.
What else can I `rm` safely ? (I don't want to clean it all up and lose my crengine past dev branches).

**Comment by benoit-pierre** [comment]
> (I don't want to clean it all up and lose my crengine past dev branches).

I don't understand what you mean by that.

**Comment by benoit-pierre** [comment]
Just to be clear: "from scratch" mean after a make clean. Not re-cloning a fresh checkout.

**Comment by poire-z** [comment]
Yes, I did mean rm -rf base and recloning everything (that I stupidely did once, so me being now cold about cleaning stuff :)
```
/space/kobo/koreader/base $ make clean
************ CMAKE_MAKE_PROGRAM: "make" **********
************ Building for MACHINE: "x86_64-linux-gnu" **********
************ PATH: "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games" **********
************ CHOST: "" **********
rm -rf build/x86_64-linux-gnu/*
rm -rf thirdparty/{kpvcrlib,nanosvg,zstd,luajit,lpeg,turbo,czmq,libzmq,libk2pdfopt,tesseract,leptonica,lj-wpaclient,lua-htmlparser,lua-rapidjson,lua-Spore,luasec,luasocket,glib,lodepng,minizip,djvulibre,mupdf,freetype2,harfbuzz,giflib,libpng,zlib,libwebp,lunasvg,tar,sdcv,libiconv,gettext,libjpeg-turbo,popen-noshell,sqlite,openssl,dropbear,openssh,curl,zsync2,fbink,kobo-usbms,fribidi,libunibreak,utf8proc}/build/x86_64-linux-gnu
/space/kobo/koreader/base $ cd ..

/space/kobo/koreader $ ../emu_build_koreader.sh
(this just sets some env build stuff, and call kodev build)

(it goes immediately to build glib)

[ 12%] Performing build step for 'glib'
make[5]: Entering directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib'
make[6]: Entering directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib'
Making all in libcharset
make[7]: Entering directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib/libcharset'
make[7]: Leaving directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib/libcharset'
Making all in pcre
make[7]: Entering directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib/pcre'
make[7]: Leaving directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib/pcre'
Making all in update-pcre
make[7]: Entering directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib/update-pcre'
make[7]: Leaving directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib/update-pcre'
Making all in .
make[7]: Entering directory '/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib-build/glib'
  CC       deprecated/libglib_2_0_la-gallocator.lo
  CC       deprecated/libglib_2_0_la-gcache.lo
  CC       deprecated/libglib_2_0_la-gcompletion.lo
  CC       deprecated/libglib_2_0_la-grel.lo
  CC       deprecated/libglib_2_0_la-gthread-deprecated.lo
  CC       libglib_2_0_la-gconvert.lo
/space/kobo/koreader/base/thirdparty/glib/build/x86_64-linux-gnu-debug/glib-prefix/src/glib/glib/gconvert.c:59:2: error: #error GNU libiconv not in use but included iconv.h is from libiconv
   59 | #error GNU libiconv not in use but included iconv.h is from libiconv
      |  ^~~~~
  CC       libglib_2_0_la-gdate.lo
make[7]: *** [Makefile:1884: libglib_2_0_la-gconvert.lo] Error 1
```

**Comment by poire-z** [comment]
Ok, took and bit more time to rm with `KODEBUG=1 make clean` :)
Now rebuilding the world (which takes > 1 hour on my old little pc).

**Comment by benoit-pierre** [comment]
1 hour! Do you use ccache?

Also, where does your `iconv.h` come from? And which distribution are you using?

**Comment by benoit-pierre** [comment]
I assume something like `/usr/include/iconv.h` is used, since you're building the emulator, but which package installed it?

**Comment by poire-z** [comment]
```
$ locate iconv.h
/usr/include/iconv.h   comes from debian 12's libc6-dev 2.36-9+deb12u4
/space/kobo/gnu_arm-linux-gnueabihf/i386/usr/include/iconv.h
/space/kobo/gnu_arm-linux-gnueabihf/usr/arm-linux-gnueabihf/include/iconv.h
```
(The stuff in `/space/kobo/gnu_arm-linux-gnueabihf/` are some .deb from Debian 10 that I unpacked there, and I'm still using these old stuff without issues. Trying to use those from debian 11 caused some issues, some stories at https://github.com/koreader/koreader/issues/3972#issuecomment-918119409 .)

**Comment by poire-z** [comment]
> 1 hour! Do you use ccache?

No, I don't really need to inverstigate that, I don't rebuild the world as often as you do, I can bear 1 hour every other month - and I guess it probably won't speed up my crengine rebuild, which takes 3mn everytime I touch a popular .h :/))

**Comment by benoit-pierre** [comment]
So you're not using the koxtoolchain?

**Comment by poire-z** [comment]
> So you're not using the koxtoolchain?

Nope.
(I guess I'll eventually have to switch to it when you'll shuffle more stuff to use meson and other fancy stuff...)

Ok, my build, after a proper make clean, finished well without the errors I mentionned above.
All is well, sorry for the noise.

**Comment by benoit-pierre** [comment]
So I guess from a previous build without #1754 you had an `iconv.h` header still layout around. That PR could explain the speedup too.

And 3mn to compile crengine, that's slooowwwww. You really should give ccache a try, I don't know which header your modifying, but you still should see some cache hits.

**Comment by Frenzie** [comment]
I had the same problem (of sorts) but I slightly more strategically cleaned out a couple of build folders. I think mainly glib and libiconv.

**Comment by poire-z** [comment]
Just reporting that I was able to rebuild with zero issue with the latest master !

> Now rebuilding the world (which takes > 1 hour on my old little pc).

It now builds in 35mn :) probably thanks to a better handling of -j2.
It was actually very satisfying watching the output steps and the little %, guessing the dependancies and the new ordering of steps !

Btw, when re kodev build, after the 10 seconds needed to check what stuff is needed, it always outputs:
```
[  0%] Performing build step for 'crengine'
make[5]: warning: -j2 forced in submake: resetting jobserver mode.
[  0%] Performing install step for 'crengine'
[  1%] Completed 'crengine'
[  1%] Completed build dependencies for 'koreader'
[  2%] Performing build step for 'koreader'
make[5]: warning: -j2 forced in submake: resetting jobserver mode.
[  2%] Performing install step for 'koreader'
[  2%] Completed 'koreader'
```
only mentionning crengine, and no other library.
Could this be because I have archived stuff causing:?
`        modified:   thirdparty/kpvcrlib/crengine (untracked content)`

Also, I had a trick when working on crengine to avoid the 10s needed to check if other stuff has changed:
```sh
cd koreader
export KODEBUG=1
DEBUG_NO_DEFAULT=1
MYMAKEFILE=Makefile.cre.emu
cp Makefile $MYMAKEFILE
cat >> $MYMAKEFILE << 'EOT'
mycrengine:
        $(MAKE) -C $(KOR_BASE) $(OUTPUT_DIR)/libs/libkoreader-cre.so

EOT
make -f $MYMAKEFILE mycrengine
rm $MYMAKEFILE
```
which doesn't work anymore.
I think you mentionned somewhere there are now ways to explicitely rebuild only some parts, is that the case? What new trick can I use ?
(and if none, before I investigate, any idea how to make my above trick work again?)

**Comment by benoit-pierre** [comment]
> Just reporting that I was able to rebuild with zero issue with the latest master !
> 
> > Now rebuilding the world (which takes > 1 hour on my old little pc).
> 
> It now builds in 35mn :) probably thanks to a better handling of -j2.

Nice! \o/

> Btw, when re kodev build, after the 10 seconds needed to check what stuff is needed, it always outputs:
> 
> ```
> [  0%] Performing build step for 'crengine'
> make[5]: warning: -j2 forced in submake: resetting jobserver mode.
> [  0%] Performing install step for 'crengine'
> [  1%] Completed 'crengine'
> [  1%] Completed build dependencies for 'koreader'
> [  2%] Performing build step for 'koreader'
> make[5]: warning: -j2 forced in submake: resetting jobserver mode.
> [  2%] Performing install step for 'koreader'
> [  2%] Completed 'koreader'
> ```
> 
> only mentionning crengine, and no other library. Could this be because I have archived stuff causing:? ` modified: thirdparty/kpvcrlib/crengine (untracked content)`

No, that's normal: since the crengine and koreader external projects don't have an install step (it's a no-op), they are set up to "build always", rather than use the dependency file trick other external projects rely on for triggering a build step on source change.

> Also, I had a trick when working on crengine to avoid the 10s needed to check if other stuff has changed:
> 
> ```shell
> cd koreader
> export KODEBUG=1
> DEBUG_NO_DEFAULT=1
> MYMAKEFILE=Makefile.cre.emu
> cp Makefile $MYMAKEFILE
> cat >> $MYMAKEFILE << 'EOT'
> mycrengine:
>         $(MAKE) -C $(KOR_BASE) $(OUTPUT_DIR)/libs/libkoreader-cre.so
> 
> EOT
> make -f $MYMAKEFILE mycrengine
> rm $MYMAKEFILE
> ```
> 
> which doesn't work anymore. I think you mentionned somewhere there are now ways to explicitely rebuild only some parts, is that the case? What new trick can I use ? (and if none, before I investigate, any idea how to make my above trick work again?)

Using `make koreader-cre` will ask for everything up-to and included `libkoreader-cre.so`, so try that.

Locally, it speeds up a no-change build by ~38%:
```shell
▹ time make USE_MAKE=1
[…]
make USE_MAKE=1  3.03s user 1.87s system 471% cpu 1.041 total
▹ time make USE_MAKE=1 koreader-cre
[…]
make USE_MAKE=1 koreader-cre  1.25s user 0.64s system 283% cpu 0.668 total
```
But you should really give ninja a go, as it's where it shines (in terms of performance):
```shell
▹ time make
[…]
make  0.14s user 0.07s system 100% cpu 0.205 total
▹ time make koreader-cre
[…]
make koreader-cre  0.08s user 0.07s system 100% cpu 0.149 total
```

**Comment by poire-z** [comment]
> Using make koreader-cre will ask for everything up-to and included libkoreader-cre.so, so try that.

Thanks, went from 8s to 4s when no source change, good enough for me :)

Installed it, and:
```
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
make[1]: *** [Makefile:50: build/x86_64-linux-gnu-debug/cmake/build.ninja] Error 1
```
Don't want to waste 35mn (or would it really not rebuild the whole thing?), so I'll wait for your next big build system update to see how it does :)

**Comment by benoit-pierre** [comment]
NOTE: you can get a list of supported cmake targets using `make help`.

**Pull request merged**
