### PR TITLE
macos: fix wrap-mupdf library extension

### PR DESCRIPTION
**Pull request by benoit-pierre**
Cf. https://github.com/koreader/koreader/issues/12546#issuecomment-2391710914.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1948)

### CODE REVIEW

**Comment by Frenzie** [comment]
Thanks!

**Comment by Frenzie** [comment]
Did you also see the others in https://github.com/koreader/koreader/issues/12546#issuecomment-2391718387 ?

**Comment by benoit-pierre** [comment]
Yes, but those are Lua modules, so they get a `.so` extension.

**Comment by Frenzie** [comment]
They do? Hm, ok.

**Comment by benoit-pierre** [comment]
Yeah, apart from Windows, LuaJIT default package path uses `?.so`.

**Pull request merged**
