### PR TITLE
Add a truly awful hack to make scp work with our dropbear build...

### PR DESCRIPTION
**Pull request by NiLuJe**
... provided we're installed on the default "modern" location,
(i.e., /mnt/onboard/.adds/koreader).

And look for sftp-server there, too, even if we don't bundle one.

Re [KO#4014](https://github.com/koreader/koreader/issues/4104)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Can't do anything better than that, it's the shell that handles the actual command, so it's either an absolute path, or something in $PATH.

Don't do this at home, kids, that's the stupidest dirty patch I've ever done.

**Comment by NiLuJe** [comment]
Switch to a non multicall dropbear build to save a few KBs, since we don't rightly care about the standalone keygen.

**Comment by Frenzie** [comment]
Huh, interesting idea about sftp.

**Comment by Frenzie** [comment]
@NiLuJe I'm getting all kinds of builds failures. But since the nightlies on Gitlab succeeded I guess I'll just do a grand cleanup sometime later and try again. (Not sure I want to heat up the CPU and the room atm…)

**Comment by NiLuJe** [comment]
What kind? I don't think this should affect incremental builds, but you never know ;)

**Comment by NiLuJe** [comment]
The tail end on #713 might, though ;)

**Comment by Frenzie** [comment]
Errors like this:

screenshot_2018-07-28_06-45-50

Also stuff on Leptonica, not sure about LodePNG. I'll try a targeted deletion of those specific thirdparty libs to see if it helps.

**Comment by Frenzie** [comment]
At this time of day at least my CPU is at 55° under load instead of while idling.

screenshot_2018-07-28_06-53-29

Targeted deletion of those from #713 plus djvulibre, dropbear, leptonica, and k2pdfopt made it compile successfully. Better than everything. ;-)

**Comment by NiLuJe** [comment]
Yep, that was probably the LDFLAGS bits from #713 ;).

**Comment by NiLuJe** [comment]
Do you happen to usually have CFLAGS/LDFLAGS set in your env, by chance?

**Comment by Frenzie** [comment]
Nope. :-)

Btw, current idle temp on my CPU is a whopping 41°! D-:

(It might sound lowish if you're thinking stock, but thanks to my bequiet Shadow Rock Slim it's usually around 31/32ish.)

**Comment by Frenzie** [comment]
The Benelux is the hottest part of Europe: https://m.nieuwsblad.be/cnt/dmf20180726_03632882//

**Comment by NiLuJe** [comment]
Ouch.

**Comment by Frenzie** [comment]
Also yesterday around 14:30 the A/C broke down at work. :-P

**Pull request merged**
