### PR TITLE
optimize gettext / glib builds

### PR DESCRIPTION
**Pull request by benoit-pierre**
- compile only the part of gettext we need
- compile only a static version of `libglib-2.0`, since that's all sdcv needs

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1690)

### CODE REVIEW

**Comment by Frenzie** [comment]
As an aside and I don't know if it matters, but it's the glib becoming a bit old?

**Comment by benoit-pierre** [comment]
It's not too fresh, yeah.

**Comment by NiLuJe** [comment]
Yeah, newer builds switched to meson and I didn't have the will to deal with it for a platform idgaf about ;).

**Comment by Frenzie** [comment]
@benoit-pierre What does the draft status currently indicate? ^_^

**Comment by benoit-pierre** [comment]
I was just waiting for #1689 to be merged.

**Pull request merged**
