### PR TITLE
fix kodev release builds

### PR DESCRIPTION
**Pull request by benoit-pierre**
Update `CMakeLists.txt` tests for `KODEBUG` to match the makefiles: check for a non-empty `KODEBUG`, not for definition (`kodev` export an empty `KODEBUG` on release builds).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1677)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Didn't @NiLuJe say he already had this included somewhere coming soon or am I mixing things up? So not merging immediately just yet.

**Comment by NiLuJe** [comment]
> Didn't @NiLuJe say he already had this included somewhere coming soon or am I mixing things up? So not merging immediately just yet.

Doesn't ring a bell ;D.

----

I'm likely the one that broke this, though, as I often didn't go through kodev when working on this stuff ;).

**Comment by NiLuJe** [comment]
And because this prompted me to double-check: `Makefile.defs` use of `ifdef KODEBUG` is safe, because that one assumes empty is falsy.

**Review by NiLuJe — APPROVED** [review]

**Comment by benoit-pierre** [comment]
Yep, add to double check that too.

**Comment by Frenzie** [comment]
Closing in favor of https://github.com/koreader/koreader-base/pull/1679.

**Pull request closed without merging**
