### PR TITLE
Update to HarfBuzz 8.2.1

### PR DESCRIPTION
**Pull request by NiLuJe**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1657)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
:-D

**Comment by Frenzie** [comment]
And another one. :laughing: 
https://github.com/harfbuzz/harfbuzz/releases/tag/8.2.2
https://github.com/harfbuzz/harfbuzz/compare/8.2.1...8.2.2

**Comment by NiLuJe** [comment]
It's already in ;).

https://github.com/koreader/koreader-base/pull/1670

**Comment by Frenzie** [comment]
Ah lol you can tell I had to do a few very early very long days in Brussels. ;-)

**Comment by NiLuJe** [comment]
Let's chalk than one to a bad case of the Mondays ;).

**Pull request merged**
