### PR TITLE
bump crengine

### PR DESCRIPTION
**Pull request by frankyifei**

### CODE REVIEW

**Comment by frankyifei** [comment]
what's wrong with this 
`The command "wget https://tesseract-ocr.googlecode.com/files/tesseract-ocr-3.02.eng.tar.gz" failed 3 times.`

**Comment by Markismus** [comment]
There has to be a simpler alternative than this: `wget http://downloads.sourceforge.net/project/tesseract-ocr-alt/tesseract-ocr-3.02.eng.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Ftesseract-ocr-alt%2Ffiles%2F%3Fsource%3Dnavbar`

**Comment by Markismus** [comment]
Yep: wget https://github.com/tesseract-ocr/tesseract/archive/3.02.02.tar.gz

BTW is there a reason we don't update to 3.04? wget https://github.com/tesseract-ocr/tesseract/archive/3.04.01dev.tar.gz

**Comment by houqp** [comment]
The traineddata repo has been moved to https://github.com/tesseract-ocr/tessdata. We will need to grab all eng.* files. At the mean time, @frankyifei could you try using the following link in `.ci/test_script.sh`?

http://pkgs.fedoraproject.org/repo/pkgs/tesseract/tesseract-ocr-3.02.eng.tar.gz/3562250fe6f4e76229a329166b8ae853/tesseract-ocr-3.02.eng.tar.gz

**Pull request closed without merging**
