### PR TITLE
Build sdcv for Android

### PR DESCRIPTION
**Pull request by chrox**
by static linking of libz, libglib-2.0, libiconv and libintl

### CODE REVIEW

**Comment by hwhw** [comment]
Sorry, I merged a bit too fast: do you know why travis build is broken?

**Comment by chrox** [comment]
Oh, I should test it earlier. The new glib has a dependency of pthread. I have sent a new PR on #318.

**Comment by hwhw** [comment]
Though the busted tests do still fail. Hm. Did they ever work recently or are they only run for the main koreader repository?

**Comment by chrox** [comment]
I noticed that the koptcontext sometimes failed the spec at `totable/fromtable` but it doesn't fail reliably. So probably it needs further investigation.

**Pull request merged**
