### PR TITLE
Make sure nnsvg links against libm in every circumstances

### PR DESCRIPTION
**Pull request by NiLuJe**
* Link flags on the left of `-o`: deprecated. May apparently eat your firstborn's soul and/or said link flags ^^.
* Linking order: stuff that *requires* symbols on the left of stuff that *provides* those symbols. (And LuaJIT *requires* libm ;)).

Re https://github.com/koreader/koreader/issues/7190

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1292)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Looks fine, but did you test or should I?

**Comment by NiLuJe** [comment]
Haven't tested on affected systems, no, so, be my guest ;).

**Comment by Frenzie** [comment]
Well, I imagine using a pre ~Ubuntu 20.04 to build the whole thing and testing on something newer is part of it, anyway. I'll give it a quick build on my desktop (or not that quick since I haven't built non-debug in quite a while…)

**Comment by Frenzie** [comment]
Drat, I forgot about this:

```
cd koreader-appimage-x86_64-linux-gnu && pwd && \
	rm -rf tmp && mkdir -p tmp && \
	cp -Lr koreader tmp && \
	rm -rf tmp/koreader/ota && \
	rm -rf tmp/koreader/resources/icons/src && \
	rm -rf tmp/koreader/spec
/home/frans/src/kobo/koreader/koreader-appimage-x86_64-linux-gnu
cp: cannot stat 'koreader/libs/libbsd.so.0': No such file or directory
```

Meh, let's just bump it and see what happens. I don't feel like dragging out the ole' Docker image tonight. xP

**Pull request merged**
