### PR TITLE
Random basket of fixes

### PR DESCRIPTION
**Pull request by NiLuJe**
Re: https://github.com/koreader/koreader/issues/9506

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1515)

### CODE REVIEW

**Comment by Frenzie** [comment]
Er, could you hold off on this unless you're super sure and tested extensively. It's too late to think about this atm but you'll forgive me for putting eyes like Argus on this code path. ;-P

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
Now includes moar stuff!

(Specifically, more Android STL madness).

(rebase me ;p).

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
Okay, did another pass on the FFI vs. C99 shenanigans, and I don't see anything potentially broken there.

I pinned the proper types for HB, but since there were no 64-bit types involved, it's pretty harmless.

**Comment by NiLuJe** [comment]
Actually tested on the emulator (a.k.a., "I broke SDL the first time around" ;p).

**Comment by NiLuJe** [comment]
And I broke sdcv on Android, whee.

Because it needs MOAR PIE!

**Comment by Frenzie** [comment]
Have fun. xp

Btw I'll be moving next week so if you don't see me you know why. ;)

**Comment by NiLuJe** [comment]
On the upside, I've updated my phone to Lineage, so at least I've got root via adb now.

(I may only just have remembered that *after* uninstalling the old APK :D).

**Comment by NiLuJe** [comment]
FFS, forgot that bionic doesn't support rpath.

**Comment by NiLuJe** [comment]
There, requires fugly ass frontend hackery because bionic is the worst, but it works.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Comment by akemnade** [comment]
compiled that thing and now I have a usable touchscreen on the Tolino Shine 2 HD with the deb package.

**Comment by Frenzie** [comment]
> FFS, forgot that bionic doesn't support rpath.

Like I said, I despise it.

**Comment by NiLuJe** [comment]
Went on a bit of a harfbuzz spree there...

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Pull request merged**
