### PR TITLE
[fix] Detect Clang

### PR DESCRIPTION
**Pull request by Frenzie**
This will result in horrible failures, but it'll hopefully be easier to get an overview through the CI.

### CODE REVIEW

**Comment by Frenzie** [comment]
Observations while the tests are running: Travis now uses Clang again while CircleCI doesn't. (Good thing we kept Travis around for the moment.)

**Comment by NiLuJe** [comment]
I should have just ditched that naive check and used the real Clang check that I added a few lines below that ;).

**Comment by NiLuJe** [comment]
In slightly related concerns (verbosity), I just checked a local build, without VERBOSE in my env, yields a 15232 lines long log (2761890 bytes, so, a bit over half the allowed size).

So I'm not quite sure what Android is doing to have logs that are at least twice as large :?

**Comment by NiLuJe** [comment]
Oh. the Android-only stuff (libiconv, gettext), is *insanely* verbose.

**Comment by NiLuJe** [comment]
So, yeah, libiconv & gettext *probably* deserve their `--silent` in the BUILD & INSTALL commands ;).

**Comment by Frenzie** [comment]
I say "horrible failures", the CI says "WHEEEEEE".

> I should have just ditched that naive check and used the real Clang check that I added a few lines below that ;).

Ah, so I should just move that up a few lines? Sometime after dinner/tomorrow, that is. ;-P

**Comment by NiLuJe** [comment]
There's a bit of a catch-22 in that the test definitely should be using the $(CHOST) prefixed CC when that makes sense, and that block is the one that sets CC to CHOST-CC,, but, yeah, at least it should pretty solidly devices it it's actually Clang instead of something masquerading as ca clang binary ;).

**Comment by Frenzie** [comment]
@NiLuJe I think this should do the trick then?

**Comment by Frenzie** [comment]
Hm, it's a little unclear to me what the purpose is here:

```
##############################################################################
#############################  COMPILER OPTIONS  #############################
##############################################################################
# These options mainly affect the speed of the JIT compiler itself, not the
# speed of the JIT-compiled code. Turn any of the optional settings on by
# removing the '#' in front of them. Make sure you force a full recompile
# with "make clean", followed by "make" if you change any options.
#
DEFAULT_CC = gcc
#
# LuaJIT builds as a native 32 or 64 bit binary by default.
CC= $(DEFAULT_CC)
#
# Use this if you want to force a 32 bit build on a 64 bit multilib OS.
#CC= $(DEFAULT_CC) -m32
```

Of course on Mac OS gcc is simply a symlink to Clang. I could just add an `update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-7 380`.

**Comment by NiLuJe** [comment]
> @NiLuJe I think this should do the trick then?

Nope, see my "Catch-22" comment. That'd make it check CC instead of CHOST-CC (which is what we do want to check) in cases where CHOST is set (which is nearly everywhere except emulator builds). ;).

**Comment by NiLuJe** [comment]
IIRC, we should be enforcing pretty much everything when building LuaJIT, I don't *think* this can be an issue, as we *do* enforce CC (& HOST_CC & TARGET_CC) when building it ;).

**Comment by Frenzie** [comment]
@NiLuJe Well, I'm not really following the Catch 22. It seems to be setting it based on CC, so then what's there to check afterward?

**Comment by NiLuJe** [comment]
Except this high up, CC is stil CC, not yet CHOST-CC. We do want to check CGOST-CC? not CC ;).

**Comment by Frenzie** [comment]
Right, thanks.

**Comment by NiLuJe** [comment]
I don't really see a cleaner solution than either setting an initial

```
ifdef CHOST
    CC:=$(CHOST)-$(CC)
endif
```

right above it, and then let the "real" one set that to CHOST-gcc or CHOST-clang ;).

**Comment by Frenzie** [comment]
What about keeping things more or less as they were, but using `$(findstring)` instead of a stupid "misses clang-x" `ifeq ($(CC), clang)`.

**Comment by NiLuJe** [comment]
Yeah, that might end up being less troublesome ;).

**Comment by NiLuJe** [comment]
I don't remember where I wondered about that, but I don't think we actually need the strip CCACHE shenanigans *anywhere*, as we no longer enforce CC:=CCACHE CC anywhere ;).

**Comment by NiLuJe** [comment]
Oh, wait, it's worse. I'm *really* stupid. I was reading those as "strip CCACHE from CC", while they're in fact doing "strip whitespace from CCACHE CC".

i.e., I'm doing the very thing I just said we shouldn't do: prepend CCACHE to CC.

*facepalm*

**Comment by Frenzie** [comment]
lol, I'll remove them all then

**Comment by NiLuJe** [comment]
Thanks ;).

Hopefully CMake will make everything pick it up, otherwise we might actually need to keep one, when we set CC for the final time ;).

**Comment by Frenzie** [comment]
Now we have a failing Clang test in Circle CI, but at least it's using Clang. The Travis Clang test isn't failing, so I'll go ahead and merge this for the CCACHE CC stuff. (Hopefully that'll fix Android.)

**Pull request merged**
