### PR TITLE
sdcv patch: allow utf8 encoded in -u dictnames (try 2)

### PR DESCRIPTION
**Pull request by poire-z**
Second attempt at solving this problem. See https://github.com/koreader/koreader/pull/3378#issuecomment-338478405

### CODE REVIEW

**Comment by Frenzie** [comment]
*cough*`./kodev release kobo`*cough*

**Comment by poire-z** [comment]
I haven't set up the whole arm cross compiling stuff since I upgraded to debian stretch - avoiding that till I really need it.
And I won't ask you to launch a nightly build, so I will only be disapointed tomorrow if this doesn't work :)

**Comment by Frenzie** [comment]
I can quickly compile it for you to test if you like.

**Comment by Frenzie** [comment]
This ought to do it.

[sdcv-allow-utf8-encoded-in-u-kobo.zip](https://github.com/koreader/koreader-base/files/1404958/sdcv-allow-utf8-encoded-in-u-kobo.zip)

**Comment by poire-z** [comment]
Thank you.
Seems to work!
Your binary is 1,1 MB vs 684 KB nightly - vs 198KB our fork in old nightlys, hope it's the same anyway, nor just stripped.
May be I somehow notice it is faster than yesterday's nightly, dunno if you build it some specific way.

**Comment by Frenzie** [comment]
Nothing specific, but this is my regular desktop Debian Stretch. As you know the nightly build has a very different toolchain.

**Pull request merged**
