### PR TITLE
thirdparty/libjpeg-turbo 3.0.2

### PR DESCRIPTION
**Pull request by Frenzie**
https://github.com/libjpeg-turbo/libjpeg-turbo/compare/3.0.1...3.0.2

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1733)

### CODE REVIEW

**Review by NiLuJe — APPROVED** [review]

**Comment by Frenzie** [comment]
Uh oh, perhaps these CMake improvements broke things. Serves me right for thinking to do a quickie using the web ui...

https://github.com/libjpeg-turbo/libjpeg-turbo/commit/5a2353c2dad951af3f823ca4f9bdee293876cea1

**Comment by NiLuJe** [comment]
Yeah, that seems to have broken our `CMAKE_INSTALL_PREFIX`...

**Comment by NiLuJe** [comment]
Enforcing the `:PATH` type on our end might be enough to deal with it?

**Comment by Frenzie** [comment]
Assuming you mean this, no such luck:
```diff
diff --git a/thirdparty/libjpeg-turbo/CMakeLists.txt b/thirdparty/libjpeg-turbo/CMakeLists.txt
index 1c4f6c7e..4a186dcf 100644
--- a/thirdparty/libjpeg-turbo/CMakeLists.txt
+++ b/thirdparty/libjpeg-turbo/CMakeLists.txt
@@ -16,8 +16,8 @@ endif()
 # CMake hell.
 # We expect lib later on in Makefile.third, even on multilib systems...
 list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${BINARY_DIR}")
-list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_LIBDIR=lib")
-list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_INCLUDEDIR=include")
+list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_LIBDIR:PATH=lib")
+list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_INCLUDEDIR:PATH=include")
 list(APPEND CMAKE_ARGS "-DCMAKE_SKIP_RPATH=TRUE")
 
 # c.f., https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake
@@ -44,7 +44,7 @@ endif()
 ko_write_gitclone_script(
     GIT_CLONE_SCRIPT_FILENAME
     https://github.com/libjpeg-turbo/libjpeg-turbo.git
-    3.0.1
+    3.0.2
     ${SOURCE_DIR}
 )
```

**Comment by Frenzie** [comment]
I think this should do it:
```diff
diff --git a/thirdparty/libjpeg-turbo/CMakeLists.txt b/thirdparty/libjpeg-turbo/CMakeLists.txt
index 1c4f6c7e..359e2011 100644
--- a/thirdparty/libjpeg-turbo/CMakeLists.txt
+++ b/thirdparty/libjpeg-turbo/CMakeLists.txt
@@ -16,8 +16,8 @@ endif()
 # CMake hell.
 # We expect lib later on in Makefile.third, even on multilib systems...
 list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${BINARY_DIR}")
-list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_LIBDIR=lib")
-list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_INCLUDEDIR=include")
+list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_LIBDIR=${BINARY_DIR}/lib")
+list(APPEND CMAKE_ARGS "-DCMAKE_INSTALL_INCLUDEDIR=${BINARY_DIR}/include")
 list(APPEND CMAKE_ARGS "-DCMAKE_SKIP_RPATH=TRUE")
 
 # c.f., https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake
@@ -44,7 +44,7 @@ endif()
 ko_write_gitclone_script(
     GIT_CLONE_SCRIPT_FILENAME
     https://github.com/libjpeg-turbo/libjpeg-turbo.git
-    3.0.1
+    3.0.2
     ${SOURCE_DIR}
 )
```

**Comment by Frenzie** [comment]
Everything's green, fine by you?

**Pull request merged**
