### PR TITLE
Bundle FBInk for visual feedback in Kobo startup scripts

### PR DESCRIPTION
**Pull request by NiLuJe**
Letting the CI do the work to check if I did this right ;p.

### CODE REVIEW

**Comment by NiLuJe** [comment]
Wheeee!

For ref: I'm not putting this in Kindle builds because:

* We have eips there, and even if it's slightly clunkier to use properly, we've long since taken care of that.
* There's a bit of an issue with the K4, where it basically needs a legacy binary, and not the K5 one, so it doesn't quite work with our target splits, and it'd a bit of a PITA to handle properly on FBInk's side ;).

**Comment by poire-z** [comment]
@NiLuJe : I was building for arm on my linux with some debian arm build stuff, and got:
```
[ 75%] Performing build step for 'fbink'
cd koreader/base/thirdparty/fbink/build/arm-linux-gnueabihf-debug/fbink-prefix/src/fbink && sh -c "make MINIMAL=1 CROSS_TC=\"arm-linux-gnueabihf\" CFLAGS=\"-Og -g -pipe  -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mthumb -mfloat-abi=hard -fno-finite-math-only -fno-stack-protector -U_FORTIFY_SOURCE -fPIC -DKOBO_PLATFORM\" LDFLAGS=\"-Wl,-O1 -Wl,--as-needed -static-libstdc++\" strip"
make[5]: Entering directory 'koreader/base/thirdparty/fbink/build/arm-linux-gnueabihf-debug/fbink-prefix/src/fbink'
mkdir -p Debug/shared/utf8 Debug/static/utf8
arm-linux-gnueabihf-gcc  -D_REENTRANT=1 -DFBINK_MINIMAL -Og -g -pipe  -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mthumb -mfloat-abi=hard -fno-finite-math-only -fno-stack-protector -U_FORTIFY_SOURCE -fPIC -DKOBO_PLATFORM -DDEBUG -Wall -Wformat=2 -Wformat-signedness -Wformat-truncation=2 -Wextra -Wunused -Wnull-dereference -Wuninitialized -Wduplicated-branches -Wduplicated-cond -Wundef -Wbad-function-cast -Wwrite-strings -Wjump-misses-init -Wlogical-op -Wstrict-prototypes -Wold-style-definition -Wshadow -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Winline -Wcast-qual -Wcast-align -Wconversion -Wpadded -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wmissing-format-attribute -o Debug/fbink_cmd.o -c fbink_cmd.c
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-Wformat-truncation=2'; did you mean '-Wline-truncation'?
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-Wduplicated-branches'; did you mean '-Wduplicated-cond'?
Makefile:147: recipe for target 'Debug/fbink_cmd.o' failed
make[5]: *** [Debug/fbink_cmd.o] Error 1
```
gcc version 6.3.0 20170516 (Debian 6.3.0-18)

So, the koreader build didn't complete (but enough for me to get the crengine libs I wanted).

**Comment by NiLuJe** [comment]
Gah, stupid GCC which doesn't ignore unknown options (or didn't, at least).

**Comment by NiLuJe** [comment]
```
When an unrecognized warning option is requested (e.g., -Wunknown-warning), GCC emits a diagnostic stating that the option is not recognized. However, if the -Wno- form is used, the behavior is slightly different: no diagnostic is produced for -Wno-unknown-warning unless other diagnostics are being produced. This allows the use of new -Wno- options with old compilers, but if something goes wrong, the compiler warns that an unrecognized option is present. 
```

Or not? (https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)

**Comment by NiLuJe** [comment]
Ah, right. And I was just happily wondering by which miracle it picked up on the fact that you were running a Debug build :D.

**Comment by poire-z** [comment]
Confirming everything builds fine with latest masters :)

**Comment by NiLuJe** [comment]
Thanks! Sorry about that -_-".

**Pull request merged**
