### PR TITLE
SDL: Handle and forward SDL_DROPTEXT events

### PR DESCRIPTION
**Pull request by johnbeard**
This allows the client to handle things like dragged URLs and other
text.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1291)

### CODE REVIEW

**Review by Frenzie — COMMENTED** [review]
I think you forgot to commit the ffi and cdecl stuff but otherwise sure, why not? ^_^

**Comment by johnbeard** [comment]
What cdecl stuff is needed for this? `DROPFILE` doesn't seem to have any?

**Comment by Frenzie** [comment]
I think you meant to say it's already in there, don't worry.

https://github.com/koreader/koreader-base/blob/8614f997e487c440a9bb57252c20401f2aec54f3/ffi/SDL2_0_h.lua#L306-L307

https://github.com/koreader/koreader-base/blob/b8ac18ef9f31a76c9a1e8e9de3741908dcb19077/ffi-cdecl/SDL2_0_decl.c#L83-L84

**Review by Frenzie — APPROVED** [review]

**Comment by johnbeard** [comment]
Ah right, I thought there was something _extra_ I was supposed to be doing :laughing:

**Pull request merged**
