### PR TITLE
Get rid of debug hooks shenanigans

### PR DESCRIPTION
**Pull request by NiLuJe**
It's currently horribly broken on CircleCI under Busted, for... reasons.
And, surprise surprise, it was originally implemented as... a CI hack.
(in 897906d91a3cbba0eb2aa27583a6510c99ac720d).
Plus, I don't think we actually ever set debug hooks in the first place
anyway?

I fully expect the testsuite to implode on some random new stuff instead,
but, oh, well.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1213)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Probably okay, but you could also just say something like `debug = {sethook = function() end}` so a human can easily swap it in and out.

**Comment by NiLuJe** [comment]
AFAIU, nothing is ever actually setting a hook, so I'm not sure it serves
any purpose now, even in the best of times ;).

**Comment by NiLuJe** [comment]
Also, C BB now ;p.

**Comment by Frenzie** [comment]
> AFAIU, nothing is ever actually setting a hook

Depends a bit, if they're in Really Useful™ positions I tend to prefer keeping such things around for the future over cleaning it up, so to speak. ymmv I suppose

**Pull request merged**
