### PR TITLE
ci: bump docker images

### PR DESCRIPTION
**Pull request by benoit-pierre**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1774)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
I don't understand why a Circle CI build is not triggered… ¯\\_(ツ)_/¯

**Comment by benoit-pierre** [comment]
I think the CircleCI checks are not run because I've enabled my fork on CircleCI. Another casualty of the fact that CircleCI run the checks directly on the PR branch instead of the merge like other CIs?

**Comment by benoit-pierre** [comment]
Here's the [run](https://app.circleci.com/pipelines/github/benoit-pierre/koreader-base/70/workflows/fcda6b4d-4e9d-4075-9edc-f54719545aa2).

**Comment by Frenzie** [comment]
Thanks!

**Comment by Frenzie** [comment]
Cross-ref to https://github.com/koreader/virdevenv/pull/94 for potential future readers.

**Pull request merged**
