### PR TITLE
[build] Add -fsanitize=undefined to debug flags

### PR DESCRIPTION
**Pull request by Frenzie**
Forgot to push this back in October, see https://github.com/koreader/crengine/pull/90#issuecomment-338333188

<hr>

Some more info here: https://developers.redhat.com/blog/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/

Btw, there are more sanitize options, some of which are mutually exclusive.

Clang has 'em too. (Based on the same lib?) http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#ubsan-checks

### CODE REVIEW

**Comment by Frenzie** [comment]
```
gcc: error: unrecognized command line option ‘-fsanitize=undefined’
```

@poire-z The easiest solution would be to say that we now require 4.9 as a minimum. By default Travis is on `gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4` but 4.9 is readily available.

Alternative and arguably better because it's just a little flag, check gcc version first: https://stackoverflow.com/a/21491594

**Comment by poire-z** [comment]
I don't really know much about build process (gcc versions, CMakefile...), so I can't really give much input on these topics.
Can only say I have these on my debian: gcc 4:6.3.0-4 gcc-6 6.3.0-18+deb9u1

**Comment by Frenzie** [comment]
My desktop runs on Stretch with gcc 6.3 as well. ;-)

gcc 4.8 was the default in Ubuntu 14 (five-year LTS until next year) and contemporaries. (Ubuntu versions being date-based makes it an easy point of reference.) There was something similar at play with upping the requirement *to* 4.8 (https://github.com/koreader/koreader/commit/e5675af467e07de7d62b3b3a71375d167dcffb4d), with the important distinction that all of our tests and toolchain are currently on 4.8.

It'd make things harder to understand to write something like "regular build 4.7, debug build 4.8/4.9" but that's basically how it is.

I could stick in something like this:
```
GCC_VER_GTE49 := $(shell echo `gcc -dumpversion | cut -f1-2 -d.` \>= 4.9 | sed -e 's/\./*100+/g' | bc )
ifeq ($(GCC_VER_GTE49),1)
  BASE_CFLAGS:=-fsanitize=undefined $(BASE_CFLAGS)
endif
```

There's also clang to worry about in that case though:
```bash
$ gcc -dumpversion
6.3.0
$ clang -dumpversion
4.2.1
```

I'd like to have it though. I'll have to think about it some more.

**Comment by Frenzie** [comment]
@poire-z What do you think of my workaround? I'm quite happy with it since the version thing was kind of stupid.

**Comment by poire-z** [comment]
Nice check (gcc does compile empty files without any warning!?)
I just hope it won't shout at us many wrong things that we lived with finely :)

**Comment by poire-z** [comment]
Got some build failure:
```
[ 50%] No update step for 'mupdf'
[ 62%] No configure step for 'mupdf'
[ 75%] Performing build step for 'mupdf'
make[5]: Entering directory 'base/thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf'
    MKDIR build/release/generated
    MKDIR build/release/scripts
    MKDIR build/release/source/fitz
    MKDIR build/release/source/pdf
    MKDIR build/release/source/xps
    MKDIR build/release/source/svg
    MKDIR build/release/source/cbz
    MKDIR build/release/source/html
    MKDIR build/release/source/gprf
    MKDIR build/release/source/tools
    MKDIR build/release/source/helpers
    MKDIR build/release/source/helpers/mu-threads
    MKDIR build/release/platform/x11
    MKDIR build/release/platform/x11/curl
    MKDIR build/release/platform/gl
    MKDIR generated
    CC build/release/scripts/namedump.o
    CC build/release/scripts/hexdump.o
    LINK build/release/scripts/namedump.exe
build/release/scripts/namedump.o: In function `main':
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:40: undefined reference to `__ubsan_handle_type_mismatch'
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:57: undefined reference to `__ubsan_handle_type_mismatch'
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:36: undefined reference to `__ubsan_handle_nonnull_arg'
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:75: undefined reference to `__ubsan_handle_type_mismatch'
build/release/scripts/namedump.o: In function `get_line':
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:22: undefined reference to `__ubsan_handle_type_mismatch'
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:22: undefined reference to `__ubsan_handle_out_of_bounds'
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:20: undefined reference to `__ubsan_handle_type_mismatch'
thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:20: undefined reference to `__ubsan_handle_out_of_bounds'
build/release/scripts/namedump.o: In function `main':
base/thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:47: undefined reference to `__ubsan_handle_type_mismatch'
base/thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:43: undefined reference to `__ubsan_handle_type_mismatch'
base/thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:54: undefined reference to `__ubsan_handle_type_mismatch'
base/thirdparty/mupdf/build/x86_64-linux-gnu-debug/mupdf-prefix/src/mupdf/scripts/namedump.c:50: undefined reference to `__ubsan_handle_type_mismatch'
collect2: error: ld returned 1 exit status
Makefile:94: recipe for target 'build/release/scripts/namedump.exe' failed
```
I have `libubsan0 6.3.0-18+deb9u1` installed, dunno if I need something else.

crengine seems to have recompiled fine with `-fsanitize=undefined`

**Comment by Frenzie** [comment]
I must've done something wrong yesterday. Okay, this needs to be reverted.

**Comment by Frenzie** [comment]
@poire-z The problem is actually that you'd need to manually delete `libmupdf.so` (or let's just say base/build/arch/libs). But the thing is that we don't really want to know this about every lib we use anyway. Something along these lines should suffice:

```diff
diff --git a/Makefile b/Makefile
index 0bab8ad..01d4a95 100644
--- a/Makefile
+++ b/Makefile
@@ -109,7 +109,7 @@ endif
 $(OUTPUT_DIR)/libs/libkoreader-cre.so: cre.cpp \
                        $(if $(or $(ANDROID),$(WIN32)),$(LUAJIT_LIB),) \
                        $(CRENGINE_LIB)
-       $(CXX) -I$(CRENGINE_SRC_DIR)/crengine/include/ $(DYNLIB_CFLAGS) \
+       $(CXX) -I$(CRENGINE_SRC_DIR)/crengine/include/ $(DYNLIB_CFLAGS) -fsanitize=undefined \
                -DLDOM_USE_OWN_MEM_MAN=$(if $(WIN32),0,1) \
                $(if $(WIN32),-DQT_GL=1) -static-libstdc++ -o $@ $^
 ifdef DARWIN
diff --git a/thirdparty/kpvcrlib/CMakeLists.txt b/thirdparty/kpvcrlib/CMakeLists.txt
index 4d5a063..da3ad93 100644
--- a/thirdparty/kpvcrlib/CMakeLists.txt
+++ b/thirdparty/kpvcrlib/CMakeLists.txt
@@ -38,6 +38,10 @@ INCLUDE_DIRECTORIES(
        ${CREGINE_INCLUDE_DIR}
 )
 
+IF(DEFINED ENV{KODEBUG})
+    SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=undefined")
+ENDIF()
+
 IF(DEFINED ENV{WIN32})
     ADD
```

https://github.com/koreader/crengine/issues/136 was probably also related to me being bitten by flag-related issues in the build process.

**Pull request merged**
