### PR TITLE
bump crengine: support for partial rerenderings, loading & zip optimisations

### PR DESCRIPTION
**Pull request by poire-z**
#### util.isSubProcessDone(): add 'wait' option

So we can wait for the process to be done (by not using WNOHANG).
Also add getppid and some contants to ffi/posix.
Needed for managing and communicating with the background rerendering subprocess.
(Done by hand, hoping there's no difference from the expected ffi_cdecl output).

#### bump crengine: support for partial rerenderings

Includes:
- https://github.com/koreader/crengine/pull/506
  - Cache: minor simplifications 
  - Cache: improve cache file reproducibility
- https://github.com/koreader/crengine/pull/507
  - CHM: minor cleanup
  - LVStream: minor cleanups
  - LVStream: fix and improve `LVZipDecodeStream` implementation
  - LVStream: disable CRC checks for ZIP streams
- https://github.com/koreader/crengine/pull/508
  - CSS: optimize :nth-child/of-type() and :nth-last-child/of-type()
  - Page splitting: fix oversight in flags handling
  - Update _doc_rendering_hash also when loading from cache
  - getDocumentRenderingHash(extended): add parameter
  - Toggable support for partial rerenderings of individual DocFragments

cre.cpp: add methods for partial rerenderings

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1582)

### CODE REVIEW

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1582)* status: all files reviewed, 2 unresolved discussions (waiting on @poire-z)

___
*[`cre.cpp` line 748 at r1](https://reviewable.io/reviews/koreader/koreader-base/1582#-NOH-B0A75CNZNHDXj_k:-NOH-B0A75CNZNHDXj_l:b-hvzyxo) ([raw file](https://github.com/koreader/koreader-base/blob/e23846aacbc3fc8075857b4a901462caadc1ebb4/cre.cpp#L748)):*
> ```cpp
>     lua_pushboolean(L, doc->dom_doc->isCacheFileStale());
>     return 1;
> }
> ```

nit: Some of the new code uses space instead of tabs for indents.

EDIT: Okay, looking at the full file, the mess is real and not new ;o).
___
*[`cre.cpp` line 845 at r1](https://reviewable.io/reviews/koreader/koreader-base/1582#-NOH-V2X4Qj8Zdg18gyw:-NOH-V2X4Qj8Zdg18gyx:b-es6jtn) ([raw file](https://github.com/koreader/koreader-base/blob/e23846aacbc3fc8075857b4a901462caadc1ebb4/cre.cpp#L845)):*
> ```cpp
>             lua_pushboolean(L, doc->dom_doc->isPartialRerenderingEnabled());
>             return 1;
>         }
> ```

nit: Re: earlier comment. This is actually problematic here, because tabs & spaces are mixed *in the same function* ;).

**Comment by NiLuJe** [comment]
The `ffi` stuff looks fine ;).

**Comment by poire-z** [comment]
> Don't we already set CRLog to output to stderr?
> This is actually problematic here, because tabs & spaces are mixed in the same function ;).

Yep, I usually painfully fixed them at the end, forgot to do it this time :/
Will come fixed with the bump for crengine.

**Review by NiLuJe — COMMENTED** [review]
I'm pretty sure there's space/tabs mixmatches left in cre.cpp (I only mentioned the first one ;)).

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1582#-:-NOMnwVU1G5hlFLJ5N2J:bls92g6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @poire-z)

**Review by NiLuJe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1582)* status: all files reviewed, 1 unresolved discussion (waiting on @poire-z)

___
*[`cre.cpp` line 1176 at r2](https://reviewable.io/reviews/koreader/koreader-base/1582#-NOMo9aT1rCmfjlcpnq3:-NOMo9aT1rCmfjlcpnq4:b762o6o) ([raw file](https://github.com/koreader/koreader-base/blob/89e3dcc03dd6957ea31d9f192ac6522e56e116d2/cre.cpp#L1176)):*
> ```cpp
> 	CreDocument *doc = (CreDocument*) luaL_checkudata(L, 1, "credocument");
>         doc->text_view->getToc();
>         doc->text_view->getPageMap();
> ```

nit: spaces instead of tabs



_Code quote:_
```cpp
        doc->text_view->getToc();
        doc->text_view->getPageMap();
```

**Comment by poire-z** [comment]
Happens when copying lines from different existing functions that use different tab/space :/
Fixed for my stuff, but not for the existing stuff just around mine.

Fine with the ffi and util stuff ?

**Review by NiLuJe — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1582)* status: all files reviewed, 1 unresolved discussion (waiting on @poire-z)

**Pull request merged**
