### PR TITLE
crengine: return description and keywords metadata

### PR DESCRIPTION
**Pull request by poire-z**
See https://github.com/koreader/crengine/pull/74
crengine bumped, which also includes "css related improvement" commit

### CODE REVIEW

**Comment by Frenzie** [comment]
It's unclear to me why the kindle/kobo/pocketbook targets are failing. O-o

**Comment by poire-z** [comment]
Various permissions problems:
```
ccache: FATAL: Could not find compiler "arm-linux-gnueabihf-gcc" in PATH
install -d build/arm-linux-gnueabi/libs
install: cannot create directory 'build': Permission denied

install: cannot change permissions of 'toolchain': Operation not permitted
make: *** [pocketbook-toolchain] Error 1
```
Closing and re-opening to trigger a new build, just to see if it's repeatable.

**Comment by poire-z** [comment]
Failed again.

**Comment by Frenzie** [comment]
> Various permissions problems:

I meant I don't understand why there'd suddenly be permissions problems. :-P

**Comment by poire-z** [comment]
Trying again a day after, with crengine rebumbed to include the 2 commits just merged.

**Comment by poire-z** [comment]
Tried again after some `id, ls -la and chmod 777` added to `.ci/build_script.sh`:
 ```
uid=1000(ko) gid=1000(ko) groups=1000(ko),27(sudo)

drwxr-xr-x  8 ko   ko   4096 Jun 27 11:14 .
drwxr-xr-x 10 root root 4096 Jun 27 11:14 ..
-rw-r--r--  1 ko   ko    220 Apr  9  2014 .bash_logout
-rw-rw-r--  1 ko   ko    397 Oct  9  2016 .bashrc
drwxr-xr-x  3 ko   ko   4096 Oct 11  2016 .cache
drwxrwxrwx 19 2000 2000 4096 Oct 28  2016 .ccache
drwxr-xr-x  5 ko   ko   4096 Oct 11  2016 .luarocks
-rw-r--r--  1 ko   ko    675 Apr  9  2014 .profile
drwxrwxr-x 12 2000 2000 4096 Jun 27 11:13 base
-rwxrwxr-x  1 root root  224 Oct  2  2016 build_kobo_tc.sh
-rwxrwxr-x  1 root root  890 Sep 30  2016 install_luarocks.sh
drwxr-xr-x  7 ko   ko   4096 Oct 11  2016 local
drwxr-xr-x  3 ko   ko   4096 Oct 11  2016 x-tools

chmod: changing permissions of '.': Operation not permitted
```

Looks like travis (who did the git fetch thirdparty) uid is 2000, ko (who tries to build in docker) uid is 1000
Any way to see history of these docker images (i know nothing about docker) ? Although the content of the home dir does not seem to have changed recently. May be some changes of uid on the travis side ?

Tried a few things, but in the end, adding `sudo chown -R ko:ko .` in between `cd /home/ko/base` and `make` seem to solve the problem.
Is that fix fine enough or do we want to dig deeper in the root cause ?

Should I let in @frankyifei 's 3 crengine commits ? Or do we want individual nightlys with each one to allow for easier testing/bissecting in case of problems ?

Should I make that 3 commits (one for the travis build fix, one for frankyfei 3 crengine changes, one for my description metadata stuff) ?

**Comment by Frenzie** [comment]
Travis added a notice to the build log in the meantime.

> This job ran on our Trusty, sudo: required environment which was updated on Wednesday, June 21st. Read all about it on [our blog](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch) and take note that you can add `group: deprecated-2017Q2` in your .travis.yml file to use the previous version. 

It's probably worth checking if that's the difference.

> Tried a few things, but in the end, adding sudo chown -R ko:ko . in between cd /home/ko/base and make seem to solve the problem.

Should be fine. There's already a bunch of that in the script you modified after all.

> Should I make that 3 commits (one for the travis build fix, one for frankyfei 3 crengine changes, one for my description metadata stuff) ?

I think it's fine the way it is. I'll merge it now.

**Pull request merged**
