### PR TITLE
Find regex

### PR DESCRIPTION
**Pull request by zwim**
The new PR for finding regex. See aborted #1378 for previous discussions.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1380)

### CODE REVIEW

**Comment by zwim** [comment]
The story goes on: crengine here has https://github.com/koreader/koreader-base/pull/1380/commits/0b8b2afa39ef02e386e9eddbdf0e873f8336a64d
but crengine in https://github.com/koreader/crengine/commits/master has https://github.com/koreader/crengine/commit/feb97ff4843d1c98dd17b2e5928066f3dfe3edee

**Comment by poire-z** [comment]
Looks ok to me.
```
wget  https://github.com/koreader/koreader-base/pull/1380.diff
vi 1380.patch

diff --git a/thirdparty/kpvcrlib/crengine b/thirdparty/kpvcrlib/crengine
index 844be5032..feb97ff48 160000
--- a/thirdparty/kpvcrlib/crengine
+++ b/thirdparty/kpvcrlib/crengine
@@ -1 +1 @@
-Subproject commit 844be50324fb7ddd7849bca04a191803f264f237
+Subproject commit feb97ff4843d1c98dd17b2e5928066f3dfe3edee
```
They match prev and current.

**Comment by poire-z** [comment]
Ah f*ck. No CircleCI ha srun.... Launching it manually... That will be 30/40 more minutes /

**Comment by poire-z** [comment]
And I don't see any "unauthorized" PR ... that I could act on :/ Wtf ?

**Comment by zwim** [comment]
Hasn't there been a change on circleci recently?

**Comment by poire-z** [comment]
Dunno, I don't follow what's happening on their side.
(Like they realized they had forgotten to curse you on koreader-base like they did on koreader, and they just fixed that ? :)
@Frenzie any idea ?

**Comment by poire-z** [comment]
And I don't see your frontend PR https://github.com/koreader/koreader/pull/7883 either :/
And even @hius07 PRs were unauthorized these last days and had not run.
(Before, @hius07 PR were run, and yours were visible and just unauthorize.)

**Comment by zwim** [comment]
Maybe this has something to do with a missing .circleci/config.yml
When I log in to circleci I see the following

grafik

**Comment by zwim** [comment]
An if I click n "Not Run" I see the following ... anomaly that violates CircleCI Terms of Service

I have not the slightest idea what to do.
BTW: The missing `missing .circleci/config.yml` is in the repo.

I will pause this for now, as I have to go to Switzerland tomorrow morning very early. I will be back on Thursday afternoon.

grafik

**Comment by poire-z** [comment]
OK, good night & trip.
Hopefully, @Frenzie will have an idea, because I don't get CircleCI.

**Comment by Frenzie** [comment]
koreader-base doesn't have any secrets (for pushing docs and coverage)

But didn't you fix it with a dummy `koreader-vars` or whatever it's called exactly?

**Comment by Frenzie** [comment]
Wait, an anomaly? What does that link to?

**Comment by Frenzie** [comment]
That sounds like something exclusive to your account, but I have no idea what that could be.

**Comment by zwim** [comment]
I have found: https://discuss.circleci.com/t/we-have-detected-an-anomaly-that-violates-the-circleci-terms-of-service/37878
and a link within the former: https://support.circleci.com/hc/en-us/articles/360043679453-CircleCI-Terms-of-Service-Violation-Sanctioned-Country

I informed the circleci guys and girls, that I am a European citizen, living and working in Austria. So I should not be affected be export restrictions. Let's see how this goes on.

@poire-z : As this request to circleci seems to take some time, how shall I go on with this PR?

**Comment by poire-z** [comment]
I guess I'l ljust merge it :) and we should get CircleCI triggered on our master branch.
We just need to be sure it compiles on all platform - if not, we'll have to find a solution (or revert) before somebody else needs to push something into koreader-base.
So, let's go.

**Comment by Frenzie** [comment]
Not quite done yet, but looks like it should finish with no complaints.

**Comment by zwim** [comment]
Thank you. Shall I do a pump base in koreader/findRegex?

**Comment by poire-z** [comment]
(We call that "bump", not "pump" - even if it sounds correct to me that we could pump a submodule into a parent module ? :)
Just wait for the yellow dot to turn green (click on the dot, waiting for Kindle and Cervantes builds to end) at https://github.com/koreader/koreader-base/commits/master .

**Pull request merged**
