### PR TITLE
bump LunaSVG: minor upstream fixes (gcc-13 support)

### LINKED ISSUE #1604: lunasvg compile error with gcc-13.1.0
lunasvg does not compile with gcc 13.1.0

[compile.log.txt](https://github.com/koreader/koreader-base/files/11365891/compile.log.txt)

### PR DESCRIPTION
**Pull request by poire-z**
Brings https://github.com/sammycage/lunasvg/compare/585d61eef24510bc0b7fe3d9e768d0675d4b5a6f...f924651b85cac47dbe15f51a4aa320461fc1d07b
Closes #1604.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1606)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
Any idea why that build crapchain would fail (for the devices arch, not the emuones):

FAILED: CMakeFiles/crengine.dir/crengine/crengine/src/lvimg.cpp.o 
/home/ko/x-tools/arm-kobo-linux-gnueabihf/bin/arm-kobo-linux-gnueabihf-g++ --sysroot=/home/ko/x-tools/arm-kobo-linux-gnueabihf/arm-kobo-linux-gnueabihf/sysroot  -DALLOW_KERNING=1 -DCHM_SUPPORT_ENABLED=1 -DCR3_ANTIWORD_PATCH=1 -DCR3_PATCH=1 -DCR_EMULATE_GETTEXT -DENABLE_ANTIWORD=1 -DHAVE_PROTOTYPES -DHAVE_STAT64=1 -DHAVE_UNSIGNED_CHAR -DLINUX=1 -DMATHML_SUPPORT=1 -DNDEBUG=1 -DUSE_FONTCONFIG=0 -DUSE_FREETYPE=1 -DUSE_FRIBIDI=1 -DUSE_HARFBUZZ=1 -DUSE_LIBUNIBREAK=1 -DUSE_LIBWEBP=1 -DUSE_LUNASVG=1 -DUSE_NANOSVG=0 -DUSE_SRELL_REGEX=1 -DUSE_UTF8PROC=1 -DUSE_ZSTD=1 -D_LARGEFILE64_SOURCE=1 -D_LINUX=1 -Dcrengine_EXPORTS -Dmain=xxxmain -I../staging-arm-kobo-linux-gnueabihf/include -I/home/ko/base/thirdparty/mupdf/build/arm-kobo-linux-gnueabihf/mupdf-prefix/src/mupdf/scripts -I/home/ko/base/thirdparty/freetype2/build/arm-kobo-linux-gnueabihf/freetype2-prefix/src/freetype2-build/include/freetype2 -I/home/ko/base/thirdparty/harfbuzz/build/arm-kobo-linux-gnueabihf/harfbuzz-prefix/src/harfbuzz-build/include/harfbuzz -I/home/ko/base/thirdparty/fribidi/build/arm-kobo-linux-gnueabihf/fribidi-prefix/src/fribidi-build/include -I/home/ko/base/thirdparty/libunibreak/build/arm-kobo-linux-gnueabihf/libunibreak-prefix/src/libunibreak-build/include -I/home/ko/base/thirdparty/utf8proc/build/arm-kobo-linux-gnueabihf/utf8proc-prefix/src/utf8proc -I../../crengine/thirdparty/antiword -I../../crengine/thirdparty/chmlib/src -I/home/ko/base/thirdparty/libpng/build/arm-kobo-linux-gnueabihf/libpng-prefix/src/libpng-build/include -I/home/ko/base/thirdparty/zlib/build/arm-kobo-linux-gnueabihf/zlib-prefix/src/zlib/include -I/home/ko/base/thirdparty/libjpeg-turbo/build/arm-kobo-linux-gnueabihf/libjpeg-turbo-prefix/src/libjpeg-turbo-build/include -I/home/ko/base/thirdparty/libwebp/build/arm-kobo-linux-gnueabihf/libwebp-prefix/src/libwebp-build/include **-I/home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/include/lunasvg** -I/home/ko/base/thirdparty/zstd/build/arm-kobo-linux-gnueabihf/zstd-prefix/src/zstd-build/include -I/home/ko/base/thirdparty/srell -I../../crengine/crengine/include -O2 -ffast-math -pipe -fomit-frame-pointer   -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mthumb -mfloat-abi=hard  -fPIC -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/crengine.dir/crengine/crengine/src/lvimg.cpp.o -MF CMakeFiles/crengine.dir/crengine/crengine/src/lvimg.cpp.o.d -o CMakeFiles/crengine.dir/crengine/crengine/src/lvimg.cpp.o -c ../../crengine/crengine/src/lvimg.cpp
../../crengine/crengine/src/lvimg.cpp:53:10: fatal error: lunasvg.h: No such file or directory
   53 | #include <lunasvg.h>
      |          ^~~~~~~~~~~
compilation terminated

**Comment by poire-z** [comment]
```
make[2]: Leaving directory '/home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build'
Install the project...
-- Install configuration: ""
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/include/lunasvg/lunasvg.h
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/include/lunasvg/xlunasvg.h
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/include/lunasvg/lunasvg_export.h
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/lib/liblunasvg.so
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/lib/cmake/lunasvg/lunasvgTargets.cmake
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/lib/cmake/lunasvg/lunasvgTargets-noconfig.cmake
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/lib/cmake/lunasvg/lunasvgConfig.cmake
-- Installing: /home/ko/base/thirdparty/lunasvg/build/arm-kobo-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/build/staging-arm-kobo-linux-gnueabihf/lib/cmake/lunasvg/lunasvgConfigVersion.cmake
```

For some reason, cmake decided to pout stuff in a `build/staging-arm-linux-gnueabihf/` intermediate directory ?!:
```
installed in:
base/thirdparty/lunasvg/build/arm-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/**build/staging-arm-linux-gnueabihf/**include/lunasvg/lunasvg.h
base/thirdparty/lunasvg/build/arm-linux-gnueabihf/lunasvg-prefix/src/lunasvg-build/include/lunasvg
expected in ^
```

**Comment by poire-z** [comment]
Looks like adding in lunasvg's root CMakeLists.txt:
```cmake
# When cross-compiling, avoid installation in a
# "build/staging-arm-linux-gnueabihf/" subdirectory
set(CMAKE_STAGING_PREFIX "${CMAKE_INSTALL_PREFIX}")
```
solves the problem.

**Comment by poire-z** [comment]
Of course.....:
```
FAILED: lunasvg-prefix/src/lunasvg-stamp/lunasvg-configure 
cd /home/ko/base/thirdparty/lunasvg/build/arm-linux-androideabi/lunasvg-prefix/src/lunasvg-build && /usr/bin/cmake -DCMAKE_TOOLCHAIN_FILE=/home/ko/base/thirdparty/cmake_modules/CMakeCross.cmake -DCMAKE_INSTALL_PREFIX=/home/ko/base/thirdparty/lunasvg/build/arm-linux-androideabi/lunasvg-prefix/src/lunasvg-build -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_INCLUDEDIR=include -DCMAKE_SKIP_BUILD_RPATH:BOOL=True "-DCMAKE_EXE_LINKER_FLAGS=-Wl,-O1 -Wl,--as-needed -L/home/ko/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -no-canonical-prefixes -Wl,--fix-cortex-a8 -march=armv7-a -lgnustl_shared" "-DCMAKE_MODULE_LINKER_FLAGS=-Wl,-O1 -Wl,--as-needed -L/home/ko/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -no-canonical-prefixes -Wl,--fix-cortex-a8 -march=armv7-a -lgnustl_shared" "-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-O1 -Wl,--as-needed -L/home/ko/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -no-canonical-prefixes -Wl,--fix-cortex-a8 -march=armv7-a -lgnustl_shared" "-DCMAKE_C_FLAGS= -O2 -ffast-math -pipe -fomit-frame-pointer  -std=gnu11 -march=armv7-a -mfpu=vfpv3-d16 -mthumb -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -mfloat-abi=softfp --sysroot /home/ko/android-ndk-r15c/platforms/android-14/arch-arm -fPIC" "-DCMAKE_CXX_FLAGS= -O2 -ffast-math -pipe -fomit-frame-pointer  -std=gnu++11 -march=armv7-a -mfpu=vfpv3-d16 -mthumb -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -mfloat-abi=softfp --sysroot /home/ko/android-ndk-r15c/platforms/android-14/arch-arm -I/home/ko/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/ko/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fPIC" -DBUILD_SHARED_LIBS=ON "-GUnix Makefiles" /home/ko/base/thirdparty/lunasvg/build/arm-linux-androideabi/lunasvg-prefix/src/lunasvg && /usr/bin/cmake -E touch /home/ko/base/thirdparty/lunasvg/build/arm-linux-androideabi/lunasvg-prefix/src/lunasvg-stamp/lunasvg-configure
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version 3.10.2
```

**Comment by poire-z** [comment]
The upstream cmake required version bump was done by `https://github.com/sammycage/lunasvg/pull/84`.
Dunno if I should try lowering it (no idea if the other cmake changes really requires 3.13 or if they will be fine with only requiring 3.10).
Of if you can/prefer updating it in the android toolchains ?

**Comment by Frenzie** [comment]
I'm not even sure if it's doing anything that wouldn't work in 3.3.

> Of if you can/prefer updating it in the android toolchains ?

Prefer yes, but can has been a failure so far.

**Comment by poire-z** [comment]
About to update LunaSVG, first to the 4th latest commit in https://github.com/sammycage/lunasvg/commits/master, which reverts many of the Cmake crap I had to handle in this PR.....
I will also clean some remnants tweaks for the old Android toolchain.

And as a second step, I'll try updating to latest (quite annoying how often upstream refactors...).

@benoit-pierre : I remember that for some of our `#include`, you wanted to get a subdir (ie. fribidi).
Any problem for you if I revert this (made in this PR, no longer to do with their revert):
```
-		-DLUNASVG_INCLUDE_DIR="$(LUNASVG_DIR)/include" \
+		-DLUNASVG_INCLUDE_DIR="$(LUNASVG_DIR)/include/lunasvg" \
```
?
Or should I patch their CMakefile so lunasvg.h ends up in a lunasvg/ dir ?

I should also update a few Harfbuzz related deprecated stuff like:
```
crengine/src/lvfntman.cpp:2529:44: warning: 'void hb_font_get_glyph_shape(hb_font_t*, hb_codepoint_t, hb_draw_funcs_t*, void*)' is deprecated: Use 'hb_font_draw_glyph' instead [-Wdeprecated-declarations]
 2529 |                     hb_font_get_glyph_shape(_hb_font, code, SVGGlyphsCollector_svg_funcs, svg_collector);
```

I guess I can just hardcode the new names, and no need to stay compatible with older Harfbuzz versions? (if anybody is using our crengine with some older harfbuzz, it's there problem, right?)

**Comment by poire-z** [comment]
I also noticed these warnings in the MacOS build some days ago....:
```
/Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xlunasvg.h:11:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               external_font_spec_t
/Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xlunasvg.h:12:27: note: type is not C-compatible due to this default member initializer
    const char * family = nullptr;
                          ^~~~~~~
/Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xlunasvg.h:18:3: note: type is given name 'external_font_spec_t' for linkage purposes by this typedef declaration
} external_font_spec_t;



In file included from /Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/source/parser.cpp:19:
/Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xtspanelement.h:54:10: warning: 'path' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    Path path() const { return Path{}; } // not used
         ^
/Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/source/geometryelement.h:17:18: note: overridden virtual function is here
    virtual Path path() const = 0;
                 ^
In file included from /Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/source/parser.cpp:19:
/Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xtspanelement.h:56:27: warning: 'clone' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    std::unique_ptr<Node> clone() const;
                          ^
/Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/source/element.h:169:35: note: overridden virtual function is here
    virtual std::unique_ptr<Node> clone() const = 0;
                                  ^
3 warnings generated.


/Users/runner/work/koreader-base/koreader-base/thirdparty/kpvcrlib/crengine/crengine/src/lvimg.cpp:2262:13: warning: expression result unused [-Wunused-value]
            *src++;
            ^~~~~~
2 warnings generated.

```
Haven't yet thought about them, but if you have thoughts whether to fix them in the code, use some compiler options, or ignore them, they are welcome :)

**Comment by benoit-pierre** [comment]
> @benoit-pierre : I remember that for some of our `#include`, you wanted to get a subdir (ie. fribidi).

IMHO, the ideal situation is where all headers are installed to a subdirectory (no risk of accidental inclusion without the right `-I`) and have a prefix to avoid namespace collision, like freetype:

```
/usr/include/freetype2/
├── freetype
│   ├── config
│   │   ├── ftconfig.h
[…]
│   │   └── public-macros.h
│   ├── freetype.h
│   ├── ftadvanc.h
│   ├── ftbbox.h
[…]
│   └── tttags.h
└── ft2build.h

3 directories, 54 files
```

> Any problem for you if I revert this (made in this PR, no longer to do with their revert):
> 
> ```
> -		-DLUNASVG_INCLUDE_DIR="$(LUNASVG_DIR)/include" \
> +		-DLUNASVG_INCLUDE_DIR="$(LUNASVG_DIR)/include/lunasvg" \
> ```
> 
> ? Or should I patch their CMakefile so lunasvg.h ends up in a lunasvg/ dir ?

But in any case, I try to follow the convention of the project (so for the meson port I will install headers in the same location as with CMake, generate a similar pkg-config entry, etc…).

So no issue for me.

**Comment by poire-z** [comment]
```
lvimg.cpp:2262:13: warning: expression result unused [-Wunused-value]
            *src++;
```
I guess I just have to remove the `*`, right ? :/

For the other "override" stuff, a bit in the dark until the MacOS CI confirms:
```diff
--- a/xtended/xtspanelement.h
+++ b/xtended/xtspanelement.h
@@ -51,9 +51,9 @@ public:

     void layout(LayoutContext* context, LayoutContainer* current) const override; // not used

-    Path path() const { return Path{}; } // not used
+    Path path() const override { return Path{}; } // not used

-    std::unique_ptr<Node> clone() const;
+    std::unique_ptr<Node> clone() const override;
 };

 } // namespace lunasvg
```
`Path path() const override { implementation }` , is the ordering of const override before implementation alright?
(For when there is no implementation, like for `clone()`, I have const override after it elsehwere, so this should be fine.)

**Comment by benoit-pierre** [comment]
> I also noticed these warnings in the MacOS build some days ago....:
> 
> ```
> /Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xlunasvg.h:11:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
> typedef struct {
>               ^
>                external_font_spec_t
> /Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xlunasvg.h:12:27: note: type is not C-compatible due to this default member initializer
>     const char * family = nullptr;
>                           ^~~~~~~
> /Users/runner/work/koreader-base/koreader-base/thirdparty/lunasvg/build/x86_64-apple-darwin20.6.0/lunasvg-prefix/src/lunasvg/xtended/xlunasvg.h:18:3: note: type is given name 'external_font_spec_t' for linkage purposes by this typedef declaration
> } external_font_spec_t;

```diff
--- subprojects/packagefiles/lunasvg/overlay/xtended/xlunasvg.h	2023-07-13 00:06:35.081329533 +0200
+++ subprojects/lunasvg/xtended/xlunasvg.h	2023-07-15 14:21:58.766855630 +0200
@@ -8,14 +8,14 @@
 typedef struct external_context_t external_context_t;
 
 // Font specification, given to external text to glyph SVG paths converter
-typedef struct {
+struct external_font_spec_t {
     const char * family = nullptr;
     double size = 16;
     short weight = 400;
     bool italic = false;
     unsigned int features = 0;
     const char * lang = nullptr;
-} external_font_spec_t;
+};
 
 // Prototype of callback (defined in xtspanelement.cpp) to receive SVG paths for each glyph
 typedef std::function<void(const char * path_d, double advance_x, double advance_y, bool can_adjust_from_previous, unsigned int base_char)> tspan_path_callback_t;
```

For the other warnings, I think I already fixed some of them too, check https://github.com/benoit-pierre/koreader/tree/bpierre/subprojects/packagefiles/lunasvg/overlay.

**Comment by benoit-pierre** [comment]
> ```
> lvimg.cpp:2262:13: warning: expression result unused [-Wunused-value]
>             *src++;
> ```

Yep.

**Comment by poire-z** [comment]
Thanks !

About the lunasvg build, I get this:
```
[ 62%] Performing configure step for 'lunasvg'
-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
```
These variables were added with https://github.com/koreader/koreader-base/commit/4d9ac09f144deb8ad1df631a31d6161c405a1ffb
Not touching that and letting that to you CMake tamers :)

**Pull request merged**
