### PR TITLE
bump crengine: minor fixes, upstream picks

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- (Upstream) Fix errors in lString16 to 32 update https://github.com/koreader/crengine/pull/395
- (Upstream) Misc Win32 fixes
- (Upstream) lString32: add 2 additional pos() methods
- (Upstream) Ignore WORD_JOINER when font has no glyph
- (Upstream) FB2 metadata: discard empty genres
- FB2: mark 2nd++ BODYs as non-linear
- Fix support in EPUB for ``
- XML parsing: correctly parse `CDATA` https://github.com/koreader/crengine/pull/397

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1252)

### CODE REVIEW

**Comment by pazos** [comment]
@poire-z @NiLuJe : for one time the failure in macos is relevant.

`otool -L` won't list libluajit.so as needed by libkoreader-nnsvg, so the command fails. I wonder if that's because the hidden attribute. I will check

**Comment by poire-z** [comment]
Thanks @pazos, waiting for your feedback before bumping base into front.
(Merging this PR, as it's unrelated to the nnsvg issue.)

**Comment by pazos** [comment]
@poire-z: nothing to do with -fvisibility=hidden. The following diff fixes the issue

```diff
diff --git a/Makefile b/Makefile
index b49b784e..f7ba5656 100644
--- a/Makefile
+++ b/Makefile
@@ -190,11 +190,11 @@ ifdef DARWIN
                $@
 endif
 
-$(OUTPUT_DIR)/libs/libkoreader-nnsvg.so: nnsvg.c \
+$(OUTPUT_DIR)/libs/libkoreader-nnsvg.so: \
                        $(if $(USE_LUAJIT_LIB),$(LUAJIT_LIB),) \
-                       $(NANOSVG_HEADERS)
+                       nnsvg.c
        $(CC) -I$(NANOSVG_INCLUDE_DIR) \
-       $(CFLAGS) $(DYNLIB_CFLAGS) -fvisibility=hidden -Wall -o $@ nnsvg.c
+       $(CFLAGS) $(DYNLIB_CFLAGS) -fvisibility=hidden -Wall -o $@ $^
 ifdef DARWIN
        install_name_tool -change \
                `otool -L "$@" | grep "libluajit" | awk '{print $$1}'` \
```

**Comment by Frenzie** [comment]
> for one time the failure in macos is relevant.

I thought it was crapping out early these days because it's such a lovely always moving target?

**Comment by poire-z** [comment]
I think I need that dependancy on `$(NANOSVG_HEADERS)` to be "built" (actually, copied from the source to some common place NANOSVG_INCLUDE_DIR=`/thirdparty/nanosvg/build/include/` so this build can find them here.
That's the reason I did what you're just reverting :) :/
(Or may be it's because I build my little library with another recipe I hijack/add in the Makefile?)

**Comment by poire-z** [comment]
Precisely, this target;
https://github.com/koreader/koreader-base/blob/3ea2a698aa6938dc866c0999574ee5fe11da34d3/Makefile.third#L791-L800

**Comment by poire-z** [comment]
```
install_name_tool -change \
		`otool -L "build/x86_64-apple-darwin19.6.0/libs/libkoreader-nnsvg.so" | grep "libluajit" | awk '{print $1}'` \
		libs/libluajit.so \
		build/x86_64-apple-darwin19.6.0/libs/libkoreader-nnsvg.so
Usage: /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
make: *** [build/x86_64-apple-darwin19.6.0/libs/libkoreader-nnsvg.so] Error 1
```

What's the difference before/after in the output of that ?
`otool -L "build/x86_64-apple-darwin19.6.0/libs/libkoreader-nnsvg.so" `
I guess just `libluajit` missing - which feels like it could still be the fault of fvisibility=hidden...

**Comment by pazos** [comment]
> What's the difference before/after in the output of that ?

## Without  the change

```
base/build/x86_64-apple-darwin20.1.0/libs/libkoreader-nnsvg.so:
	build/x86_64-apple-darwin20.1.0/libs/libkoreader-nnsvg.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

and otool fails as in the log.

## with the change

```
base/build/x86_64-apple-darwin20.1.0/libs/libkoreader-nnsvg.so:
	build/x86_64-apple-darwin20.1.0/libs/libkoreader-nnsvg.so (compatibility version 0.0.0, current version 0.0.0)
	libs/libluajit.so (compatibility version 2.1.0, current version 2.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

-fvisibility doesn't change that :/

**Comment by poire-z** [comment]
What does this (vs current master) do ?
```diff
-       $(CFLAGS) $(DYNLIB_CFLAGS) -fvisibility=hidden -Wall -o $@ nnsvg.c
+       $(CFLAGS) $(DYNLIB_CFLAGS) -fvisibility=hidden -Wall -o $@ nnsvg.c $(if $(USE_LUAJIT_LIB),$(LUAJIT_LIB),)
```
I remember it complained when I used `$^` - which then included `$(NANOSVG_HEADERS)` in there - so let's just do as $^ wihout the headers - https://devhints.io/makefile

Our Master Builders @Frenzie & @NiLuJe will probably know the better way to do that.

**Comment by pazos** [comment]
I will try in a few minutes as I'm building master right now. Brew changed how luarocks is built and screw our build scripts again :(. osx is worse than android 😢

**Comment by poire-z** [comment]
Can I still bump base (so, breaking frontend Mac builds I guess, but making nightlies) - or is it best to wait till this is solved?

**Comment by pazos** [comment]
yeah, that works, the change was exactly:

```diff
diff --git a/Makefile b/Makefile
index b49b784e..185fc082 100644
--- a/Makefile
+++ b/Makefile
@@ -194,7 +194,8 @@ $(OUTPUT_DIR)/libs/libkoreader-nnsvg.so: nnsvg.c \
                        $(if $(USE_LUAJIT_LIB),$(LUAJIT_LIB),) \
                        $(NANOSVG_HEADERS)
        $(CC) -I$(NANOSVG_INCLUDE_DIR) \
-       $(CFLAGS) $(DYNLIB_CFLAGS) -fvisibility=hidden -Wall -o $@ nnsvg.c
+       $(CFLAGS) $(DYNLIB_CFLAGS) -fvisibility=hidden -Wall -o $@ nnsvg.c \
+               $(if $(USE_LUAJIT_LIB),$(LUAJIT_LIB),)
 ifdef DARWIN
        install_name_tool -change \
                `otool -L "$@" | grep "libluajit" | awk '{print $$1}'` \
```

> Can I still bump base (so, breaking frontend Mac builds I guess, but making nightlies) - or is it best to wait till this is solved?

Please update. mac builds are broken in many ways :p

**Pull request merged**
