### PR TITLE
mupdf: expand list of supported CSS color names

### PR DESCRIPTION
**Pull request by benoit-pierre**
Cf. https://github.com/koreader/koreader/pull/12158#issuecomment-2267492105

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1894)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
I'm surprised they don't have those upstream. They're liable to turn up sooner rather than later.

**Comment by ptrm** [comment]
Was dictionary displayed by something else than mupdf before the big upgrade? I remember darkgray working up till then (still not tested, will try to find some time)

**Comment by benoit-pierre** [comment]
Not that I'm aware, no.

**Comment by Frenzie** [comment]
It wouldn't have worked, no. This list of colors dates back a decade to the very first implementation: https://github.com/ArtifexSoftware/mupdf/commit/bb875f77f23ac4c51a072f4fc6692ce2dc352997

**Comment by Frenzie** [comment]
@benoit-pierre Do you still have remaining concerns about this? It looks straightforward and obvious to me. :-)

**Comment by benoit-pierre** [comment]
@ptrm: where you able to confirm this fix your invisible `darkgray` text?

**Pull request merged**
