### PR TITLE
MuPDF 1.13.0

### LINKED ISSUE #656: MuPDF 1.13
Pinging @TnS-hun :-)

It's not mentioned on https://mupdf.com/news.html yet but the `1.13.0` tag exists in the repo.

Because of the "Improvements to annotation editing API." mentioned in the changelog the build fails. I didn't investigate what changed exactly; this was just a quick test to see what would happen.

```
In file included from wrap-mupdf.c:24:0:
wrap-mupdf.h:119:21: error: unknown type name ‘fz_annot_type’; did you mean ‘fz_annot’?
     pdf_page *page, fz_annot_type type)
                     ^
wrap-mupdf.h:32:46: note: in definition of macro ‘MUPDF_WRAP’
     ret_type wrapper_name(fz_context *ctx, ##__VA_ARGS__);
                                              ^~~~~~~~~~~
In file included from wrap-mupdf.c:154:0:
wrap-mupdf.h:119:21: error: unknown type name ‘fz_annot_type’; did you mean ‘fz_annot’?
     pdf_page *page, fz_annot_type type)
                     ^
wrap-mupdf.h:49:53: note: in definition of macro ‘MUPDF_WRAP’
     extern ret_type wrapper_name(fz_context *ctx, ##__VA_ARGS__) { \
                                                     ^~~~~~~~~~~
```
screenshot_2018-04-20_16-42-46

Edit: btw, [MuPDF Explored](https://ghostscript.com/%7Erobin/mupdf_explored.pdf) was updated too.

### PR DESCRIPTION
**Pull request by TnS-hun**
Closes #656

### CODE REVIEW

**Comment by Frenzie** [comment]
So the backend changes are completely transparent without requiring changes in ffi/mupdf or front? Great! :-)

**Comment by Frenzie** [comment]
Ah, the unit test failed. Presumably that's fine but it'll require some manual double checking before updating the hash.

```
mupdf module PDF document API should open a page, add an annotation and write a new document
./spec/base/unit/mupdf_spec.lua:135: Expected objects to be equal.
Passed in:
(string) '0e0c0e59b8b8bac1465370985e707630'
Expected:
(string) 'ff191739c6f75894a975f336be0a623a'
```

**Comment by TnS-hun** [comment]
Getting busted to work was painful. In the end I needed to use a custom built LuaRocks just like in the CI.

I've submitted a new simple-out.pdf but it might have been too early. I want to double check against the version before MuPDF 1.12.0.

**Comment by Frenzie** [comment]
No problem.

**Comment by bahusoid** [comment]
Shouldn't we get rid of obsolete patches here?
At least the following patches seem to be already fixed in 1.13:
https://github.com/koreader/koreader-base/blob/master/thirdparty/mupdf/vec_dot.patch
https://github.com/koreader/koreader-base/blob/master/thirdparty/mupdf/no_icc_fixes.patch

**Comment by TnS-hun** [comment]
> Shouldn't we get rid of obsolete patches here?

Nice catch. I removed the SIZE_MAX patch too, that wasn't needed either.

@Frenzie: are those targets supposed to work in Travis? Because it's way too red. :)

It looks like it's because of HarfBuzz. Maybe caused by the changes to [Makerules](https://github.com/ArtifexSoftware/mupdf/commits/master/Makerules) and [Makethird](https://github.com/ArtifexSoftware/mupdf/commits/master/Makethird)?

**Comment by Frenzie** [comment]
@TnS-hun 
Yes, everything is very much supposed to be green, lol. I don't really have time to take a peek today (too late) or tomorrow though.

At a glance those errors are very suspicious. An error on something like -mthumb would suggest it's failing to use the cross compiler.

**Comment by NiLuJe** [comment]
@TnS-hun : Possibly. From a (very) quick glance, see if adding a `-DCXX="$(CXX)"` to https://github.com/koreader/koreader-base/blob/master/Makefile.third#L65 & `CXX=\"${CXX}\"` to https://github.com/koreader/koreader-base/blob/master/thirdparty/mupdf/CMakeLists.txt#L23 help?

**Comment by NiLuJe** [comment]
Whoops, I was a bit hasty: the `USE_SYSTEM_<THIRDPARTYLIB>` stuff is from MuPDF's current master branch, it's not in the 1.13.0 release, so, slightly less work to do.

Still something to remember for the next release, if it stays in as-is ;).

**Comment by Frenzie** [comment]
@NiLuJe Good catch. That'd certainly explain why it's not picking up on the g++ cross-compiler. :-P

**Comment by TnS-hun** [comment]
Thanks NiLuJe. That would have taken me a while to figure out.

**Comment by NiLuJe** [comment]
Happy to help ;).

**Comment by Frenzie** [comment]
I'm generally against altering the PDF file itself but I tried it for testing and that looks like this in Evince/Atril (after removing KOReader's own gray overlay). Is that expected? It's not a regression, mind you, just something I hadn't really noticed yet.

screenshot_2018-05-03_18-01-47

Anyway, the 1.13.0 as in this PR seems to be working fine. Ready to merge @TnS-hun or is there anything specific you'd like to test further first?

**Comment by TnS-hun** [comment]
I don't use PDFs or highlighting so I can't say what's the expected look.

I'm done with the testing: the annotation that's added by the test case is in the PDF, it's just not visible. It wasn't visible in the earlier versions either.

**Comment by Frenzie** [comment]
Thanks for the effort!

**Pull request merged**
