### PR TITLE
MµPDF 1.14.0

### PR DESCRIPTION
**Pull request by NiLuJe**
Here be dragons, a few API changes to pass some stuff by value instead of by reference...

And a buildsystem update, because of course. :D.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/762)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Special shout out to past self in #660 ;p.

**Comment by NiLuJe** [comment]
Sidebar: documentation is still abysmal, ripgrep is my best friend.

**Comment by NiLuJe** [comment]
Library authors: for the love of all that is holy, please *document* API changes in a clear, concise, and easy to find way.

**Comment by NiLuJe** [comment]
Probably addMarkupAnnotation -> pdf_set_annot_quad_points because of the switch from fz_rect to fz_quad

**Comment by NiLuJe** [comment]
Not quite sure what the wrapper function was doing there, so, err, help wanted ;p.

**Comment by NiLuJe** [comment]
Pro tip: calling a function that doesn't exist will segfault! :D.

`pdf_set_markup_appearance` is gone.

**Comment by NiLuJe** [comment]
I have no idea how any of this is supposed to work, so, if anyone wants to take care of it, be my guest ;).

**Comment by Frenzie** [comment]
I'm not really any more informed than you (and don't have much time to look). Did you already try dumping the Travis cache just in case they have some weird architectural issue or is it the same as locally?

**Comment by NiLuJe** [comment]
Nope, the function really is gone ;/. Since I'm not familiar with the PDF
specs, I have no idea how the new API replacing it are supposed to work.

**Comment by NiLuJe** [comment]
Let's just say that I've been less than enthused so far... ;).

**Comment by Frenzie** [comment]
> Quads instead of rects when highlighting and searching text.

Is that the relevant part of the changelog? I don't know what quads are in this context but it sounds like it might very well break all of our assumptions, although if there were a pointer on how to *use* them it might still be easy to keep it all the same for the frontend by just passing a rectangle.

But yeah… I don't have time to go code digging, atm and not much desire to do so on Sunday, at least this one. ;-)

**Comment by NiLuJe** [comment]
Haven't hit an issue related to that yet, no ;).

**Comment by NiLuJe** [comment]
(There's a link to the offending commit for the current issue in a comment added in the latest commit).

**Comment by Frenzie** [comment]
Good, that's one step closer. ;-)

**Comment by baskerville** [comment]
The following command might be helpful in knowing precisely how the API changed:
```sh
git diff 1.13.0..1.14.0 include
```

**Comment by NiLuJe** [comment]
My main concern is no longer ranting about undocumented changes, but instead [figuring out the replacing API](https://github.com/koreader/koreader-base/pull/762/commits/aafb1ed48d8f70e8e4d857a1f695787297be5f2f) with zero knowledge of the PDF format :D.

**Comment by bahusoid** [comment]
> for the love of all that is holy, please document API changes in a clear, concise, and easy to find way.

And voila [MuPdf 1.15 ](https://github.com/ArtifexSoftware/mupdf/tree/1.15.0 ) is out with [API changes](https://github.com/ArtifexSoftware/mupdf/blob/master/docs/api-changes.html) :) At least made in 1.14

Regarding [replacing API](https://github.com/NiLuJe/koreader-base/blob/aafb1ed48d8f70e8e4d857a1f695787297be5f2f/ffi/mupdf.lua#L635-L636).

Have you looked [here](https://github.com/ArtifexSoftware/mupdf/blob/master/platform/gl/gl-annotate.c#L98) (see how this `new_annot` is used)? I might be wrong but seems it contains similar logic that creates and manipulates with annotations. Looks like you need to simply call [`pdf_update_appearance`](https://github.com/ArtifexSoftware/mupdf/blob/57441f685fea936a51e941282526e7328e387d1c/platform/gl/gl-annotate.c#L106) instead plus:
* Line thickness seems be internalized (at least I didn't see it);
* for alpha setting call additionally [`pdf_set_annot_opacity`](https://github.com/ArtifexSoftware/mupdf/blob/57441f685fea936a51e941282526e7328e387d1c/platform/gl/gl-annotate.c#L556-L563);
* for color [`pdf_set_annot_color`](https://github.com/ArtifexSoftware/mupdf/blob/57441f685fea936a51e941282526e7328e387d1c/platform/gl/gl-annotate.c#L552)

At the end of manipulations it seems second call to [`pdf_update_appearance`](https://github.com/ArtifexSoftware/mupdf/blob/57441f685fea936a51e941282526e7328e387d1c/platform/gl/gl-annotate.c#L630) is required.

**Comment by NiLuJe** [comment]
Thanks for the heads up ;). That looks sensible, thanks!

This'll have to wait until k2pdfopt moves to this new MuPDF version, though ;). Provided the accompanying bump to tesseract and friends doesn't also drive me mad ;p.

**Comment by Frenzie** [comment]
1.16 comes with further significant API changes: https://github.com/ArtifexSoftware/mupdf/blob/97096297d409ec6f206298444ba00719607e8ba8/docs/api/changes.html

**Comment by NiLuJe** [comment]
No new k2pdfopt release yet, though, so 1.14 is still what it expects IIRC.

**Comment by Frenzie** [comment]
@NiLuJe I hope I merged it right; it was a quickie using the GH web GUI. k2pdfopt 2.52 just came out but it's still on MuPDF 1.14 I believe.

**Comment by NiLuJe** [comment]
I'll take a look at it sometime this week ;).

**Comment by roshavagarga** [comment]
[k2pdfopt 2.53](https://www.willus.com/k2pdfopt/k2pdfopt_version.txt) seems to have updated to MuPDF 1.17.

**Comment by roshavagarga** [comment]
@Frenzie @NiLuJe  [k2pdfopt 2.53](https://www.willus.com/k2pdfopt/k2pdfopt_version.txt) seems to have updated to MuPDF 1.17.

**Comment by NiLuJe** [comment]
@roshavagarga: Ah, now we're talking, thanks for the heads up!

I'll try to take a look at it Soon(TM)v;).

**Comment by NiLuJe** [comment]
Sidebar: soon may be late, because I won't be available for most of August ;p.

**Comment by Frenzie** [comment]
Well, have fun! ;-)

**Comment by Frenzie** [comment]
Superseded by https://github.com/koreader/koreader-base/pull/1203.

**Pull request closed without merging**
