### PR TITLE
Fix missing LUA_LJ_SQLITE dep

### PR DESCRIPTION
**Pull request by ezdiy**
Missed in 32af1b8

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1219)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Oops.

Thanks!

**Comment by Frenzie** [comment]
Will this require a new point release?

**Comment by poire-z** [comment]
> Will this require a new point release?

Nope.
This fixes https://github.com/koreader/koreader/pull/6778, that was merged this night, after you made 2020.10.1.

**Comment by NiLuJe** [comment]
And I just pulled the nightly zsync file from the OTA to prevent further nightly OTA updates until tomorrow ;).

**Pull request merged**
