### PR TITLE
ffi/posix: fix typo in cdecls

### PR DESCRIPTION
**Pull request by benoit-pierre**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1983)

### CODE REVIEW

**Review by NiLuJe — APPROVED** [review]
(The actual constant definition was okay, so this is just to avoid mishaps on future regens).

**Comment by benoit-pierre** [comment]
Yeah, except we can't really regen from `ffi-cdecl/posix_decl.c` which is how that discrepancy got in. ;(

**Comment by benoit-pierre** [comment]
I have not investigated, but I get this error:
```
ffi-cdecl/posix_decl.c:331:1: error: ...-pc-linux-gnu-debug/staging/share/lua/5.1//gcc/cdecl.lua:30: attempt to call method 'value' (a nil value)
stack traceback:
        ...-pc-linux-gnu-debug/staging/share/lua/5.1//gcc/cdecl.lua:30: in function 'format_attributes'
        ...-pc-linux-gnu-debug/staging/share/lua/5.1//gcc/cdecl.lua:266: in function 'format_node_class'
        ...-pc-linux-gnu-debug/staging/share/lua/5.1//gcc/cdecl.lua:354: in function 'format'
        ...4-pc-linux-gnu-debug/staging/share/lua/5.1/ffi-cdecl.lua:71: in function <...4-pc-linux-gnu-debug/staging/share/lua/5.1/ffi-cdecl.lua:45>
  331 | cdecl_func(htons)
      | ^~~~~~~~~~
```

But not if I comment the `cdecl_func(fopen)` line…

**Comment by NiLuJe** [comment]
Yeah, I recall it being pissy about something, unless a chunk of it was commented out :/.

It never really made much sense to me either (but it did work at one point, so not sure whether it got broken by newer glibcs, or by newer GCCs...).

Been happening for quite a while, though.

**Pull request merged**
