### PR TITLE
[chore] thirdparty patch file dependencies

### PR DESCRIPTION
**Pull request by Frenzie**
I'm going bonkers when a patch file is updated and nothing happens because only CMakeLists.txt is a dependency. This reruns CMake when any file in `thirdparty/<dependency>` changes. In practice that mostly means `*.patch` in addition to CMakeLists.txt. There's a `cr3.css` in kpvclib and that's probably about it, but I'm trying to be forward-thinking here.

### CODE REVIEW

**Comment by Frenzie** [comment]
Just `*` will include the directory `thirdparty/freetype/build`.

The manual doesn't seem to indicate any other way to exclude directories.

https://www.gnu.org/software/make/manual/html_node/Wildcard-Function.html
https://www.gnu.org/software/make/manual/html_node/Wildcard-Examples.html

**Comment by NiLuJe** [comment]
Do we actually need the wildcard function for a rule prerequisite?

The doc seems to hint that wildcards are expanded automatically in rule prereqs.

**Comment by Frenzie** [comment]
To my mind I was more or less following the example from the manual:

```
objects := $(patsubst %.c,%.o,$(wildcard *.c))

foo : $(objects)
        cc -o foo $(objects)
```

Which example/explanation are you referring to precisely?

**Comment by NiLuJe** [comment]
The "print" one from https://www.gnu.org/software/make/manual/html_node/Wildcard-Examples.html

**Comment by Frenzie** [comment]
D'oh, I must've overlooked that.

**Pull request merged**
