### PR TITLE
what happens with homebrew?

### PR DESCRIPTION
**Pull request by pazos**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1242)

### CODE REVIEW

**Comment by NiLuJe** [comment]
That's a good question. It's actually utterly borked on my laptop, and I can't be arsed to fix it there, so I'm a tad out of the loop on that front ^^.

**Comment by pazos** [comment]
@Frenzie: it seems that last xcode (12.0) builds fine **today**. I wonder what will happen tomorrow 😄

**Comment by Frenzie** [comment]
@pazos What do they keep doing over there? O_o I had previously naively thought that most breakage was due to us/me not testing on macOS, but ever since I set up this GitHub action it's broken itself… 3 or 4 times by now without any change on our side. :-/

**Comment by pazos** [comment]
No idea.

The brew error got fixed automagically so the change in brew deps order is no longer relevant
The issue with leptonica build and the C compiler cannot generate executables got fixed automagically ¿?

The only issue left which breaks the build in our end happens with "otooling" libkoreader-nnsvg.so. Once that's fixed everything else should work :p

**Pull request closed without merging**
