### PR TITLE
harfbuzz: Don't crash on invalid language tags.

### PR DESCRIPTION
**Pull request by ezdiy**
Fixes https://github.com/koreader/koreader/issues/6806

(to be verified)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1223)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Sounds sensible regardless, as it can indeed return a nullptr ;).

**Comment by zwim** [comment]
@ezdiy: with this patch I get 
`E/KOReader( 5976): [NativeThread]: failed to run script: ffi/harfbuzz.lua:25: bad argument #2 to 'hb_ot_name_get_utf8' (cannot convert 'nil' to 'unsigned int')
`
name_id is nil

**Comment by NiLuJe** [comment]
What happens if `n` is `0`? 

(i.e., is the nil guard on list working as intended, or should it be a check for n being 0 instead?)

**Comment by ezdiy** [comment]
@zwim Huh, there's something real weird going on. Can you `logger.dbg(list[i])` ? It seems like were geting entirely wrong ctype in here. name_id can't be nil:

```
typedef unsigned int hb_ot_name_id_t;
struct hb_ot_name_entry_t {
  hb_ot_name_id_t name_id;
  hb_var_int_t var;
  hb_language_t language;
};
```

**Comment by ezdiy** [comment]
Also `ffi/harfbuzz.lua:25` is suspect. There's no such call at line 25.

**Comment by zwim** [comment]
@ezdiy: You are right. I applied the #1223 patch again. It seems that I did something wrong the first time.
Now I did `git stash`; ` git fetch upstream ; git merge upstream/master` (no change, as expected) and then I patched the harfbuzz.lua with `patch -p1 <1223.patch` .

Not I get 
```
 E/KOReader( 6196): [NativeThread]: failed to run script: ffi/harfbuzz.lua:26: bad argument #3 to 'hb_ot_name_get_utf8' 
(cannot convert 'string' to 'const struct hb_language_impl_t *')
E/KOReader( 6196): [NativeThread]: Stopping due to previous errors
```

**Comment by zwim** [comment]
@ezdiy: I inserted `require("logger").err(list[i])` in the for loop in line 22
and got
`E/KOReader( 7550):  cdata<const struct hb_ot_name_entry_t &>: 0x6802c8d8`

**Comment by zwim** [comment]
@ezdiy: Maybe this helps you.
I changed
```
function hb_face_t:getNames(maxlen)
    maxlen = maxlen or 256
    local n = ffi.new("unsigned[1]")
    local list = hb.hb_ot_name_list_names(self, n)
    if list == nil then return end
    local buf = ffi.new("char[?]", maxlen)
    local res = {}
    for i=0, n[0]-1 do
        local name_id = list[i].name_id
        require("logger").err(list[i])
        local hb_lang = list[i].language
        require("logger").err(hb_lang)
        hb_lang = hb.hb_language_to_string(hb_lang)
        require("logger").err(hb_lang)
        if hb_lang ~= nil then
            hb_lang = ffi.string(hb_lang)
            require("logger").err(hb_lang)
            local got = hb.hb_ot_name_get_utf8(self, name_id, hb_lang, ffi.new("unsigned[1]", maxlen), buf)
            if got > 0 then
                res[hb_lang] = res[hb_lang] or {}
                res[hb_lang][name_id] = ffi.string(buf)
            end
        end
    end
    return res
end
```
I get
```
E/KOReader( 7724):  cdata<const struct hb_ot_name_entry_t &>: 0x6802c508
E/KOReader( 7724):  cdata<const struct hb_language_impl_t *>: 0x65f8fff0
E/KOReader( 7724):  cdata<const char *>: 0x65f8fff0
E/KOReader( 7724):  en
E/KOReader( 7724): [NativeThread]: failed to run script: ffi/harfbuzz.lua:30: bad argument #3 to 'hb_ot_name_get_utf8' (cannot convert 'string' to 'const struct hb_language_impl_t *')
E/KOReader( 7724): [NativeThread]: Stopping due to previous errors
```

**Comment by zwim** [comment]
@ezdiy: And when I change
`            local got = hb.hb_ot_name_get_utf8(self, name_id, list[i].language, ffi.new("unsigned[1]", maxlen), buf)`
to give hb_ot_name_get_utf8 at least the right type

I get
```
E/KOReader( 7767):  cdata<const struct hb_ot_name_entry_t &>: 0x6802c510
E/KOReader( 7767):  cdata<const struct hb_language_impl_t *>: 0x400f2fc8
E/KOReader( 7767):  cdata<const char *>: 0x400f2fc8
E/KOReader( 7767):  en
E/KOReader( 7767):  cdata<const struct hb_ot_name_entry_t &>: 0x6802c51c
E/KOReader( 7767):  cdata<const struct hb_language_impl_t *>: 0x400f2fc8
E/KOReader( 7767):  cdata<const char *>: 0x400f2fc8
E/KOReader( 7767):  en
+ hunderts of lines 
```
and KOReader closes

**Comment by ezdiy** [comment]
@zwim Ah, good point. Forgot I can't override the hb_lang at that point. Try with the next patch.

**Comment by zwim** [comment]
Sorry, I cannot do it now. I will try it tomorrow evening.

**Comment by zwim** [comment]
@ezdiy: Good news. With 62e1a9d KOReader does not crash. 
It works like expected

**Pull request merged**
