### PR TITLE
[Android] Build libdjvu

### PR DESCRIPTION
**Pull request by Frenzie**
References https://github.com/koreader/koreader/issues/1534

### CODE REVIEW

**Comment by Frenzie** [comment]
This one's been bugging me a lot on Android, but I was hoping @marmistrz would tackle it.

There don't seem to be any issues. Here's a screenshot of Android with this test file: https://en.wikisource.org/wiki/File:Test_rs20846.djvu

screenshot_1508008637

**Comment by Frenzie** [comment]
I was trying to grab a DjVu for testing from the Archive.org website as I'm used to and apparently they quit making new ones?! 

https://archive.org/post/1053214/djvu-files-for-new-uploads

An atrocious decision.

Btw @poire-z I didn't look into it but this isn't color-enabled yet. A quick glance suggests this might be the place to look:

https://github.com/koreader/koreader-base/blob/f0cad8faa0178f6543484e3477e4ef7e49bd02ea/djvu.c#L600-L607

**Comment by poire-z** [comment]
I know. I tried to enable it (and I just tried again), but I can't get something else than this kind of display:
reader_2017-oct-14_231400

There are other parts to tweak:
https://github.com/koreader/koreader-base/blob/f0cad8faa0178f6543484e3477e4ef7e49bd02ea/djvu.c#L101
https://github.com/koreader/koreader-base/blob/f0cad8faa0178f6543484e3477e4ef7e49bd02ea/djvu.c#L514-L528
with various possibilities:
```
     doc->pixelformat = ddjvu_format_create(DDJVU_FORMAT_GREY8, 0, NULL);
     doc->pixelformat = ddjvu_format_create(DDJVU_FORMAT_RGB24, 0, NULL);
     static unsigned int masks[4] = {0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000};
     doc->pixelformat = ddjvu_format_create(DDJVU_FORMAT_RGBMASK32, 4, masks);
```
but always that same kind of display.

**Comment by Frenzie** [comment]
The last one sounds the most interesting to me. Btw, we can also peek at the neighbors: https://github.com/mortenpi/ebookdroid/blob/e9a18b0842088d956c297aeb6697441a6b92c5fd/jni/ebookdroid/DjvuDroidBridge.cpp#L560-L561

**Comment by poire-z** [comment]
Just for reference, this should make it display correctly the page in colors (with `is_color_capable = false `commented in djvudocument.lua)
```c
--- a/djvu.c
+++ b/djvu.c
@@ -98,7 +98,9 @@ static int openDocument(lua_State *L) {
        while (! ddjvu_document_decoding_done(doc->doc_ref))
                handle(L, doc->context, True);

-       doc->pixelformat = ddjvu_format_create(DDJVU_FORMAT_GREY8, 0, NULL);
+//     doc->pixelformat = ddjvu_format_create(DDJVU_FORMAT_GREY8, 0, NULL);
+       static unsigned int masks[4] = {0x000000FF, 0x0000FF00, 0x00FF0000, 0xFF000000};
+       doc->pixelformat = ddjvu_format_create(DDJVU_FORMAT_RGBMASK32, 4, masks);
        if (! doc->pixelformat) {
                return luaL_error(L, "cannot create DjVu pixelformat for <%s>", filename);
        }
@@ -603,7 +605,7 @@ static int drawPage(lua_State *L) {
        BlitBuffer *bb = (BlitBuffer*) lua_topointer(L, 3);
        ddjvu_render_mode_t djvu_render_mode = (int) luaL_checkint(L, 6);
        ddjvu_rect_t pagerect, renderrect;
-       int bbsize = (bb->w)*(bb->h);
+       int bbsize = (bb->w)*(bb->h)*4;
        uint8_t *imagebuffer = bb->data;

        /*printf("@page %d, @@zoom:%f, offset: (%d, %d)\n", page->num, dc->zoom, dc->offset_x, dc->offset_y);*/
@@ -638,7 +640,7 @@ static int drawPage(lua_State *L) {
         * So we don't set rotation here.
         */

-       if (!ddjvu_page_render(page->page_ref, djvu_render_mode, &pagerect, &renderrect, page->doc->pixelformat, bb->w, imagebuffer))
+       if (!ddjvu_page_render(page->page_ref, djvu_render_mode, &pagerect, &renderrect, page->doc->pixelformat, bb->w*4, imagebuffer))
                memset(imagebuffer, 0xFF, bbsize);

        /* Gamma correction of the blitbuffer, do we need to build this into BlitBuffer? */

```
But it then crashes when you change zoom mode to Fit content (which it seems wants some RGB24, but even when you give it RGB24, it truncates the page in its 1/3...)

**Comment by Frenzie** [comment]
Minor update, upstream has now incorporated this: https://gitlab.com/koreader/djvulibre/-/commit/8e79901a927d7b20b629f5240e64f617d67f3dff

**Pull request merged**
