### PR TITLE
ci/circle: fix ccache cache, take 2

### PR DESCRIPTION
**Pull request by benoit-pierre**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1997)

### CODE REVIEW

**Comment by Frenzie** [comment]
I imagine this should be `${DOCKER_HOME}/.cache/ccache`?
https://github.com/koreader/koreader-base/blob/538f02435ffc80a6dbb8f84c10c20a8bd2443a78/.ci/build_script.sh#L24

**Comment by benoit-pierre** [comment]
> I imagine this should be `${DOCKER_HOME}/.cache/ccache`?
> 
> https://github.com/koreader/koreader-base/blob/538f02435ffc80a6dbb8f84c10c20a8bd2443a78/.ci/build_script.sh#L24

Not necessarily, since ccache will honor `~/.ccache`.

**Comment by benoit-pierre** [comment]
Wait, no, since it won't already exists.

**Comment by Frenzie** [comment]
> Wait, no, since it won't already exists.

ccache doesn't do that? That seems a little odd.

**Comment by Frenzie** [comment]
> Not that it mattered in that instance, since the directory is guaranteed to exists (as a mountpoint for docker), so I could have left it at that.

I meant for consistency and to prevent future confusion, unless there was a reason to have it different.

**Pull request merged**
