### PR TITLE
Fix brew not found on non-Mac platforms

### PR DESCRIPTION
**Pull request by Frenzie**
Follow-up to #1593

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1594)

### CODE REVIEW

**Comment by NiLuJe** [comment]
That'll lead to a concat with a nil, won't it? (i.e., this should have an else that sets it to the empty string).

**Comment by NiLuJe** [comment]
Oh, hey, it does. Never mind me :D.

**Comment by NiLuJe** [comment]
Oh, right, I was looking at the diff from the first PR, I'm not going entirely barmy, that's reassuring :D.

**Comment by Frenzie** [comment]
Yeah, I wasn't paying close enough attention and I was also doing some experiments with Podman.

The tl;dr is you need something like this which I don't find very convenient (but I guess it's supposedly more secure, at least on a server):
```
podman unshare chown -R 1000:1000 koreader-for-building-android
podman run -v $(pwd)/koreader-for-building-android:/home/ko/koreader -it localhost/frans/koandroid:0.5.3 bash
```

**Pull request merged**
