### PR TITLE
Ship all the necessary webp dependencies

### PR DESCRIPTION
**Pull request by NiLuJe**
Newer versions depend on the internal libsharpyuv, ship it.

Fix https://github.com/koreader/koreader/issues/10679#issuecomment-1632240549

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1634)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
lgtm

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
(No way to statically include it in the other libs ? It looks a bit unrelated with its name not mentionning "webp", and it is super small ?)

**Comment by NiLuJe** [comment]
I really don't want to have to deal with the buildsystem for a static link, so, no ;o).

**Comment by Frenzie** [comment]
> (No way to statically include it in the other libs ? It looks a bit unrelated with its name not mentionning "webp", and it is super small ?)

libwebp split it out for reasons that aren't completely clear to me. I guess someone asked for it.

https://github.com/webmproject/libwebp/commit/29cc95ce4cfeae88de13f44c43d8e73ffb782f79
https://github.com/webmproject/libwebp/commit/841960b670c7ed9324b0437b1cd2865b57fc3ad9
https://github.com/webmproject/libwebp/commit/a3b68c195e27248e4401e727dbdb21ea1ef1258f

**Pull request merged**
