### PR TITLE
ci: don't install SDL2 from brew

### PR DESCRIPTION
**Pull request by benoit-pierre**
Since the macOS build already come with one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1639)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
@NiLuJe: OK, do you want to add it to your #1638 pile?

**Comment by NiLuJe** [comment]
We're going to need a PR in front to handle the bump and updating the bundle script, so I have no particular attachment at how we go at this.

(I can push to this very branch if necessary anyway).

**Comment by benoit-pierre** [comment]
Note that the build script does not try to bundle brew' SDL, so for that particular issue, there's no need to patch it.

**Comment by pazos** [comment]
Not sure if it is relevant here but the emulator relies on brew's sdl2

**Comment by benoit-pierre** [comment]
How?

**Comment by pazos** [comment]
> How?

:p

Just by checking the history tree I realized the entire workflow exists just to generate macos artifacts.

So, yep, no relevant and indeed not needed since https://github.com/koreader/koreader-base/pull/1143

**Comment by benoit-pierre** [comment]
Ping!

**Comment by Frenzie** [comment]
Force pushing already pings. ;-)

**Pull request merged**
