### PR TITLE
PocketBook: import adjustAreaWithSaturationBrightnessAndDithering for color devices

### PR DESCRIPTION
**Pull request by dmalinovsky**
My hope is that playing with `dithering` parameter may help with https://github.com/koreader/koreader/issues/12527.

@rjd22, what do you think?

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1933)

### CODE REVIEW

**Comment by rjd22** [comment]
I'm okay with it so you can play around.

**Review by rjd22 — APPROVED** [review]

**Comment by Frenzie** [comment]
Could you suggest a slightly better commit message? `PocketBook: import adjustAreaWithSaturationBrightnessAndDithering for color devices`?

**Comment by dmalinovsky** [comment]
> Could you suggest a slightly better commit message? `PocketBook: import adjustAreaWithSaturationBrightnessAndDithering for color devices`?

Will the PR title change work?

**Comment by rjd22** [comment]
No you need to change the commit message. You can do so by doing a git commit amend (google it) and force pusing.

**Comment by NiLuJe** [comment]
> Will the PR title change

Since we squash by default, yes, that'll do ;).

**Comment by rjd22** [comment]
> > Will the PR title change work?
> 
> Since we squash by default, yes, that'll do ;).

That works? Sorry then. Ignore my message.

**Comment by NiLuJe** [comment]
> That works? Sorry then. Ignore my message.

I mean, we can choose the exact title & log when squashing, so, sort of ;p.

(There might have been a time where GH actually preferred the PR title over the commits, but that's not the case right now).

**Comment by Frenzie** [comment]
> Will the PR title change work?

A "that's fine" would've sufficed but I needed to know it wasn't incorrect in some way.

**Pull request merged**
