### PR TITLE
Initial support for NTX + MTK + Kaleido devices

### PR DESCRIPTION
**Pull request by NiLuJe**
* Bump LuaJIT to 20240422 (there's a potentially interesting 20-year old memory leak fixed)
* Update FBInk & KoboUSBMS to handle the new devices properly
* Update MTK headers for whatever we could glean of the new stuff
* Add dedicated refresh modes for Kaleido-specific waveform modes (basically, once for images, and one for text/highlights).
* Implemented a halfway sensible wait_for logic for those new devices
* Special-cased the Elipsa 2E because it behaves differently.
* "Fix" nightmode on the Elipsa 2E (thanks to #1768).
* And, as usual, workaround a few driver bugs in the process (as far as possible) ;p

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1779)

### CODE REVIEW

**Review by Frenzie — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1779)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @NiLuJe)

___
*[`ffi/framebuffer_mxcfb.lua` line 296 at r1](https://reviewable.io/reviews/koreader/koreader-base/1779#-NxENghW8KZVEU1Ssdo7:-NxENghW8KZVEU1Ssdo8:b8g71ug) ([raw file](https://github.com/koreader/koreader-base/blob/ad458eaa4fd47c794290b7999e36b03b34ed4b6f/ffi/framebuffer_mxcfb.lua#L296)):*
> ```Lua
>     --       c.f., epdc_process_update @ drivers/video/fbdev/mxc/mxc_epdc_v2_fb.c on a Kobo Mk. 7 kernel...).
>     -- And regardless of alignment constraints, make sure the rectangle is strictly bounded inside the screen.
>     x, y, w, h = bb:getBoundedRect(x, y, w, h, dither and 8 or fb.alignment_contraint)
> ```

Looks like a typo, one that's older I assume but still distracting

**Comment by Frenzie** [comment]
LuaJIT changes for those interested:
https://github.com/LuaJIT/LuaJIT/compare/d06beb0480c5d1eb53b3343e78063950275aa281...5790d253972c9d78a0c2aece527eda5b134bbbf7

**Comment by NiLuJe** [comment]
> Looks like a typo, one that's older I assume but still distracting

Err, where?

**Comment by NiLuJe** [comment]
> Could this be included [NiLuJe/FBInk#78](https://github.com/NiLuJe/FBInk/pull/78)?
> 
> There's a similar patch for kobo-usbms: https://github.com/benoit-pierre/koreader-base/blob/dev/thirdparty/kobo-usbms/fix_make_-n.patch

Welp. Somehow managed to miss email notification for this, my bad.

**Comment by NiLuJe** [comment]
> contrain vs constrain ;-)

Oh, yeah, that one's new, lol ;D.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1779)* status: all files reviewed, 1 unresolved discussion (waiting on @Frenzie)

___
*[`ffi/framebuffer_mxcfb.lua` line 296 at r1](https://reviewable.io/reviews/koreader/koreader-base/1779#-NxENghW8KZVEU1Ssdo7:-NxPonsT6EHw44xihauC:b-896fix) ([raw file](https://github.com/koreader/koreader-base/blob/ad458eaa4fd47c794290b7999e36b03b34ed4b6f/ffi/framebuffer_mxcfb.lua#L296)):*
<details><summary><i>Previously, Frenzie (Frans de Jonge) wrote…</i></summary><blockquote>

Looks like a typo, one that's older I assume but still distracting
</blockquote></details>

Done.

**Pull request merged**
