### PR TITLE
Neuter pkg-config when cross-compiling

### PR DESCRIPTION
**Pull request by NiLuJe**
Re #1102

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1103)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Let's see if stuff horribly breaks.

**Comment by yparitcher** [comment]
this without the patch from #1102 does not fix the issue for me. I still get build errors

**Comment by NiLuJe** [comment]
@Frenzie: Best as I can remember, it's commented out because it overrides the env, which, as I mentioned earlier, I usually set properly myself ;p.

TL;DR: While *I* definitely want it commented, it probably makes sense to have it set by default (I happen to replace that CMakeCross file for my own builds anyway, so the point is moot as far as I'm concerned).

e.g.:

```
┌─(niluje@illyria:pts/15)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(0.30:42%:23:45:%)── pkg-config --exists libbrotlidec && echo "found" || echo "not found"                                                                                                                                                                                                                                                            ──(Sun, May 24)─┘
found
┌─(niluje@illyria:pts/15)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(0.30:42%:23:45:%)── source ~SVN/Configs/trunk/Kindle/Misc/x-compile.sh kobo env                                                                                                                                                                                                                                                                     ──(Sun, May 24)─┘
- correct kobo to Kobo ? ([Y]es/[N]o/[E]dit/[A]bort) -n
* Setting environment up . . .

* Environment has been set up for the KOBO TC, enjoy :)
┌─(niluje@illyria:pts/15)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(0.28:42%:23:45:%)── pkg-config --exists libbrotlidec && echo "found" || echo "not found"                                                                                                                                                                                                                                                            ──(Sun, May 24)─┘
not found
```

**Comment by NiLuJe** [comment]
@yparitcher: With what kind of environment?

**Comment by yparitcher** [comment]
regular running ./kodev

**Comment by NiLuJe** [comment]
If they don't simply break everything, the last few commits *should* make that better, @yparitcher ;).

**Comment by yparitcher** [comment]
works now

**Comment by NiLuJe** [comment]
Cool, thanks for testing :).

**Pull request merged**
