### PR TITLE
thirdparty/freetype 2.13.3

### PR DESCRIPTION
**Pull request by Frenzie**
https://github.com/freetype/freetype/compare/VER-2-13-2...VER-2-13-3

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1901)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Wrong MD5? I get 4425315beb50f913ae12d643e4e121e1.

TODO: show the computed checksum in the log.

**Comment by Frenzie** [comment]
Indeed, me too. I forgot `-L` in curl.

**Comment by benoit-pierre** [comment]
Failure:
```
/usr/local/bin/ccache /usr/bin/clang++   -I/home/ko/project/thirdparty/kpvcrlib/crengine/crengine/include -I/home/ko/project/thirdparty/kpvcrlib/crengine/thirdparty/antiword -I/home/ko/project/thirdparty/kpvcrlib/crengine/thirdparty/chmlib/src -I/home/ko/project/build/staging/include -I/home/ko/project/build/staging/include/freetype2 -I/home/ko/project/build/staging/include/harfbuzz -I/home/ko/project/build/staging/include/fribidi -I/home/ko/project/thirdparty/srell -O2 -ffast-math -pipe -fomit-frame-pointer -DNDEBUG -ffile-prefix-map=/home/ko/project/= -Wno-ignored-optimization-argument -Wno-unknown-warning-option -Wno-array-bounds -Wno-unused-command-line-argument -Wno-self-assign -Wno-parentheses-equality -Wno-macro-redefined -std=gnu++17 -march=native -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -ftabstop=4 -Wall -include /home/ko/project/build/thirdparty/crengine/build/crsetup.h -std=gnu++17 -MD -MT CMakeFiles/crengine.dir/crengine/crengine/src/lvfntman.cpp.o -MF CMakeFiles/crengine.dir/crengine/crengine/src/lvfntman.cpp.o.d -o CMakeFiles/crengine.dir/crengine/crengine/src/lvfntman.cpp.o -c /home/ko/project/thirdparty/kpvcrlib/crengine/crengine/src/lvfntman.cpp
/home/ko/project/thirdparty/kpvcrlib/crengine/crengine/src/lvfntman.cpp:2675:19: error: cannot initialize a variable of type 'char *' with an lvalue of type 'unsigned char *'
            char* tags = outline.tags;
                  ^      ~~~~~~~~~~~~
/home/ko/project/thirdparty/kpvcrlib/crengine/crengine/src/lvfntman.cpp:2676:20: error: cannot initialize a variable of type 'short *' with an lvalue of type 'unsigned short *'
            short* contours = outline.contours;
                   ^          ~~~~~~~~~~~~~~~~
2 errors generated.
```

Unrelated, but interesting:
```
DEPRECATION: CMake support for versions <3.17 is deprecated since Meson 0.62.0.
|
|   However, Meson was only able to find CMake 3.16.3.
|
|   Support for all CMake versions below 3.17.0 will be removed once
|   newer CMake versions are more widely adopted. If you encounter
|   any errors please try upgrading CMake to a newer version first.
```

**Comment by benoit-pierre** [comment]
https://github.com/freetype/freetype/commit/2a7bb4596f566a34fd53932af0ef53b956459d25

**Pull request merged**
