### PR TITLE
relocatable build dir and moved thirdparty build

### PR DESCRIPTION
**Pull request by benoit-pierre**
## Relocatable build directory

Support `make OUTPUT_DIR=build` or `make OUTPUT_DIR=~/dev/koreader/build` (path is relative to base directory when not absolute).

Use cases: different build trees to avoid the need for rebuilding everything when alternating between different branches, simplify CI configuration (same build directory for all platforms).

## Move thirdparty build directories

Under the main build directory, with simpler tree structure.

**Before:**
```
.
├── build/
│   └── x86_64-pc-linux-gnu-debug/
└── thirdparty/
    ├── luajit/
    │   ├── build/
    │   │   ├── git_checkout/
    │   │   └── x86_64-pc-linux-gnu-debug
    │   │       ├── build.ninja
    │   │       ├── CMakeCache.txt
    │   │       ├── CMakeFiles/
    │   │       ├── cmake_install.cmake
    │   │       ├── git_checkout/
    │   │       │   ├── stamp/
    │   │       │   └── tmp/
    │   │       └── luajit-prefix/
    │   │           ├── src/
    │   │           │   ├── luajit/
    │   │           │   ├── luajit-build/
    │   │           │   └── luajit-stamp/
    │   │           └── tmp/
    │   ├── CMakeLists.txt
    │   ├── koreader-luajit-enable-table_pack.patch
    │   ├── koreader-luajit-makefile-tweaks.patch
    │   └── koreader-luajit-verbose-build.patch
    └── tar/
        ├── build/
        │   ├── downloads/
        │   │   └── tar-1.34.tar.gz
        │   └── x86_64-pc-linux-gnu-debug/
        │       ├── build.ninja
        │       ├── CMakeCache.txt
        │       ├── CMakeFiles
        │       ├── cmake_install.cmake
        │       └── tar-prefix/
        │           ├── src/
        │           │   ├── tar/
        │           │   └── tar-stamp/
        │           └── tmp/
        ├── CMakeLists.txt
        ├── tar-1.31-revert-wordsplit-for-android-glob.patch
        └── tar-1.33-remove-o_path-usage.patch
```
**After:**
```
.
├── build/
│   └── x86_64-pc-linux-gnu-debug/
│       └── thirdparty/
│           ├── luajit/
│           │   ├── build.ninja
│           │   ├── CMakeCache.txt
│           │   ├── CMakeFiles/
│           │   ├── cmake_install.cmake
│           │   ├── install/
│           │   ├── log/
│           │   ├── source/
│           │   ├── stamp/
│           │   └── tmp/
│           ├── tar/
│           │   ├── build/
│           │   ├── build.ninja
│           │   ├── CMakeCache.txt
│           │   ├── CMakeFiles
│           │   ├── cmake_install.cmake
│           │   ├── install/
│           │   ├── log/
│           │   ├── source/
│           │   ├── stamp/
│           │   └── tmp/
└── thirdparty/
    ├── luajit/
    │   ├── build/
    │   │   └── source/
    │   ├── CMakeLists.txt
    │   ├── koreader-luajit-enable-table_pack.patch
    │   ├── koreader-luajit-makefile-tweaks.patch
    │   └── koreader-luajit-verbose-build.patch
    └── tar/
        ├── build/
        │   └── downloads/
        │       └── tar-1.34.tar.gz
        ├── CMakeLists.txt
        ├── tar-1.31-revert-wordsplit-for-android-glob.patch
        └── tar-1.33-remove-o_path-usage.patch
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1781)

### CODE REVIEW

**Comment by Frenzie** [comment]
As an aside for other potential readers, you can also use `KOR_BASE` https://github.com/koreader/koreader/blob/12c3c190b012e8c4b070d3e0b4e66b2878a89c7a/Makefile#L2

**Review by Frenzie — APPROVED** [review]
Fine by me, pinging @NiLuJe

**Comment by NiLuJe** [comment]
Love the idea ;).

One small comment about 1cef7713ba02dfc23f5172cc1645f511d2c9d088: how/when.where? Most of our targets do not actually support symlinks?

**Review by NiLuJe — APPROVED** [review]
Nothing jumps out at a quick glance.

Just another thing: I'm assumling `lib32` vs. `lib64` is no longer a concern on multilib systems, given how you removed all the fixed LIBDIR flags?

> Reviewed 54 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1781#-:-NxYY-uX2H4qyW_cR8zo:bquwr4f)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @benoit-pierre)

**Comment by benoit-pierre** [comment]
> Love the idea ;).
> 
> One small comment about [1cef771](https://github.com/koreader/koreader-base/commit/1cef7713ba02dfc23f5172cc1645f511d2c9d088): how/when/where? Most of our targets do not actually support symlinks?

By koreader, I meant the superproject: https://github.com/koreader/koreader/commit/fda3d7ce8397072ffb195cd9e7f0364e5ba1c4d1

**Comment by benoit-pierre** [comment]
> Just another thing: I'm assumling lib32 vs. lib64 is no longer a concern on multilib systems, given how you removed all the fixed LIBDIR flags?

I'm not sure what you're referring to.

**Comment by NiLuJe** [comment]
> > Just another thing: I'm assumling lib32 vs. lib64 is no longer a concern on multilib systems, given how you removed all the fixed LIBDIR flags?
> 
> I'm not sure what you're referring to.

IIRC, CMake, particularly, was probably doing something stupid at some point on multilib systems. e.g., assuming you're building on a multilib 64-bit arch, it was honoring the host's libdir (lib64) for the target libdir (which we pretty much always expect to be lib).

**Comment by benoit-pierre** [comment]
Yes, did notice that when working on the new build system, but I can't remember in which environment… But, FWIR, that was only with cmake (and those `-DCMAKE_INSTALL_LIBDIR=…` are still here).

**Comment by NiLuJe** [comment]
> (and those `-DCMAKE_INSTALL_LIBDIR=…` are still here)

I though I'd noticed a few of those being removed earlier, but at a quick glance, I can only see that happening for `lunasvg` right now ;).

**Comment by benoit-pierre** [comment]
> > (and those `-DCMAKE_INSTALL_LIBDIR=…` are still here)
> 
> I thought I'd noticed a few of those being removed earlier, but at a quick glance, I can only see that happening for `lunasvg` right now ;).

Amended.

**Review by NiLuJe — APPROVED** [review]
> Reviewed 51 of 51 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1781)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @benoit-pierre)

**Pull request merged**
