### PR TITLE
Proper REAGL handling on Kobo Aura

### PR DESCRIPTION
**Pull request by NiLuJe**
Needs testing, I don't have the device ;).
Based on @cramoisi's logs from [KO#3130](https://github.com/koreader/koreader/issues/3130).

### CODE REVIEW

**Comment by NiLuJe** [comment]
Sneaked in the last bit to make my life less of a nightmare in https://github.com/NiLuJe/koreader/tree/uimanager-wip

Should be harmless, and is arguably more correct anyway.

**Comment by NiLuJe** [comment]
On a slightly related note, the whole marker handling for tracked marker feels a bit more complex than it should, we're basically doing wait_for_marker ourselves instead of relying on the kernel.
We could pretty much fire & forget a rotating 10 marker ids and be done with it ;).

**Comment by NiLuJe** [comment]
Okay, rewrote REAGL handling, period. :D.

It behaves properly on my PW2, I need to check what happens on non-REAGL devices, though.

**Comment by NiLuJe** [comment]
Okay, tested on my H2O, seems okay there too.

The only mystical bit is collision_test handling on Kindles... I'm not quite sure where the fuck those magic numbers come from, and the state of the kernel sources is inconsistent (the headers are up to date, but the driver source is... weird. There's bits of the updates in, and not others, and while there's a gigantic list of patches, some of which do include the update to this ioctl, it appears to be half-in (some defines are there, but the iocitl's signature doesn't match the header, and what's actually in the release binaries).

AFAICT, it relates to the id of the LUT in charge of a specific update, with 0 being we don't care about collision. But that doesn't explain the 1642888, unless that's INVALID_LUT (-1) after a number of weird-ass bit operations...

If shit goes wrong on Kindle, that's the first thing to go ;).

**Comment by cramoisi** [comment]
I pushed the files minus the 3 last commit on the device.

**Comment by poire-z** [comment]
Tested with up to https://github.com/koreader/koreader-base/pull/676/commits/7f77f480d0993c2525674ac13d3b858373302cf4 since last evening: no problem (and no change :) noticed on my GloHD.

**Comment by cramoisi** [comment]
@NiLuJe : if you need some specific test, don't hesitate to point them out.

**Comment by NiLuJe** [comment]
@cramoisi : Nothing specific, really, the only massive REAGL user is the reader itself, so, nothing jumping out when reading is pretty good news ;).

I should (hopefully) be done with the reset of this (w/ the uimanager-wip branch) soon, so once that other PR pops up, real reviewing & testing can begin ;).

**Comment by NiLuJe** [comment]
There we go!

**Comment by NiLuJe** [comment]
If everyone's happy with this, it's ready to go in (and then we can get [KO#3983](https://github.com/koreader/koreader/pull/3983) moving ;).

**Comment by cramoisi** [comment]
happy here.

**Comment by Frenzie** [comment]
Haven't tested but looks fine

**Pull request merged**
