### PR TITLE
More alpha-blending fixes

### PR DESCRIPTION
**Pull request by NiLuJe**
Mainly add a method to properly handle MuPDF's premultiplied alpha

### CODE REVIEW

**Comment by Frenzie** [comment]
lgtm, but maybe we could slightly expand on the tests? Seems kinda easy to break when modding otherwise. :-)

https://github.com/koreader/koreader-base/blob/e2ea51dad6b46cedde8ac1dcc9e6120d802466c3/spec/unit/blitbuffer_spec.lua#L306-L321

**Comment by NiLuJe** [comment]
That can be arranged ;). Any specific ideas besides a simple pmulblend test?

**Comment by Frenzie** [comment]
Not really beyond that atm, no.

**Comment by NiLuJe** [comment]
I'll add a few when I get back home ;).

**Pull request merged**
