### PR TITLE
Honor dithering requests from UIManager

### PR DESCRIPTION
**Pull request by NiLuJe**
... on supported devices.

That is:

Kindle: KOA2+ (KOA2, PW4)
Kobo: Mk.7+ (Clara, Forma)

Possibly Cervantes 3 & 4, but the required "new" codepath isn't implemented in KO (pinging @pazos) ;).

Used by [KO#4541](https://github.com/koreader/koreader/pull/4541)

### CODE REVIEW

**Comment by NiLuJe** [comment]
If someone's looking for technical details, this is an EPDC V2 feature, which does quantization + ordered dithering, with a fairly nice pattern.

I'd already noticed that simple ordered dithering patterns were more than "good-enough", but this one is really pretty decent.

Even throwing a nasty testcase full of gradients at it leads to pretty good results!

And that's coming from a guy [that *really* cares about this stuff](https://www.mobileread.com/forums/showpost.php?p=3728291&postcount=17) ;).

**Comment by pazos** [comment]
> Possibly Cervantes 3 & 4, but the required "new" codepath isn't implemented in KO 

@NiLuJe: I don't want to mess with my main reader, plus I remember I tried some dithering calls (x1, x4, ntx_d8) and they were awful.

**Comment by NiLuJe** [comment]
@pazos : I was thinking of what amounts to the Mk. 7 codepath (which you implemented in [FBInk](https://github.com/NiLuJe/FBInk/blob/590c1dbec54871164b13ea044fd15e02a09d7c78/fbink.c#L1401-L1462)), not those weird and legacy flags which date back to the equally weird and esoteric Aura, IIRC ;).

Namely, the new update_data struct with the dither_mode/quant_bit fields (and the mxcfb_dithering_mode enum), not the old, quirky and indeed potentially horribly broken legacy EPDC_FLAG ones ;).

**Comment by NiLuJe** [comment]
It's hidden behind the `-D` flag in FBInk, if you want to try it out on your device.

And here's my usual torture test, thanks to jackie_w on MR ;).
gradient_forma

**Comment by Frenzie** [comment]
Reminds me of your standard printer test page type thing:

https://opensource.apple.com/source/cups/cups-136.9/cups/test/testfile.pdf

**Comment by NiLuJe** [comment]
It has the added benefit of having a large magenta section, which is a nice color to pickup differences in greyscaling methods (it ends up looking fairly different depending on whether you gamma-correct grayscale, or do it in linear light).

Which was a bonus point, in my case ;).

I have a full archive of dithering experiments in Nickel [over here](http://files.ak-team.com/niluje/mrpub/Other/Kobo-Dithering-Test-4.12.tar.xz), especially as far as full-screen covers are concerned ;).

**Comment by NiLuJe** [comment]
@pazos : Speaking of, given the age of the Cervantes 3, if that 2016 mention is accurate, I'd be inclined to think only the Cervantes 4 could actually support that codepath?

**Comment by Frenzie** [comment]
If you want to take a break, have a look at this: https://www.youtube.com/watch?v=EySDyp1SQ-E

**Comment by Frenzie** [comment]
@pazos Is https://github.com/koreader/android-luajit-launcher/blob/14f9c2491d181db34ed694e0b9a7d307762919be/src/org/koreader/device/rockchip/RK30xxEPDController.java#L47 the same thing? (If so, in the long term Android could tap into this as well.)

**Comment by pazos** [comment]
> I was thinking of what amounts to the Mk. 7 codepath (which you implemented in FBInk), not those weird and legacy flags which date back to the equally weird and esoteric Aura, IIRC ;).

> Speaking of, given the age of the Cervantes 3, if that 2016 mention is accurate, I'd be inclined to think only the Cervantes 4 could actually support that codepath?

@NiLuJe: yeah, the code in FBInk is broken, it just works because it is never called (I bet you can find why), I will submit a patch when I have some time. So no, the new codepath won't be supported in current cervantes models.

@Frenzie: i didn't test the Dither mode on Android, but I think it will be broken like any other EPD mode in the controller. The only one that worked (other than FULL or black2white) was A2, which was nice for scrolling but a real pain for fast page turning. Probably things are better with recent devices.

**Comment by NiLuJe** [comment]
@pazos : Even on a Cervantes 4?

Where did the mxcfb header come from then, Kobo?

Because, yeah, right now, I woudln't say that it's never called, unless I'm reading things wrong, it's kind of worse: the "classic" ioctl is called, but with a struct full of the new stuff.
Why that doesn't horribly blow up is beyond me ;).

**Comment by pazos** [comment]
> So I just tried to clear that up in FBInk (bascially getting rid of the cervantes_new codepath, which should match KOReader's behavior), could you check that I didn't do anything stupid when you have the time? ;)

Look good to me. Again sorry for the mess :sob:

**Comment by NiLuJe** [comment]
@pazos : :tada:

No worries, I remember how the Aura quirks threw me for a loop at the time, and this turned out to be fairly similar ;).

**Comment by Frenzie** [comment]
@NiLuJe Were we waiting on anything to merge this one?

**Comment by NiLuJe** [comment]
@Frenzie : Nope, it's good to go :).

**Comment by ptrm** [comment]
How about Aura One? Too old for this ;) ?

**Comment by NiLuJe** [comment]
Yep, Mk. 7 only ;).

**Pull request merged**
