### PR TITLE
Bump zstandard to v1.5.0

### PR DESCRIPTION
**Pull request by NiLuJe**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-base/1371)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by jimman2003** [comment]
Nice!

**Comment by jimman2003** [comment]
On a somewhat unrelatef note, just got [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) working in zstd!

**Comment by Frenzie** [comment]
If you're referring to this repo, for the moment we're still on CMake 3.5, although that will change in the not too far off future. Cf. https://github.com/koreader/koreader-base/pull/851

**Comment by poire-z** [comment]
Possibly unrelated to this issue, or not :/

I get some crash when running appimage v2021.06 or 08 or 09 (but not a v2021.03-12 I had around), on my updated debian 11 (so, probably no issue at the times I tested these on debian 10), when Start with last book, and just invoking History (when display mode set to show covers, not when with classic mode or detailed with no image), so probably when it's about to decompress the cached cover images. I sometimes can see it display one cover.

```
ffi.load (assisted searchpath): ./libs/libsqlite3.so
09/22/21-08:46:42 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_MONOTONIC

Thread 1 "luajit" received signal SIGSEGV, Segmentation fault.
0x00007ffff67940fd in ZSTD_freeDDict () from /usr/lib/x86_64-linux-gnu/libzstd.so.1
(gdb) bt
#0  0x00007ffff67940fd in ZSTD_freeDDict () from /usr/lib/x86_64-linux-gnu/libzstd.so.1
#1  0x00007fffc7081a07 in ZSTD_decompressDCtx () from libs/libzstd.so.1
#2  0x0000555555428eb6 in ?? ()
#3  0x000055555544c5d9 in ?? ()
#4  0x0000555555424503 in ?? ()
#5  0x0000555555426a85 in ?? ()
#6  0x0000555555413fcc in lua_pcall ()
#7  0x000055555540852e in ?? ()
#8  0x0000555555409402 in ?? ()
#9  0x0000555555426a85 in ?? ()
#10 0x000055555541401d in lua_cpcall ()
#11 0x0000555555408036 in main ()
```
Installed Debian11 libzstd1 version is 1.4.8+dfsg-2.1 : https://packages.debian.org/bullseye/libzstd1
Previous Debian 10 libzstd1 was 1.3.8+dfsg-3+deb10u2 : https://packages.debian.org/buster/libzstd1
No issue with the emulator which is using the one we ship and build.

Got a bunch of other strange things when playing at removing bookinfo.sdb to start from a clean one:

```
ffi.load (assisted searchpath): ./libs/libsqlite3.so
09/22/21-08:56:25 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_MONOTONIC
09/22/21-08:56:36 WARN  BookInfo cache DB schema updated from version 0 to version 20201210
09/22/21-08:56:36 WARN  Deleting existing ./settings/bookinfo_cache.sqlite3 to recreate it
[Detaching after fork from child process 17625]
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
[Detaching after fork from child process 17630]
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
error in subprocess: frontend/document/document.lua:392: attempt to concatenate field 'mod_time' (a nil value)
stack traceback:
 frontend/document/document.lua:392: in function 'getFullPageHash'
 frontend/document/document.lua:397: in function 'renderPage'
 frontend/document/koptinterface.lua:319: in function 'getCoverPageImage'
 plugins/coverbrowser.koplugin/bookinfomanager.lua:520: in function 'extractBookInfo'
 plugins/coverbrowser.koplugin/bookinfomanager.lua:694: in function 'func'
 ./ffi/util.lua:343: in function <./ffi/util.lua:314>
 [C]: in function 'xpcall'
 ./ffi/util.lua:314: in function 'runInSubProcess'
 plugins/coverbrowser.koplugin/bookinfomanager.lua:702: in function 'extractInBackground'
 plugins/coverbrowser.koplugin/covermenu.lua:143: in function 'action'
 frontend/ui/uimanager.lua:1201: in function '_checkTasks'
 frontend/ui/uimanager.lua:1599: in function 'handleInput'
 frontend/ui/uimanager.lua:1707: in function 'run'
 reader.lua:290: in main chunk
```

**Comment by NiLuJe** [comment]
Doesn't the appimage ship our own zstd build? Because, yeah, a different SOVER won't do ;).

**Comment by poire-z** [comment]
Yes, it's shipped, and even loaded by the luajit process - but so is my system version :/
Below is the list of files opened by the luajit process.
That's with the `--appimage-extract` extracted appimage.
By just running the appimage binary, I also get a segfault - but I get no backtrace when gbd'ing it, so can't confirm it's the same segfault reason.

```
21518 ./luajit reader.lua -d
        /kobo/squashfs-root-v2021.09/luajit
        /lib/x86_64-linux-gnu/ld-2.31.so
        /lib/x86_64-linux-gnu/libc-2.31.so
        /lib/x86_64-linux-gnu/libcom_err.so.2.1
        /lib/x86_64-linux-gnu/libdbus-1.so.3.19.13
        /lib/x86_64-linux-gnu/libdl-2.31.so
        /lib/x86_64-linux-gnu/libexpat.so.1.6.12
        /lib/x86_64-linux-gnu/libgcc_s.so.1
        /lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
        /lib/x86_64-linux-gnu/libkeyutils.so.1.9
        /lib/x86_64-linux-gnu/liblzma.so.5.2.5
        /lib/x86_64-linux-gnu/libm-2.31.so
        /lib/x86_64-linux-gnu/libnss_files-2.31.so
        /lib/x86_64-linux-gnu/libpthread-2.31.so
        /lib/x86_64-linux-gnu/libresolv-2.31.so
        /lib/x86_64-linux-gnu/librt-2.31.so
        /lib/x86_64-linux-gnu/libtinfo.so.6.2
        /lib/x86_64-linux-gnu/libtirpc.so.3.0.0
        /lib/x86_64-linux-gnu/libz.so.1.2.11
        /kobo/squashfs-root-v2021.09/common/mime/mcore.so
        /kobo/squashfs-root-v2021.09/common/socket/score.so
        /kobo/squashfs-root-v2021.09/common/ssl.so
        /kobo/squashfs-root-v2021.09/fonts/droid/DroidSansMono.ttf
        /kobo/squashfs-root-v2021.09/fonts/freefont/FreeSans.ttf
        /kobo/squashfs-root-v2021.09/fonts/freefont/FreeSerif.ttf
        /kobo/squashfs-root-v2021.09/fonts/nerdfonts/symbols.ttf
        /kobo/squashfs-root-v2021.09/fonts/noto/NotoSans-Bold.ttf
        /kobo/squashfs-root-v2021.09/fonts/noto/NotoSans-Regular.ttf
        /kobo/squashfs-root-v2021.09/fonts/noto/NotoSansArabicUI-Regular.ttf
        /kobo/squashfs-root-v2021.09/fonts/noto/NotoSansCJKsc-Regular.otf
        /kobo/squashfs-root-v2021.09/fonts/noto/NotoSansDevanagariUI-Regular.ttf
        /kobo/squashfs-root-v2021.09/fonts/noto/NotoSerif-Bold.ttf
        /kobo/squashfs-root-v2021.09/fonts/noto/NotoSerif-Regular.ttf
        /kobo/squashfs-root-v2021.09/libs/libblitbuffer.so
        /kobo/squashfs-root-v2021.09/libs/libcrengine.so
        /kobo/squashfs-root-v2021.09/libs/libcrypto.so.1.1
        /kobo/squashfs-root-v2021.09/libs/libfreetype.so.6
        /kobo/squashfs-root-v2021.09/libs/libfribidi.so.0
        /kobo/squashfs-root-v2021.09/libs/libharfbuzz.so.0
        /kobo/squashfs-root-v2021.09/libs/libjpeg.so.8
        /kobo/squashfs-root-v2021.09/libs/libkoreader-cre.so
        /kobo/squashfs-root-v2021.09/libs/libkoreader-lfs.so
        /kobo/squashfs-root-v2021.09/libs/libkoreader-nnsvg.so
        /kobo/squashfs-root-v2021.09/libs/libkoreader-xtext.so
        /kobo/squashfs-root-v2021.09/libs/liblodepng.so
        /kobo/squashfs-root-v2021.09/libs/libmupdf.so
        /kobo/squashfs-root-v2021.09/libs/libpng16.so.16
        /kobo/squashfs-root-v2021.09/libs/libsqlite3.so
        /kobo/squashfs-root-v2021.09/libs/libssl.so.1.1
        /kobo/squashfs-root-v2021.09/libs/libunibreak.so.3
        /kobo/squashfs-root-v2021.09/libs/libutf8proc.so.2
        /kobo/squashfs-root-v2021.09/libs/libwrap-mupdf.so
        /kobo/squashfs-root-v2021.09/libs/libzstd.so.1        ================= ours
        /kobo/squashfs-root-v2021.09/luajit
        /kobo/squashfs-root-v2021.09/rocks/lib/lua/5.1/lpeg.so
        /kobo/fonts/arbutusslab-regular.ttf
        /usr/lib/locale/locale-archive
        /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
        /usr/lib/x86_64-linux-gnu/gconv/ISO8859-1.so
        /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
        /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
        /usr/lib/x86_64-linux-gnu/libGL.so.1.7.0
        /usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libLLVM-11.so.1
        /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.14.0
        /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0
        /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
        /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
        /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
        /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
        /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
        /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
        /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
        /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
        /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
        /usr/lib/x86_64-linux-gnu/libXss.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
        /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
        /usr/lib/x86_64-linux-gnu/libbsd.so.0.11.3
        /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
        /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
        /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
        /usr/lib/x86_64-linux-gnu/libedit.so.2.0.63
        /usr/lib/x86_64-linux-gnu/libelf-0.183.so
        /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0
        /usr/lib/x86_64-linux-gnu/libgbm.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
        /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
        /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
        /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
        /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
        /usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
        /usr/lib/x86_64-linux-gnu/libmd.so.0.0.4
        /usr/lib/x86_64-linux-gnu/libnsl.so.2.0.1
        /usr/lib/x86_64-linux-gnu/libogg.so.0.8.4
        /usr/lib/x86_64-linux-gnu/libopus.so.0.8.0
        /usr/lib/x86_64-linux-gnu/libpulse.so.0.23.0
        /usr/lib/x86_64-linux-gnu/libsensors.so.5.0.0
        /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.31
        /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
        /usr/lib/x86_64-linux-gnu/libsystemd.so.0.30.0
        /usr/lib/x86_64-linux-gnu/libudev.so.1.7.0
        /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.9
        /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.12
        /usr/lib/x86_64-linux-gnu/libvulkan.so.1.2.162
        /usr/lib/x86_64-linux-gnu/libwayland-client.so.0.3.0
        /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libwayland-server.so.0.1.0
        /usr/lib/x86_64-linux-gnu/libwrap.so.0.7.6
        /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
        /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
        /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
        /usr/lib/x86_64-linux-gnu/libz3.so.4
        /usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8            ============== my !
        /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-14.2.so
        [heap]
        [stack]
        [vdso]
        [vvar]
        /dev/pts/3 (3)
        /kobo/squashfs-root-v2021.09/ev.log
        /kobo/test/test-issue8034-css_content_encoding.epub
```

**Comment by NiLuJe** [comment]
Ah, it might be pulled by one of the system dependencies, that's... not great ;/.

Possibly some X or freedesktop stuff...

**Comment by NiLuJe** [comment]
Or pulseaudio :s

**Comment by NiLuJe** [comment]
Wait, it's actually the same major SOVER... Does Debian's multilib setup
rely on rpath or something?

I'll check what happens over here when I get back home tonight.

**Comment by Frenzie** [comment]
Pulse seems unlikely. Then again, they all do.

My output from `apt-cache rdepends libzstd1`: [rdepends.txt](https://github.com/koreader/koreader-base/files/7210479/rdepends.txt)

**Comment by NiLuJe** [comment]
Yup, #worksforme ;p.

```
┌─(niluje@illyria:pts/11)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(0.51:29%:18:31:%)── cat /proc/$(pidof luajit)/maps | ag libz                                                                                                                                                                                                                                                                                        ──(Sat, Sep 25)─┘
7fce034af000-7fce035bb000 r-xp 00000000 00:31 529532636                  /tmp/.mount_koreadXzdAtS/libs/libzstd.so.1
7fce035bb000-7fce037bb000 ---p 0010c000 00:31 529532636                  /tmp/.mount_koreadXzdAtS/libs/libzstd.so.1
7fce037bb000-7fce037bc000 r--p 0010c000 00:31 529532636                  /tmp/.mount_koreadXzdAtS/libs/libzstd.so.1
7fce037bc000-7fce037bd000 rw-p 0010d000 00:31 529532636                  /tmp/.mount_koreadXzdAtS/libs/libzstd.so.1
7fce037bd000-7fce037d3000 r-xp 00000000 00:31 529532528                  /tmp/.mount_koreadXzdAtS/libs/libz.so.1
7fce037d3000-7fce039d2000 ---p 00016000 00:31 529532528                  /tmp/.mount_koreadXzdAtS/libs/libz.so.1
7fce039d2000-7fce039d3000 r--p 00015000 00:31 529532528                  /tmp/.mount_koreadXzdAtS/libs/libz.so.1
7fce039d3000-7fce039d4000 rw-p 00016000 00:31 529532528                  /tmp/.mount_koreadXzdAtS/libs/libz.so.1
```

**Comment by poire-z** [comment]
One of the other things loaded that depends on a libzstd is:
```
$ ldd /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
[...]
 libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9ce9f2a000)
 libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f9ce9e4f000)
 libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9ce9e47000)
[...]
```

**Comment by NiLuJe** [comment]
> One of the other things loaded that depends on a libzstd is:
> 
> ```
> $ ldd /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
> [...]
>  libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9ce9f2a000)
>  libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f9ce9e4f000)
>  libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9ce9e47000)
> [...]
> ```
> 
> (I'm using a X server on Windows, and KOReader on a remote linux, if that matters and explain swrast_dri.so as my driver ?)

That was going to be my next question, yeah ;p.

FWIW:

```
┌─(niluje@illyria:pts/11)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(0.25:30%:20:47:%)── cat /proc/$(pidof luajit)/maps | awk '{print $6}' | sort -u                                                                                                                                                                                                                                                                     ──(Sat, Sep 25)─┘

/dev/dri/renderD128
[heap]
/home/niluje/.compose-cache/l4_030_313cb605_00280cc0
/lib64/ld-2.33.so
/lib64/libc-2.33.so
/lib64/libdl-2.33.so
/lib64/liblzma.so.5.2.5
/lib64/libm-2.33.so
/lib64/libpthread-2.33.so
/lib64/libresolv-2.33.so
/lib64/librt-2.33.so
/lib64/libtinfo.so.6.2
/lib64/libudev.so.1.7.2
/lib64/libwrap.so.0.7.6
/memfd:xshmfence
/mnt/data/XDG/cache/niluje/mesa_shader_cache/index
[stack]
/tmp/.mount_koread2N5EBu/common/mime/mcore.so
/tmp/.mount_koread2N5EBu/common/socket/score.so
/tmp/.mount_koread2N5EBu/common/ssl.so
/tmp/.mount_koread2N5EBu/fonts/droid/DroidSansMono.ttf
/tmp/.mount_koread2N5EBu/fonts/freefont/FreeSans.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoNaskhArabic-Bold.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSansArabicUI-Bold.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSansArabicUI-Regular.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSans-Bold.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSansCJKsc-Regular.otf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSans-Regular.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSerif-Bold.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSerif-Italic.ttf
/tmp/.mount_koread2N5EBu/fonts/noto/NotoSerif-Regular.ttf
/tmp/.mount_koread2N5EBu/libs/libblitbuffer.so
/tmp/.mount_koread2N5EBu/libs/libbsd.so.0
/tmp/.mount_koread2N5EBu/libs/libcrengine.so
/tmp/.mount_koread2N5EBu/libs/libcrypto.so.1.1
/tmp/.mount_koread2N5EBu/libs/libfreetype.so.6
/tmp/.mount_koread2N5EBu/libs/libfribidi.so.0
/tmp/.mount_koread2N5EBu/libs/libharfbuzz.so.0
/tmp/.mount_koread2N5EBu/libs/libjpeg.so.8
/tmp/.mount_koread2N5EBu/libs/libkoreader-cre.so
/tmp/.mount_koread2N5EBu/libs/libkoreader-lfs.so
/tmp/.mount_koread2N5EBu/libs/libkoreader-nnsvg.so
/tmp/.mount_koread2N5EBu/libs/libkoreader-xtext.so
/tmp/.mount_koread2N5EBu/libs/liblodepng.so
/tmp/.mount_koread2N5EBu/libs/libmupdf.so
/tmp/.mount_koread2N5EBu/libs/libpng16.so.16
/tmp/.mount_koread2N5EBu/libs/libSDL2.so
/tmp/.mount_koread2N5EBu/libs/libsndio.so.6.1
/tmp/.mount_koread2N5EBu/libs/libsqlite3.so
/tmp/.mount_koread2N5EBu/libs/libssl.so.1.1
/tmp/.mount_koread2N5EBu/libs/libunibreak.so.3
/tmp/.mount_koread2N5EBu/libs/libutf8proc.so.2
/tmp/.mount_koread2N5EBu/libs/libwrap-mupdf.so
/tmp/.mount_koread2N5EBu/libs/libXss.so.1
/tmp/.mount_koread2N5EBu/libs/libz.so.1
/tmp/.mount_koread2N5EBu/libs/libzstd.so.1
/tmp/.mount_koread2N5EBu/luajit
/tmp/.mount_koread2N5EBu/rocks/lib/lua/5.1/lpeg.so
/tmp/.mount_koread2N5EBu/rocks/lib/lua/5.1/rapidjson.so
/usr/lib64/dri/radeonsi_dri.so
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.2.0/libgcc_s.so.1
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.2.0/libstdc++.so.6.0.29
/usr/lib64/gconv/gconv-modules.cache
/usr/lib64/libasound.so.2.0.0
/usr/lib64/libasyncns.so.0.3.1
/usr/lib64/libdbus-1.so.3.19.13
/usr/lib64/libdrm_amdgpu.so.1.0.0
/usr/lib64/libdrm_radeon.so.1.0.1
/usr/lib64/libdrm.so.2.4.0
/usr/lib64/libelf-0.185.so
/usr/lib64/libexpat.so.1.8.1
/usr/lib64/libffi.so.8.1.0
/usr/lib64/libFLAC.so.8.3.0
/usr/lib64/libglapi.so.0.0.0
/usr/lib64/libGLdispatch.so.0.0.0
/usr/lib64/libGL.so.1.7.0
/usr/lib64/libGLX_mesa.so.0.0.0
/usr/lib64/libGLX.so.0.0.0
/usr/lib64/libicudata.so.69.1
/usr/lib64/libicuuc.so.69.1
/usr/lib64/libogg.so.0.8.5
/usr/lib64/libopus.so.0.8.0
/usr/lib64/libpulse.so.0.24.0
/usr/lib64/libsndfile.so.1.0.31
/usr/lib64/libvorbisenc.so.2.0.12
/usr/lib64/libvorbis.so.0.4.9
/usr/lib64/libwayland-client.so.0.3.0
/usr/lib64/libwayland-cursor.so.0.0.0
/usr/lib64/libwayland-egl.so.1.0.0
/usr/lib64/libX11.so.6.4.0
/usr/lib64/libX11-xcb.so.1.0.0
/usr/lib64/libXau.so.6.0.0
/usr/lib64/libxcb-dri2.so.0.0.0
/usr/lib64/libxcb-dri3.so.0.0.0
/usr/lib64/libxcb-glx.so.0.0.0
/usr/lib64/libxcb-present.so.0.0.0
/usr/lib64/libxcb-shm.so.0.0.0
/usr/lib64/libxcb.so.1.1.0
/usr/lib64/libxcb-sync.so.1.0.0
/usr/lib64/libxcb-xfixes.so.0.0.0
/usr/lib64/libXcursor.so.1.0.2
/usr/lib64/libXdmcp.so.6.0.0
/usr/lib64/libXext.so.6.4.0
/usr/lib64/libXfixes.so.3.1.0
/usr/lib64/libXinerama.so.1.0.0
/usr/lib64/libXi.so.6.1.0
/usr/lib64/libxkbcommon.so.0.0.0
/usr/lib64/libxml2.so.2.9.12
/usr/lib64/libXrandr.so.2.2.0
/usr/lib64/libXrender.so.1.3.0
/usr/lib64/libxshmfence.so.1.0.0
/usr/lib64/libXxf86vm.so.1.0.0
/usr/lib64/llvm/12/lib64/libLLVM-12.so
/usr/lib64/locale/locale-archive
/usr/lib64/pulseaudio/libpulsecommon-15.0.so
[vdso]
[vvar]
```

(On an actual Radeon box ;p).

**Comment by poire-z** [comment]
Well, been having many other segfault/crashes related to libpthread.so and swrast_dri.so.
Looks like I can avoid them by using:
`export LIBGL_DRIVERS_PATH=/non_existant` (ref https://docs.mesa3d.org/envvars.html)
which causes this to be logged at start up:
```
Starting SDL in koreader/base/build/x86_64-linux-gnu-debug/
libGL error: MESA-LOADER: failed to open swrast: /non_existant/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /non_existant)
libGL error: failed to load driver: swrast
```
and I haven't got a single segfault since then !

So, no OpenGL 3D rendering of EPUBs for me - but I'll be fine :)

**Comment by poire-z** [comment]
> Looks like I can avoid them by using:
`export LIBGL_DRIVERS_PATH=/non_existant `
and I haven't got a single segfault since then !

Well, still no segfault which is nice, but ... with this, when I resize KOReader's window, nothing is drawn: I 'm stuck with a big full white blank window :/

**Comment by poire-z** [comment]
^solved by using swrast_dri.so from debian10 (that does not link to libzstd.so) (and libLLVM-7.so.1 and libffi.so.6) and:
```sh
export LIBGL_DRIVERS_PATH=/path/to/buster_dri_swrast
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/buster_dri_swrast
```

**Comment by poire-z** [comment]
Following up on my above off-topic adventure with debian upgrades and my old Windows X server...
Upgraded to Debian12, of course the X/swrast_dri stuff didn't work anymore.
Had to upgrade my [old](https://sourceforge.net/projects/xming/) X Server from 2007 to somethng more [modern](https://sourceforge.net/projects/vcxsrv/), and I managed to get my emulator to display.

I noticed something bothering when resizing the emulator with the mouse by dragging edges: resize events are sent all along my mouse press>move>release, which is not nice with crengine rerendering uselessly for all the intermediate window sizes.
Somehow, my old X server must have sent the resize event only at the end, at release time, and it was pretty convenient.
How is your experience, you people with real and pure-linux X11/Wayland, with this ?

I'm wondering if we could somehow buffer these SDL_WINDOWEVENT_RESIZED and SDL_WINDOWEVENT_SIZE_CHANGED events, and emit the last one only after some small delay when no new one has been seen.
Or is there some X11/GL/SDL env variables to control this behaviour? Couldn't find anything related...

**Comment by Frenzie** [comment]
Both Windows and X11 have a setting as to whether windows should be redrawn while resizing or not, but I don't think you can set that per app.

A quick search produced what you're asking in reverse: `https://github.com/libsdl-org/SDL/issues/1059`

**Pull request merged**
