### PR TITLE
Pass arbitrary DjVu text annotations to frontend

### PR DESCRIPTION
**Pull request by xelxebar**
## Overview

Partially addresses koreader/koreader#2943.

This just transparently translates the annotation tree into a Lua table. The frontend needs to be prepared to handle this more flexible structure. Fortunately, almost all DjVu files in practice adhere to the rigid `page -> line -> word` hierarchy, so this patch should transparently work without any noticeable difference in practice.

## Comments

The final product here is my original implementation, which departs from the prevailing style of `djvu.c`, so I made an attempt at orthogonalizing style choices into the second commit.

Currently, `djvu.c` has a lot of magic numbers and repeated code, so my goal was to give these understandable names and make them reusable. Arguably, this should be it's own pull request, and be  carried out file-wide, but I figured that the comparison here might help review, so am including it.

### CODE REVIEW

**Comment by Frenzie** [comment]
Btw, in principle the coding style of the project is with 4 spaces instead of tabs, but I suppose we should just keep this file in tabs.

But part of me wonders if we should migrate "organically". ;-)

**Comment by xelxebar** [comment]
@Frenzie 
Roger on the spaces vs. tabs. I have half a mind to do some housecleaning on `djvu.c` anyway, and if I do that might be the time to switch. Or did you mean migrate everything else the other way? lol

Thanks for the props! I put a Doxygen-style comment header on `lua_settable_djvu_anno`, but is there any project convention on this too? I haven't noticed any from my little bit of poking around.

**Comment by xelxebar** [comment]
Strange that `spec/unit/md5_spec.lua` would be failing on this.

**Comment by Frenzie** [comment]
> Thanks for the props! I put a Doxygen-style comment header on lua_settable_djvu_anno, but is there any project convention on this too? I haven't noticed any from my little bit of poking around.

The project is mainly Lua. We don't really have any formal C conventions. However, if it doesn't matter for Doxygen then it might be best to stick closer to the luadoc style for project-wide consistency, in this case with an `@` instead of a `\`: https://github.com/koreader/koreader/blob/c0ba6ae48ea3ee9b693448b43e2c5f30db5991b7/frontend/util.lua#L70-L77

> Strange that spec/unit/md5_spec.lua would be failing on this.

It's not related to this PR. It's some issue with the Docker Clang container I made, but I can't reproduce it locally (in the exact same Docker container) and the CircleCI SSH login didn't work for me yesterday.

I have no idea why it's failing.

**Comment by xelxebar** [comment]
Push change to comment. Doxygen accepts `@` as well.
Thanks for the quick feedback.

**Pull request merged**
